// This file has been automatically generated by utils/settings.rb
// Don't make any modifications to it. They will be lost.

#include "platform.h"
#include "config/parameter_group_ids.h"
#include "fc/settings.h"
#include "sensors/gyro.h"
#include "sensors/acceleration.h"
#include "sensors/compass.h"
#include "sensors/barometer.h"
#include "rx/rx.h"
#include "rx/spektrum.h"
#include "flight/mixer.h"
#include "flight/failsafe.h"
#include "sensors/boardalignment.h"
#include "sensors/battery_config_structs.h"
#include "sensors/battery_config_structs.h"
#include "flight/mixer_profile.h"
#include "flight/servos.h"
#include "fc/control_profile_config_struct.h"
#include "flight/imu.h"
#include "config/general_settings.h"
#include "flight/ez_tune.h"
#include "io/gps.h"
#include "fc/rc_controls.h"
#include "flight/pid.h"
#include "navigation/navigation.h"
#include "io/serial.h"
#include "telemetry/telemetry.h"
#include "telemetry/sim.h"
#include "fc/config.h"
#include "fc/rc_modes.h"
#include "common/time.h"
#include "drivers/display.h"
#include "fc/config.h"
#include "drivers/light_ws2811strip.h"
#include "drivers/dronecan/dronecan.h"
#pragma GCC diagnostic ignored "-Wunused-const-variable"
const pgn_t settingsPgn[] = {
	PG_GYRO_CONFIG,
	PG_ACCELEROMETER_CONFIG,
	PG_COMPASS_CONFIG,
	PG_BAROMETER_CONFIG,
	PG_RX_CONFIG,
	PG_MOTOR_CONFIG,
	PG_FAILSAFE_CONFIG,
	PG_BOARD_ALIGNMENT,
	PG_BATTERY_METERS_CONFIG,
	PG_BATTERY_PROFILES,
	PG_MIXER_PROFILE,
	PG_REVERSIBLE_MOTORS_CONFIG,
	PG_SERVO_CONFIG,
	PG_CONTROL_PROFILES,
	PG_IMU_CONFIG,
	PG_ARMING_CONFIG,
	PG_GENERAL_SETTINGS,
	PG_EZ_TUNE,
	PG_GPS_CONFIG,
	PG_RC_CONTROLS_CONFIG,
	PG_PID_PROFILE,
	PG_POSITION_ESTIMATION_CONFIG,
	PG_NAV_CONFIG,
	PG_TELEMETRY_CONFIG,
	PG_SYSTEM_CONFIG,
	PG_MODE_ACTIVATION_OPERATOR_CONFIG,
	PG_TIME_CONFIG,
	PG_DISPLAY_CONFIG,
	PG_BEEPER_CONFIG,
	PG_LEDPIN_CONFIG,
	PG_DRONECAN_CONFIG,
};
const uint8_t settingsPgnCounts[] = {
	14,
	12,
	13,
	3,
	14,
	4,
	12,
	3,
	9,
	14,
	12,
	3,
	7,
	19,
	10,
	4,
	1,
	10,
	11,
	7,
	81,
	22,
	89,
	21,
	4,
	1,
	2,
	1,
	3,
	1,
	4,
};
static const uint8_t settingNamesWords[] = {
	0x70,0x6c, /* "nav" */ 
	0x3,0x5c, /* "fw" */ 
	0xd,0x18, /* "mc" */ 
	0x24,0x1a,0x14, /* "rate" */ 
	0x19,0xd, /* "yaw" */ 
	0xc0,0x97,0x6,0xc0, /* "inav" */ 
	0x80, /* "p" */ 
	0x20,0x9a,0xd,0x0, /* "pitch" */ 
	0xd0, /* "z" */ 
	0xf,0x9, /* "gps" */ 
	0x81,0x81,0xab,0x86,0x80, /* "launch" */ 
	0x41,0xf3, /* "pos" */ 
	0x4,0x9e,0xc6, /* "roll" */ 
	0x1,0xa1,0xc0, /* "max" */ 
	0x1a,0x97, /* "min" */ 
	0x2,0x54,0x40, /* "rth" */ 
	0x8, /* "d" */ 
	0x3,0x5,0x2c,0x98,0x4c,0x50, /* "failsafe" */ 
	0x24, /* "i" */ 
	0x17, /* "w" */ 
	0x6,0x32, /* "xy" */ 
	0x0,0xb8,0xec,0x28, /* "angle" */ 
	0x11,0xa0, /* "hz" */ 
	0x32,0x6, /* "lpf" */ 
	0x3,0x43,0x66,0x25,0xcb, /* "mavlink" */ 
	0x5,0x33,0x2, /* "type" */ 
	0x80,0x85,0x9,0x4,0x17,0x10, /* "deadband" */ 
	0x4,0x2b,0x3,0x90, /* "delay" */ 
	0x17,0x40, /* "ez" */ 
	0x3e,0x64,0xf0, /* "gyro" */ 
	0x34,0x27, /* "mag" */ 
	0x5,0x11,0x27,0xd2,0x8c,0x28, /* "throttle" */ 
	0x2,0x31, /* "acc" */ 
	0x80,0x28,0x94, /* "ahrs" */ 
	0xc0,0x1a,0xd1,0xe0, /* "auto" */ 
	0x68,0x5d,0x50,0xb0, /* "manual" */ 
	0xd,0x79,0xa, /* "mode" */ 
	0xa,0x22,0x40, /* "thr" */ 
	0x1b,0x12,0xd1, /* "climb" */ 
	0x0,0xb8,0x83, /* "expo" */ 
	0xc0,0xc2,0xd8,0xac, /* "level" */ 
	0x4,0x86, /* "rc" */ 
	0x0,0xb1,0x27,0x70, /* "align" */ 
	0x2,0xca,0x26,0x95,0x21, /* "altitude" */ 
	0x40,0x37,0xba,0x92,0x7b, /* "control" */ 
	0x0,0xc0,0xb8,0x80, /* "land" */ 
	0x6b,0xe8,0xf9, /* "motor" */ 
	0x2,0x89,0x69, /* "time" */ 
	0x41,0x60, /* "v" */ 
	0x58,0xac, /* "vel" */ 
	0x0,0x59,0x40, /* "alt" */ 
	0x8,0x32,0x78, /* "baro" */ 
	0x8,0x99,0xd0,0x2e,0x19, /* "distance" */ 
	0x41,0x32,0xca,0xcf, /* "servo" */ 
	0x4,0xe0,0x52,0x90, /* "speed" */ 
	0x15,0x99, /* "use" */ 
	0x41,0x78, /* "wp" */ 
	0x0,0x41,0xa5,0xb,0x2c, /* "battery" */ 
	0x80,0xc6, /* "ff" */ 
	0x1,0x92,0xca,0x16,0x40, /* "filter" */ 
	0x4d,0xb,0x26, /* "iterm" */ 
	0x81,0x81,0x71,0x12,0xe3, /* "landing" */ 
	0x81,0x89,0x6a,0x68, /* "limit" */ 
	0x8,0x24,0x80, /* "pid" */ 
	0x85,0xda, /* "pwm" */ 
	0xa,0x22,0x45,0x9a,0x1e,0xc2, /* "threshold" */ 
	0x2,0x90,0x8, /* "tpa" */ 
	0x30, /* "x" */ 
	0xc, /* "y" */ 
	0x83,0x64, /* "3d" */ 
	0x0,0xc3,0x0,0x8d,0x34,0xc8, /* "capacity" */ 
	0x6,0x40, /* "cd" */ 
	0xe,0x55,0x4c,0xca, /* "cruise" */ 
	0x2,0xd,0xa0, /* "dcm" */ 
	0x22,0x66,0x19,0x34, /* "disarm" */ 
	0x4,0x93,0xdc,0x51,0x85,0xc0, /* "dronecan" */ 
	0x26,0x5c, /* "dyn" */ 
	0x4,0x91,0x85, /* "idle" */ 
	0x3,0xcc,0x69,0x96,0x80, /* "offset" */ 
	0x94,0xe6,0x90, /* "rssi" */ 
	0x4e,0xe9,0xa0,0xd0, /* "switch" */ 
	0xa,0x15,0x85,0x69,0x69,0x2c, /* "telemetry" */ 
	0x82,0xa2,0x63,0xf0, /* "ublox" */ 
	0x0,0x8c,0x65,0x60, /* "accel" */ 
	0x2,0x31,0x9c,0x29,0x70, /* "accgain" */ 
	0x2,0x31,0xe8,0xb2,0x78, /* "acczero" */ 
	0x4,0x52,0xc0,0xb2, /* "beeper" */ 
	0x0,0x9e,0x19,0x10, /* "board" */ 
	0x3,0xb, /* "cal" */ 
	0x0,0x37,0xb6,0x0, /* "comp" */ 
	0x1d,0x65,0x22,0xba,0x80, /* "current" */ 
	0x2b,0x82,0x26,0x14,0x80, /* "enabled" */ 
	0x38,0x52,0xe0, /* "gain" */ 
	0x20,0x32,0x25,0xc3,0x22, /* "hardware" */ 
	0x81,0x4,0x38, /* "hdg" */ 
	0x10,0x50,0x91,0x2e,0x38, /* "heading" */ 
	0x10,0xf6,0x10, /* "hold" */ 
	0x9,0x20, /* "id" */ 
	0x12,0x77,0x3e,0x45, /* "ignore" */ 
	0x3,0x1f,0x70, /* "low" */ 
	0x34,0x27,0x38,0x52,0xe0, /* "maggain" */ 
	0x34,0x27,0xd1,0x64,0xf0, /* "magzero" */ 
	0x34,0xb4,0x2c, /* "meter" */ 
	0x80,0xd4,0xce,0x69,0x7b, /* "mission" */ 
	0x80,0xd4,0xe0,0xb2, /* "mixer" */ 
	0x3,0x5a,0x9c, /* "mmix" */ 
	0x1,0xb5,0x65,0x13,0x6,0x24,0xb2, /* "multiplier" */ 
	0x3,0xdc, /* "on" */ 
	0x8,0x26,0x83,0x47,0x28,0x89, /* "pitch2thr" */ 
	0x2,0x45,0x99,0x68, /* "reset" */ 
	0x9,0xb1,0xf7,0x23,0xee,0xe0, /* "slowdown" */ 
	0x4d,0xaf,0x7d,0x10,0x97,0x1c, /* "smoothing" */ 
	0x13,0xac,0x8c,0x11,0x94, /* "surface" */ 
	0x14,0x4b,0x4a,0xfa,0xd0, /* "timeout" */ 
	0x14,0x90,0x5d,0x34,0xd1,0x2f,0x70, /* "transition" */ 
	0x29,0x59,0x38, /* "turn" */ 
	0x1a,0x2c,0x9e, /* "zero" */ 
	0x0,0x89,0xf2,0xa0, /* "abort" */ 
	0x2,0x99,0x35,0xe4,0x28, /* "airmode" */ 
	0x2,0xc6,0x3e,0xe0, /* "allow" */ 
	0xc,0xe6,0x99,0xd0, /* "assist" */ 
	0x2,0xb,0x96, /* "bank" */ 
	0x1,0xa0,0xa3,0x58, /* "check" */ 
	0x6,0xf9,0x48,0xa3,0xa2,0x5e,0xe0, /* "correction" */ 
	0xe,0xb4,0x79,0x8c, /* "cutoff" */ 
	0x2,0x16,0x85,0x1d, /* "detect" */ 
	0x0,0x44,0xc8,0xa3,0xa2,0x5e,0xe0, /* "direction" */ 
	0x11,0x36,0x28, /* "dive" */ 
	0x9,0x34,0x3e,0x80, /* "dshot" */ 
	0x25,0xb,0x26, /* "dterm" */ 
	0x80,0xad,0x2c,0x8e, /* "emerg" */ 
	0x2,0xc2,0xc0, /* "epv" */ 
	0x32,0x65,0x3a, /* "first" */ 
	0x0,0xcc,0x7d, /* "flow" */ 
	0xc0,0x79,0x6,0xc9,0xa6, /* "gravity" */ 
	0x40,0x80,0xb0,0xc4,0xac,0x18,0x5c, /* "halfduplex" */ 
	0x1,0xf,0x69, /* "home" */ 
	0x40,0x97,0xd,0x89,0x70,0x68,0x97,0xb8, /* "inclination" */ 
	0x9,0x75,0x8b,0x2a,0x14,0x80, /* "inverted" */ 
	0x5a, /* "ki" */ 
	0x40,0xb8, /* "kp" */ 
	0x1,0x8f,0x4d,0xb,0x20, /* "loiter" */ 
	0x34,0x38,0xb,0x28, /* "maxalt" */ 
	0x6,0xa5,0xc1,0x65, /* "minalt" */ 
	0x0,0xd7,0x90,0xac, /* "model" */ 
	0x3,0x82,0xd2, /* "name" */ 
	0x81,0xcf,0x21, /* "node" */ 
	0x40,0xe7,0xd0,0x68, /* "notch" */ 
	0x4,0x1f,0x34,0xd1,0x2f,0x70, /* "position" */ 
	0x20,0xfb,0x96,0x40, /* "power" */ 
	0x84,0x9e,0x32,0x92,0xb2,0x28, /* "procedure" */ 
	0x21,0x27,0x99,0x2c,0x28, /* "profile" */ 
	0x21,0x27,0xd1,0xe3,0x7b, /* "protocol" */ 
	0x1,0x20,0x91,0x35,0x98, /* "radius" */ 
	0x24,0x56,0x7,0x0, /* "relax" */ 
	0x91,0x66, /* "res" */ 
	0x9,0x16,0x70,0x7b,0xa6,0x50, /* "response" */ 
	0x4b,0x0, /* "rx" */ 
	0x98,0x4c,0x54,0x3d,0xa5, /* "safehome" */ 
	0x4,0xc6,0x16,0x14, /* "scale" */ 
	0x14,0x2b,0x60, /* "temp" */ 
	0xa,0x3d,0x85,0x90,0x5c,0x32, /* "tolerance" */ 
	0x82,0x92,0x8,0xd6,0x20,0x8d,0x60, /* "trackback" */ 
	0xa6, /* "tz" */ 
	0x81,0x57,0x26,0x80, /* "unit" */ 
	0xac,0xca,0x30, /* "usec" */ 
	0x59,0xec,0xa0,0x4e,0x50, /* "voltage" */ 
	0x5a,0x70,0x20, /* "vspd" */ 
	0x2e,0x54,0x9d,0x14, /* "weight" */ 
	0x0,0x4e,0x79,0x16,0x73,0x4d,0x8a,0xe2,0xce,0x60, /* "aggressiveness" */ 
	0xa,0x65,0x38,0x14,0xa4, /* "airspeed" */ 
	0x0,0x59,0x44,0x3d,0x84, /* "althold" */ 
	0x0,0x59,0x70,0xe6,0x60, /* "always" */ 
	0xc,0x2, /* "apa" */ 
	0x0,0xc2,0xc,0x49,0x48, /* "applied" */ 
	0x0,0xd6,0x8f,0x68,0x68,0x52, /* "automated" */ 
	0x0,0x35,0xa3,0xda,0x1a,0x24,0x60, /* "automatic" */ 
	0xd,0x68,0xf8,0x25,0x8f,0xa0, /* "autopilot" */ 
	0x3,0x5a,0x3e,0x92,0x4b, /* "autotrim" */ 
	0x40,0x1c,0x26,0x60, /* "axis" */ 
	0x10,0x68, /* "bat" */ 
	0x1,0x6,0xa4, /* "baud" */ 
	0x0,0x8a,0x92,0x3e,0xa0, /* "beidou" */ 
	0x12,0x43,0x30, /* "bias" */ 
	0x9,0x34,0x90,0x68,0x50, /* "bitrate" */ 
	0xa,0x45,0xa,0xe0,0xf4,0xba,0x80, /* "breakpoint" */ 
	0x15,0x5b,0x0, /* "bump" */ 
	0xc,0x2c,0x48,0xa4,0x1a,0x25,0xee, /* "calibration" */ 
	0x0,0xca,0xc6, /* "cell" */ 
	0x0,0x65,0x75,0xb,0x20, /* "center" */ 
	0xd,0x1,0x70, /* "chan" */ 
	0x6,0x80,0xb9,0xc5,0x60, /* "channel" */ 
	0x6,0xd9,0xcc, /* "cmss" */ 
	0x3,0x7b,0x5a,0x17,0x10, /* "command" */ 
	0x3,0x7b,0x60,0x57,0x4c,0x34,0x4b,0xdc, /* "compensation" */ 
	0x1,0xbd,0xc6,0x49, /* "config" */ 
	0xc0,0x37,0xba,0x74,0xb,0xa8, /* "constant" */ 
	0x1,0xc9,0x34,0x48,0xc2,0xc0, /* "critical" */ 
	0xe,0xb2,0xb1, /* "curve" */ 
	0x40,0x40,0xb6,0x9,0x71, /* "damping" */ 
	0xc0,0x42,0x84,0x80, /* "dead" */ 
	0x21,0x45,0x53, /* "debug" */ 
	0x80,0x85,0x19,0x58,0x59,0x6,0x89,0x7b, /* "deceleration" */ 
	0x80,0x42,0x8d,0x80, /* "decl" */ 
	0x21,0x46,0xc4,0xb8,0x34,0x4b,0xdc, /* "declination" */ 
	0x2,0x14,0xc1,0xab,0x28, /* "default" */ 
	0x2,0x14,0xc1,0xab,0x29,0x30, /* "defaults" */ 
	0x10,0xa7,0x91,0x4b,0x30, /* "degrees" */ 
	0x10,0xb4,0x28,0xe8,0x97,0xb8, /* "detection" */ 
	0x4,0x4c,0xe0,0xc0,0xe7,0xa6,0x7c,0x86,0x5e,0xce,0xfd,0x13,0x12,0xe5, /* "display_force_sw_blink" */ 
	0x80,0x8f,0xbb, /* "down" */ 
	0x80,0x49,0xd0, /* "dst" */ 
	0x5,0x71, /* "end" */ 
	0x0,0x57,0x16,0x47,0xc8, /* "energy" */ 
	0xa,0xe3,0x3e,0x43,0x28, /* "enforce" */ 
	0xb,0x4, /* "eph" */ 
	0x0,0xb8,0xa0, /* "ext" */ 
	0xb,0x8a,0x48,0x3e, /* "extra1" */ 
	0x1,0x71,0x49,0x7,0x80, /* "extra2" */ 
	0x2e,0x29,0x20,0xec, /* "extra3" */ 
	0x6,0x8,0xe8,0xf9, /* "factor" */ 
	0x0,0xc9,0xc1,0x49,0xdb,0xa5,0xc7,0xe8,0x6b,0x47,0xf4,0x32,0x68, /* "fixed_wing_auto_arm" */ 
	0xc,0xc0,0xc0,0xb2,0x7b, /* "flaperon" */ 
	0x80,0x66,0x6,0x13, /* "flaps" */ 
	0x1,0xa1,0x60, /* "fpv" */ 
	0x1a,0x53,0x5e, /* "frsky" */ 
	0x40,0x69,0x4d,0x79,0xed,0x66,0x5e,0xb0,0xa7,0x8,0xf3,0xd3,0xc2,0x7d,0x6b,0xc8,0x5e,0xcc,0xae,0x9b,0xe5,0xd4,0x92,0x60, /* "frsky_use_legacy_gps_mode_sensor_ids" */ 
	0x34, /* "fs" */ 
	0xc0,0x6a,0x95,0x80, /* "fuel" */ 
	0x35,0xfa,0x9a,0x16,0x4d,0xeb,0x1e,0x35,0xf4,0xae,0x38,0x4e,0x5e,0xd1,0x12,0x2c,0xd0,0xf6,0x10, /* "fw_iterm_lock_engage_threshold" */ 
	0x6,0xbf,0x53,0x42,0xc9,0xbd,0x63,0xc6,0xbe,0xd1,0x2d,0x2f,0x5a,0x1c,0x75,0xb3, /* "fw_iterm_lock_time_max_ms" */ 
	0x1,0xaf,0xdc,0x86,0xfd,0x4d,0xb,0x26,0xf4,0xd2,0x29,0x74,0x5e,0x88,0x2e,0x5f,0x42,0xe3,0xb0,0xa0, /* "fw_yaw_iterm_freeze_bank_angle" */ 
	0x38,0x58,0x96,0x15,0xe0, /* "galileo" */ 
	0x3b,0x1e,0xe0,0xce,0x60, /* "glonass" */ 
	0x3c,0x27,0xd0,0xd6,0x8f,0xe8,0x83,0x52,0x75,0xa1,0xc7,0x67,0x58,0x41,0xf2,0xa1,0x48, /* "gps_auto_baud_max_supported" */ 
	0x3,0xc9,0xf5,0x71, /* "ground" */ 
	0x0,0x7c,0xc9,0xfd,0xb,0xa8,0x9e,0x85,0x89,0xc,0xd2,0xe3,0xf5,0x90,0x37,0x51,0xa0, /* "gyro_anti_aliasing_lpf_hz" */ 
	0x1f,0x32,0x7f,0x59,0x56,0x57,0xb3,0xb,0x60,0xc2,0xf4,0x6f,0xab,0xa8, /* "gyro_lulu_sample_count" */ 
	0x4,0x6,0x60, /* "has" */ 
	0x42,0x4e,0x80, /* "high" */ 
	0x21,0xf4,0xa7,0x42,0xc0,0xc9,0xbd,0x9b,0xea,0xe2,0x75,0x2e,0xa1,0x65,0x60,0xb0, /* "hott_alarm_sound_interval" */ 
	0x8,0x7d,0x8b,0x20, /* "hover" */ 
	0x24,0x55,0x98, /* "ibus" */ 
	0x12,0xe2,0xca,0x89,0x8, /* "inertia" */ 
	0x12,0xe4,0xd0, /* "init" */ 
	0x9,0x74, /* "ins" */ 
	0xc0,0x97,0x50,0xb2,0xb0,0x58, /* "interval" */ 
	0x5,0x8a,0x13, /* "kbps" */ 
	0x3,0xa,0x40, /* "led" */ 
	0x31,0x2e,0x5a,0x5c,0x70, /* "linking" */ 
	0x31,0xe3,0x58, /* "lock" */ 
	0x18,0xf7,0xc2,0x89,0x69, /* "looptime" */ 
	0x40,0xca,0x34, /* "ltm" */ 
	0xc,0xab,0x2a, /* "lulu" */ 
	0x6,0x85,0x2e, /* "main" */ 
	0x3,0x43,0x23,0xa5,0xc0, /* "margin" */ 
	0x69,0x68,0x87,0x90, /* "method" */ 
	0xd,0x49, /* "mid" */ 
	0x0,0xd4,0xe0, /* "mix" */ 
	0xd,0x79,0xb,0xd9,0x5,0xc7,0x2f,0x58,0xf3,0xa4,0x7d,0x7c,0xb,0x20,0xd1,0xf2, /* "mode_range_logic_operator" */ 
	0x3,0x5f,0x47,0xca,0x74,0x7c, /* "motorstop" */ 
	0x0,0xe0,0xdb,0xa5,0xc5,0x24,0x1e,0x86,0x4d,0x4b,0x8f,0xd9,0x84,0xc5,0xa6, /* "nav_extra_arming_safety" */ 
	0x40,0xe0,0xdb,0xa6,0xbf,0x42,0xc6,0x3e,0xfd,0x68,0x5d,0x50,0xb3,0xb4,0x44,0xba,0x97,0xe,0x45,0xc,0xca, /* "nav_fw_allow_manual_thr_increase" */ 
	0x7,0x6,0xdd,0x35,0xfa,0xc0,0xd5,0xc3,0x47,0x6e,0x93,0x9d,0x85,0xed,0x1f,0xdb,0x85,0x65,0xea,0x48,0xc2, /* "nav_fw_launch_wiggle_to_wake_idle" */ 
	0x81,0xc1,0xb7,0x4d,0x7e,0xc1,0xf3,0xea,0x8,0x7e,0xc1,0x24,0x9d,0x5b,0xd6,0x25,0xa9,0xa0, /* "nav_fw_pos_hdg_pidsum_limit" */ 
	0x1c,0x1b,0x74,0xd7,0xec,0xde,0x19,0x25,0xc7,0xeb,0x5f,0x47,0xcb,0xb3,0xa3,0xe0, /* "nav_fw_soaring_motor_stop" */ 
	0x7,0x6,0xdd,0x35,0xfb,0x78,0x76,0x92,0x8,0xd6,0x97,0x1f,0xa1,0x18,0xeb,0x20,0x8f,0x20, /* "nav_fw_wp_tracking_accuracy" */ 
	0x70,0x6d,0xd3,0x5f,0xb7,0x87,0x69,0x20,0x8d,0x69,0x71,0xfa,0xd0,0xe3,0xa1,0x71,0xd8,0x50, /* "nav_fw_wp_tracking_max_angle" */ 
	0x38,0x36,0xeb,0x43,0x8e,0xd0,0xb2,0x90,0x52,0xee,0x99,0xec,0x63,0xef,0xd0,0xb2,0x80, /* "nav_max_terrain_follow_alt" */ 
	0x70,0x6d,0xd6,0x8f,0xa9,0x75,0x8b,0x2a,0x14,0x9d,0x1c,0x83,0x34,0x74,0x85,0xa1,0x47,0x44,0xbd,0xc0, /* "nav_mc_inverted_crash_detection" */ 
	0x70,0x6d,0xd6,0x8f,0xb6,0x2b,0x3b,0x8c,0xf4,0x94,0x2c,0x9b,0xd0,0xd2,0x85,0x75,0x43,0x44,0xbd,0xc0, /* "nav_mc_vel_xy_dterm_attenuation" */ 
	0x70,0x6d,0xd6,0x8f,0xb6,0x2b,0x3b,0x8c,0xf4,0x94,0x2c,0x9b,0xd0,0xd2,0x85,0x75,0x43,0x44,0xbd,0xdd,0x2b,0x88, /* "nav_mc_vel_xy_dterm_attenuation_end" */ 
	0x7,0x6,0xdd,0x68,0xfb,0x62,0xb3,0xb8,0xcf,0x49,0x42,0xc9,0xbd,0xd,0x28,0x57,0x54,0x34,0x4b,0xdd,0xd9,0xd0,0x32,0xa0, /* "nav_mc_vel_xy_dterm_attenuation_start" */ 
	0x1c,0x1b,0x75,0xa3,0xed,0x8a,0xce,0xe3,0x3d,0x25,0xb,0x26,0xf5,0x90,0x37,0x51,0xa0, /* "nav_mc_vel_xy_dterm_lpf_hz" */ 
	0x38,0x36,0xec,0xa8,0x8e,0x8d,0x89,0x68,0xba,0x64,0xca,0x74,0xec,0xe8,0x13,0x97,0xa1,0x65,0x13,0x4a,0x90,0xa0, /* "nav_rth_climb_first_stage_altitude" */ 
	0x70,0x6d,0xd9,0x51,0x1d,0x1b,0x12,0xd1,0x74,0xc9,0x94,0xe9,0xd9,0xd0,0x27,0x2f,0x5a,0xf2,0x14, /* "nav_rth_climb_first_stage_mode" */ 
	0xe,0xd,0xbb,0x2a,0x23,0xac,0x4b,0x8a,0x19,0x74,0x85,0x98,0xca,0xea,0x76,0x74,0xc,0xa9,0xd2,0x26,0x74,0xb,0x86,0x50, /* "nav_rth_linear_descent_start_distance" */ 
	0x38,0x36,0xec,0xa8,0x8e,0xd6,0x65,0xeb,0x12,0xe2,0x86,0x5d,0x21,0x66,0x32,0xba,0x80, /* "nav_rth_use_linear_descent" */ 
	0x70,0x6d,0xdb,0xc3,0xac,0x78,0x49,0xd7,0xbb,0xa2,0x7b,0xe8, /* "nav_wp_load_on_boot" */ 
	0x7,0x16,0xb4,0x90,0x58, /* "neutral" */ 
	0x7,0x98,0xc0, /* "off" */ 
	0x7c,0x92,0x57,0x50,0x34,0x4b,0xdc, /* "orientation" */ 
	0x7,0xd8,0xb2,0x92,0x48,0x50, /* "override" */ 
	0x3e,0xc5,0x94,0x92,0x42,0xcc, /* "overrides" */ 
	0x10,0x2c,0x86,0x57,0x50, /* "percent" */ 
	0x10,0x4b,0x1f,0x40, /* "pilot" */ 
	0x41,0x2e, /* "pin" */ 
	0x4,0x13,0x40, /* "pit" */ 
	0x41,0x81,0x73,0x8b,0x20, /* "planner" */ 
	0x41,0x81,0xa1,0x9f,0x26, /* "platform" */ 
	0x82,0xf,0x61,0x66, /* "poles" */ 
	0x8,0x3e,0xe0, /* "pow" */ 
	0x84,0x8a,0x19,0x34, /* "prearm" */ 
	0x10,0x91,0x6c,0x92,0xdc, /* "preview" */ 
	0x10,0x93,0xec,0x92,0x16,0x40, /* "provider" */ 
	0x85,0x59,0x32, /* "pulse" */ 
	0x82,0x41,0x22,0x5e, /* "radio" */ 
	0x9,0x6,0x89,0x78, /* "ratio" */ 
	0x24,0x51,0x95,0x36,0x2c, /* "receiver" */ 
	0x81,0x22,0x8d,0x6f,0x72,0x5c,0x70, /* "reckoning" */ 
	0x48,0xa3,0x7d,0x8b,0x2c, /* "recovery" */ 
	0x82,0x45,0x31,0x64,0x57,0xc,0xa0, /* "reference" */ 
	0x91,0x60,0xf9,0x50, /* "report" */ 
	0x12,0x2c,0xe8,0x19,0x50, /* "restart" */ 
	0x12,0x63, /* "rll" */ 
	0x1,0x27,0xd0,0x34,0x4b,0xdc, /* "rotation" */ 
	0x9,0x84,0xc5, /* "safe" */ 
	0x4,0xc3,0x49, /* "sats" */ 
	0x82,0x62,0xc, /* "sbas" */ 
	0xc1,0x31,0x56,0x60, /* "sbus" */ 
	0x99,0x5d,0x34,0xd1,0x36,0x4d,0x32, /* "sensitivity" */ 
	0x9,0x95,0xd3,0x7c, /* "sensor" */ 
	0x81,0x32,0xc9,0x21,0x64,0xb0, /* "serialrx" */ 
	0x9,0xb1,0xf0,0x28, /* "slope" */ 
	0x26,0xd0,0xb1,0x80, /* "small" */ 
	0x9b,0x43,0x2a,0x41,0xf2,0xa0, /* "smartport" */ 
	0x26,0xd7,0xbe,0x88,0x71,0x67,0x30, /* "smoothness" */ 
	0x4d,0xc1,0x84,0x12,0xe2,0xce,0x60, /* "snappiness" */ 
	0x9b,0xc3,0x24,0xb8,0xe0, /* "soaring" */ 
	0x9b,0xeb,0x21,0x94, /* "source" */ 
	0x13,0x82,0x5d,0x58, /* "spinup" */ 
	0x2,0x72,0x18, /* "src" */ 
	0x27,0x40,0x89,0x2c,0x4d,0x32, /* "stability" */ 
	0x9,0xd0,0x34,0xac, /* "status" */ 
	0xc1,0x3a,0x24,0x6b, /* "stick" */ 
	0x4,0xe8,0xf8, /* "stop" */ 
	0x2,0x74,0x90, /* "str" */ 
	0x27,0x97,0xc, /* "sync" */ 
	0x13,0xcc,0xd2,0x40, /* "sysid" */ 
	0x50,0x29,0x60, /* "tail" */ 
	0x28,0x14,0xb2,0x69,0xa5,0xb,0x20, /* "tailsitter" */ 
	0x51,0x12,0x7d, /* "throw" */ 
	0xc1,0x44,0xb2,0x80, /* "tilt" */ 
	0xa2,0x5a,0x59, /* "timer" */ 
	0x2,0x8f,0x71, /* "tone" */ 
	0x41,0x49,0x5,0xd3, /* "trans" */ 
	0x5,0x24,0x90, /* "tri" */ 
	0x52,0x49,0x68, /* "trim" */ 
	0x29,0x81,0x54,0xc6,0x2c, /* "txbuffer" */ 
	0x81,0x57,0x6,0x4d,0x29, /* "unarmed" */ 
	0x1,0x58,0x10,0x34,0x28, /* "update" */ 
	0x2b,0x30,0x9c,0xa0, /* "usage" */ 
	0xac,0xcb,0x20, /* "user" */ 
	0x58,0xac,0x78,0xd3,0x4c, /* "velocity" */ 
	0x82,0xc5,0x94,0xd2,0xf7, /* "version" */ 
	0x2,0xe1,0x93,0x92,0xe3, /* "warning" */ 
	0x82,0xe9,0x71,0x6,0xf6,0xc0, /* "windcomp" */ 
	0x17,0x4b,0x89,0x58, /* "windup" */ 
	0x0,0x00
};
static const char wordSymbols[] = {'3','2','_','1',};
const char * const table_acc_hardware[] = {
	"NONE",
	"AUTO",
	"MPU6000",
	"MPU6500",
	"MPU9250",
	"BMI160",
	"ICM20689",
	"BMI088",
	"ICM42605",
	"BMI270",
	"LSM6DXX",
	"FAKE",
};
const char * const table_airmodeHandlingType[] = {
	"STICK_CENTER",
	"THROTTLE_THRESHOLD",
	"STICK_CENTER_ONCE",
};
const char * const table_alignment[] = {
	"DEFAULT",
	"CW0",
	"CW90",
	"CW180",
	"CW270",
	"CW0FLIP",
	"CW90FLIP",
	"CW180FLIP",
	"CW270FLIP",
};
const char * const table_aux_operator[] = {
	"OR",
	"AND",
};
const char * const table_baro_hardware[] = {
	"NONE",
	"AUTO",
	"BMP085",
	"MS5611",
	"BMP280",
	"MS5607",
	"LPS25H",
	"SPL06",
	"BMP388",
	"DPS310",
	"B2SMPB",
	"MSP",
	"FAKE",
};
const char * const table_bat_capacity_unit[] = {
	"MAH",
	"MWH",
};
const char * const table_bat_voltage_source[] = {
	"RAW",
	"SAG_COMP",
};
const char * const table_current_sensor[] = {
	"NONE",
	"ADC",
	"VIRTUAL",
	"FAKE",
	"ESC",
	"SMARTPORT",
	"CAN",
};
const char * const table_debug_modes[] = {
	"NONE",
	"AGL",
	"FLOW_RAW",
	"FLOW",
	"ALWAYS",
	"SAG_COMP_VOLTAGE",
	"VIBE",
	"CRUISE",
	"REM_FLIGHT_TIME",
	"SMARTAUDIO",
	"ACC",
	"NAV_YAW",
	"PCF8574",
	"DYN_GYRO_LPF",
	"AUTOLEVEL",
	"ALTITUDE",
	"AUTOTRIM",
	"AUTOTUNE",
	"RATE_DYNAMICS",
	"LANDING",
	"POS_EST",
	"ADAPTIVE_FILTER",
	"HEADTRACKER",
	"GPS",
	"LULU",
	"SBUS2",
};
const char * const table_default_altitude_source[] = {
	"GPS",
	"BARO",
	"GPS_ONLY",
	"BARO_ONLY",
};
const char * const table_direction[] = {
	"RIGHT",
	"LEFT",
	"YAW",
};
const char * const table_dronecan_bitrate_table[] = {
	"125",
	"250",
	"500",
	"1000",
};
const char * const table_failsafe_procedure[] = {
	"LAND",
	"DROP",
	"RTH",
	"NONE",
};
const char * const table_filter_type[] = {
	"PT1",
	"BIQUAD",
};
const char * const table_filter_type_full[] = {
	"PT1",
	"BIQUAD",
	"PT2",
	"PT3",
	"LULU",
};
const char * const table_gps_auto_baud_max[] = {
	"115200",
	"57600",
	"38400",
	"19200",
	"9600",
	"230400",
	"460800",
	"921600",
};
const char * const table_gps_dyn_model[] = {
	"PEDESTRIAN",
	"AUTOMOTIVE",
	"AIR_1G",
	"AIR_2G",
	"AIR_4G",
	"SEA",
	"MOWER",
};
const char * const table_gps_provider[] = {
	"UBLOX",
	"MSP",
	"FAKE",
	"DRONECAN",
};
const char * const table_gps_sbas_mode[] = {
	"AUTO",
	"EGNOS",
	"WAAS",
	"MSAS",
	"GAGAN",
	"SPAN",
	"NONE",
};
const char * const table_gyro_filter_mode[] = {
	"OFF",
	"STATIC",
	"DYNAMIC",
	"ADAPTIVE",
};
const char * const table_imu_inertia_comp_method[] = {
	"VELNED",
	"TURNRATE",
	"ADAPTIVE",
};
const char * const table_iterm_relax[] = {
	"OFF",
	"RP",
	"RPY",
};
const char * const table_led_pin_pwm_mode[] = {
	"SHARED_LOW",
	"SHARED_HIGH",
	"LOW",
	"HIGH",
};
const char * const table_ltm_rates[] = {
	"NORMAL",
	"MEDIUM",
	"SLOW",
};
const char * const table_mag_hardware[] = {
	"NONE",
	"AUTO",
	"HMC5883",
	"AK8975",
	"MAG3110",
	"AK8963",
	"IST8310",
	"QMC5883",
	"QMC5883P",
	"MPU9250",
	"IST8308",
	"LIS3MDL",
	"MSP",
	"RM3100",
	"VCM5883",
	"MLX90393",
	"FAKE",
};
const char * const table_mavlink_autopilot_type[] = {
	"GENERIC",
	"ARDUPILOT",
};
const char * const table_mavlink_radio_type[] = {
	"GENERIC",
	"ELRS",
	"SIK",
};
const char * const table_motor_pwm_protocol[] = {
	"STANDARD",
	"ONESHOT125",
	"MULTISHOT",
	"BRUSHED",
	"DSHOT150",
	"DSHOT300",
	"DSHOT600",
};
const char * const table_nav_extra_arming_safety[] = {
	"ON",
	"ALLOW_BYPASS",
};
const char * const table_nav_fw_wp_turn_smoothing[] = {
	"OFF",
	"ON",
	"ON-CUT",
};
const char * const table_nav_mc_althold_throttle[] = {
	"STICK",
	"MID_STICK",
	"HOVER",
};
const char * const table_nav_overrides_motor_stop[] = {
	"OFF_ALWAYS",
	"OFF",
	"AUTO_ONLY",
	"ALL_NAV",
};
const char * const table_nav_rth_allow_landing[] = {
	"NEVER",
	"ALWAYS",
	"FS_ONLY",
};
const char * const table_nav_rth_alt_mode[] = {
	"CURRENT",
	"EXTRA",
	"FIXED",
	"MAX",
	"AT_LEAST",
};
const char * const table_nav_rth_climb_first[] = {
	"OFF",
	"ON",
	"ON_FW_SPIRAL",
};
const char * const table_nav_rth_climb_first_stage_modes[] = {
	"AT_LEAST",
	"EXTRA",
};
const char * const table_nav_user_control_mode[] = {
	"ATTI",
	"CRUISE",
};
const char * const table_nav_wp_mission_restart[] = {
	"START",
	"RESUME",
	"SWITCH",
};
const char * const table_off_on[] = {
	"OFF",
	"ON",
};
const char * const table_pidTypeTable[] = {
	"NONE",
	"PID",
	"PIFF",
	"AUTO",
};
const char * const table_platform_type[] = {
	"MULTIROTOR",
	"AIRPLANE",
	"HELICOPTER",
	"TRICOPTER",
	"ROVER",
	"BOAT",
};
const char * const table_receiver_type[] = {
	"NONE",
	"SERIAL",
	"MSP",
	"SIM (SITL)",
};
const char * const table_reset_type[] = {
	"NEVER",
	"FIRST_ARM",
	"EACH_ARM",
};
const char * const table_rssi_source[] = {
	"NONE",
	"AUTO",
	"ADC",
	"CHANNEL",
	"PROTOCOL",
	"MSP",
};
const char * const table_rth_trackback_mode[] = {
	"OFF",
	"ON",
	"FS",
};
const char * const table_safehome_usage_mode[] = {
	"OFF",
	"RTH",
	"RTH_FS",
};
const char * const table_servo_protocol[] = {
	"PWM",
	"SBUS",
	"SBUS_PWM",
};
const char * const table_smartport_fuel_unit[] = {
	"PERCENT",
	"MAH",
	"MWH",
};
const char * const table_tristate[] = {
	"AUTO",
	"ON",
	"OFF",
};
const char * const table_tz_automatic_dst[] = {
	"OFF",
	"EU",
	"USA",
};
static const lookupTableEntry_t settingLookupTables[] = {
	{ table_acc_hardware, sizeof(table_acc_hardware) / sizeof(char*) },
	{ table_airmodeHandlingType, sizeof(table_airmodeHandlingType) / sizeof(char*) },
	{ table_alignment, sizeof(table_alignment) / sizeof(char*) },
	{ table_aux_operator, sizeof(table_aux_operator) / sizeof(char*) },
	{ table_baro_hardware, sizeof(table_baro_hardware) / sizeof(char*) },
	{ table_bat_capacity_unit, sizeof(table_bat_capacity_unit) / sizeof(char*) },
	{ table_bat_voltage_source, sizeof(table_bat_voltage_source) / sizeof(char*) },
	{ table_current_sensor, sizeof(table_current_sensor) / sizeof(char*) },
	{ table_debug_modes, sizeof(table_debug_modes) / sizeof(char*) },
	{ table_default_altitude_source, sizeof(table_default_altitude_source) / sizeof(char*) },
	{ table_direction, sizeof(table_direction) / sizeof(char*) },
	{ table_dronecan_bitrate_table, sizeof(table_dronecan_bitrate_table) / sizeof(char*) },
	{ table_failsafe_procedure, sizeof(table_failsafe_procedure) / sizeof(char*) },
	{ table_filter_type, sizeof(table_filter_type) / sizeof(char*) },
	{ table_filter_type_full, sizeof(table_filter_type_full) / sizeof(char*) },
	{ table_gps_auto_baud_max, sizeof(table_gps_auto_baud_max) / sizeof(char*) },
	{ table_gps_dyn_model, sizeof(table_gps_dyn_model) / sizeof(char*) },
	{ table_gps_provider, sizeof(table_gps_provider) / sizeof(char*) },
	{ table_gps_sbas_mode, sizeof(table_gps_sbas_mode) / sizeof(char*) },
	{ table_gyro_filter_mode, sizeof(table_gyro_filter_mode) / sizeof(char*) },
	{ table_imu_inertia_comp_method, sizeof(table_imu_inertia_comp_method) / sizeof(char*) },
	{ table_iterm_relax, sizeof(table_iterm_relax) / sizeof(char*) },
	{ table_led_pin_pwm_mode, sizeof(table_led_pin_pwm_mode) / sizeof(char*) },
	{ table_ltm_rates, sizeof(table_ltm_rates) / sizeof(char*) },
	{ table_mag_hardware, sizeof(table_mag_hardware) / sizeof(char*) },
	{ table_mavlink_autopilot_type, sizeof(table_mavlink_autopilot_type) / sizeof(char*) },
	{ table_mavlink_radio_type, sizeof(table_mavlink_radio_type) / sizeof(char*) },
	{ table_motor_pwm_protocol, sizeof(table_motor_pwm_protocol) / sizeof(char*) },
	{ table_nav_extra_arming_safety, sizeof(table_nav_extra_arming_safety) / sizeof(char*) },
	{ table_nav_fw_wp_turn_smoothing, sizeof(table_nav_fw_wp_turn_smoothing) / sizeof(char*) },
	{ table_nav_mc_althold_throttle, sizeof(table_nav_mc_althold_throttle) / sizeof(char*) },
	{ table_nav_overrides_motor_stop, sizeof(table_nav_overrides_motor_stop) / sizeof(char*) },
	{ table_nav_rth_allow_landing, sizeof(table_nav_rth_allow_landing) / sizeof(char*) },
	{ table_nav_rth_alt_mode, sizeof(table_nav_rth_alt_mode) / sizeof(char*) },
	{ table_nav_rth_climb_first, sizeof(table_nav_rth_climb_first) / sizeof(char*) },
	{ table_nav_rth_climb_first_stage_modes, sizeof(table_nav_rth_climb_first_stage_modes) / sizeof(char*) },
	{ table_nav_user_control_mode, sizeof(table_nav_user_control_mode) / sizeof(char*) },
	{ table_nav_wp_mission_restart, sizeof(table_nav_wp_mission_restart) / sizeof(char*) },
	{ table_off_on, sizeof(table_off_on) / sizeof(char*) },
	{ table_pidTypeTable, sizeof(table_pidTypeTable) / sizeof(char*) },
	{ table_platform_type, sizeof(table_platform_type) / sizeof(char*) },
	{ table_receiver_type, sizeof(table_receiver_type) / sizeof(char*) },
	{ table_reset_type, sizeof(table_reset_type) / sizeof(char*) },
	{ table_rssi_source, sizeof(table_rssi_source) / sizeof(char*) },
	{ table_rth_trackback_mode, sizeof(table_rth_trackback_mode) / sizeof(char*) },
	{ table_safehome_usage_mode, sizeof(table_safehome_usage_mode) / sizeof(char*) },
	{ table_servo_protocol, sizeof(table_servo_protocol) / sizeof(char*) },
	{ table_smartport_fuel_unit, sizeof(table_smartport_fuel_unit) / sizeof(char*) },
	{ table_tristate, sizeof(table_tristate) / sizeof(char*) },
	{ table_tz_automatic_dst, sizeof(table_tz_automatic_dst) / sizeof(char*) },
};
static const uint32_t settingMinMaxTable[] = {
	0,
	255,
	100,
	1000,
	2000,
	10,
	200,
	1,
	32767,
	-32768,
	5,
	50,
	2,
	500,
	5000,
	10000,
	65000,
	-1800,
	15,
	3600,
	65535,
	20,
	180,
	250,
	80,
	60000,
	4294967295,
	-5000,
	4,
	30,
	90,
	120,
	300,
	900,
	8192,
	-800,
	-50,
	-1,
	9,
	16,
	25,
	40,
	45,
	51,
	127,
	400,
	450,
	750,
	800,
	2250,
	9999,
	500000,
	-18000,
	-10000,
	-1000,
	-720,
	-20,
	-10,
	3,
	6,
	32,
	34,
	60,
	99,
	175,
	498,
	600,
	840,
	1350,
	1500,
	1800,
	2500,
	4000,
	6000,
	9000,
	18000,
	20000,
	30000,
	32000,
};
typedef uint8_t setting_min_max_idx_t;
#define SETTING_INDEXES_GET_MIN(val) (val->config.minmax.indexes[0])
#define SETTING_INDEXES_GET_MAX(val) (val->config.minmax.indexes[1])
static const setting_t settingsTable[] = {
	// PG_GYRO_CONFIG
	{ {252, 1, 0, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 74}, (setting_offset_t)offsetof(gyroConfig_t, looptime) },
	{ {237, 1, 0, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 3}, (setting_offset_t)offsetof(gyroConfig_t, gyro_anti_aliasing_lpf_hz) },
	{ {30, 254, 1, 92, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(gyroConfig_t, gyroLuluEnabled) },
	{ {238, 1, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {7, 18}, (setting_offset_t)offsetof(gyroConfig_t, gyroLuluSampleCount) },
	{ {30, 255, 1, 24, 23, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 13}, (setting_offset_t)offsetof(gyroConfig_t, gyro_main_lpf_hz) },
	{ {30, 60, 37, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_GYRO_FILTER_MODE }, (setting_offset_t)offsetof(gyroConfig_t, gyroFilterMode) },
	{ {30, 77, 24, 15, 23, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {41, 45}, (setting_offset_t)offsetof(gyroConfig_t, gyroDynamicLpfMinHz) },
	{ {30, 77, 24, 14, 23, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {41, 3}, (setting_offset_t)offsetof(gyroConfig_t, gyroDynamicLpfMaxHz) },
	{ {30, 77, 24, 199, 1, 40}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {7, 5}, (setting_offset_t)offsetof(gyroConfig_t, gyroDynamicLpfCurveExpo) },
	{ {245, 1, 30, 89, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(gyroConfig_t, init_gyro_cal_enabled) },
	{ {30, 117, 68, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {9, 8}, (setting_offset_t)offsetof(gyroConfig_t, gyro_zero_cal[X]) },
	{ {30, 117, 69, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {9, 8}, (setting_offset_t)offsetof(gyroConfig_t, gyro_zero_cal[Y]) },
	{ {30, 117, 9, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {9, 8}, (setting_offset_t)offsetof(gyroConfig_t, gyro_zero_cal[Z]) },
	{ {246, 1, 135, 1, 193, 1}, VAR_FLOAT | MASTER_VALUE, .config.minmax.indexes = {0, 4}, (setting_offset_t)offsetof(gyroConfig_t, gravity_cmss_cal) },
	// PG_ACCELEROMETER_CONFIG
	{ {33, 148, 1, 23, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(accelerometerConfig_t, acc_notch_hz) },
	{ {33, 148, 1, 125, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {7, 1}, (setting_offset_t)offsetof(accelerometerConfig_t, acc_notch_cutoff) },
	{ {33, 94, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_ACC_HARDWARE }, (setting_offset_t)offsetof(accelerometerConfig_t, acc_hardware) },
	{ {33, 24, 23, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 6}, (setting_offset_t)offsetof(accelerometerConfig_t, acc_lpf_hz) },
	{ {33, 24, 26, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_FILTER_TYPE }, (setting_offset_t)offsetof(accelerometerConfig_t, acc_soft_lpf_type) },
	{ {33, 161, 1, 124, 0, 0}, VAR_FLOAT | MASTER_VALUE, .config.minmax.indexes = {36, 43}, (setting_offset_t)offsetof(accelerometerConfig_t, acc_temp_correction) },
	{ {86, 68, 0, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {9, 8}, (setting_offset_t)offsetof(accelerometerConfig_t, accZero.raw[X]) },
	{ {86, 69, 0, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {9, 8}, (setting_offset_t)offsetof(accelerometerConfig_t, accZero.raw[Y]) },
	{ {86, 9, 0, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {9, 8}, (setting_offset_t)offsetof(accelerometerConfig_t, accZero.raw[Z]) },
	{ {85, 68, 0, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {7, 34}, (setting_offset_t)offsetof(accelerometerConfig_t, accGain.raw[X]) },
	{ {85, 69, 0, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {7, 34}, (setting_offset_t)offsetof(accelerometerConfig_t, accGain.raw[Y]) },
	{ {85, 9, 0, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {7, 34}, (setting_offset_t)offsetof(accelerometerConfig_t, accGain.raw[Z]) },
	// PG_COMPASS_CONFIG
	{ {43, 31, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_ALIGNMENT }, (setting_offset_t)offsetof(compassConfig_t, mag_align) },
	{ {31, 94, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_MAG_HARDWARE }, (setting_offset_t)offsetof(compassConfig_t, mag_hardware) },
	{ {31, 205, 1, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {52, 75}, (setting_offset_t)offsetof(compassConfig_t, mag_declination) },
	{ {102, 68, 0, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {9, 8}, (setting_offset_t)offsetof(compassConfig_t, magZero.raw[X]) },
	{ {102, 69, 0, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {9, 8}, (setting_offset_t)offsetof(compassConfig_t, magZero.raw[Y]) },
	{ {102, 9, 0, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {9, 8}, (setting_offset_t)offsetof(compassConfig_t, magZero.raw[Z]) },
	{ {101, 68, 0, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {9, 8}, (setting_offset_t)offsetof(compassConfig_t, magGain[X]) },
	{ {101, 69, 0, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {9, 8}, (setting_offset_t)offsetof(compassConfig_t, magGain[Y]) },
	{ {101, 9, 0, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {9, 8}, (setting_offset_t)offsetof(compassConfig_t, magGain[Z]) },
	{ {31, 188, 1, 48, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {21, 31}, (setting_offset_t)offsetof(compassConfig_t, magCalibrationTimeLimit) },
	{ {43, 31, 13, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {17, 19}, (setting_offset_t)offsetof(compassConfig_t, rollDeciDegrees) },
	{ {43, 31, 8, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {17, 19}, (setting_offset_t)offsetof(compassConfig_t, pitchDeciDegrees) },
	{ {43, 31, 5, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {17, 19}, (setting_offset_t)offsetof(compassConfig_t, yawDeciDegrees) },
	// PG_BAROMETER_CONFIG
	{ {52, 94, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_BARO_HARDWARE }, (setting_offset_t)offsetof(barometerConfig_t, baro_hardware) },
	{ {52, 89, 162, 1, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 3}, (setting_offset_t)offsetof(barometerConfig_t, baro_calibration_tolerance) },
	{ {52, 161, 1, 124, 0, 0}, VAR_FLOAT | MASTER_VALUE, .config.minmax.indexes = {36, 43}, (setting_offset_t)offsetof(barometerConfig_t, baro_temp_correction) },
	// PG_RX_CONFIG
	{ {171, 2, 26, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_RECEIVER_TYPE }, (setting_offset_t)offsetof(rxConfig_t, receiverType) },
	{ {15, 123, 0, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {3, 4}, (setting_offset_t)offsetof(rxConfig_t, mincheck) },
	{ {14, 123, 0, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {3, 4}, (setting_offset_t)offsetof(rxConfig_t, maxcheck) },
	{ {80, 192, 2, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_RSSI_SOURCE }, (setting_offset_t)offsetof(rxConfig_t, rssi_source) },
	{ {80, 192, 1, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 61}, (setting_offset_t)offsetof(rxConfig_t, rssi_channel) },
	{ {80, 15, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(rxConfig_t, rssiMin) },
	{ {80, 14, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(rxConfig_t, rssiMax) },
	{ {182, 2, 200, 2, 247, 1}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {13, 15}, (setting_offset_t)offsetof(rxConfig_t, sbusSyncInterval) },
	{ {42, 60, 24, 23, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {18, 23}, (setting_offset_t)offsetof(rxConfig_t, rcFilterFrequency) },
	{ {42, 60, 35, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(rxConfig_t, autoSmooth) },
	{ {42, 60, 112, 221, 1, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {7, 2}, (setting_offset_t)offsetof(rxConfig_t, autoSmoothFactor) },
	{ {158, 1, 15, 166, 1, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {47, 49}, (setting_offset_t)offsetof(rxConfig_t, rx_min_usec) },
	{ {158, 1, 14, 166, 1, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {47, 49}, (setting_offset_t)offsetof(rxConfig_t, rx_max_usec) },
	{ {185, 2, 136, 1, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_TRISTATE }, (setting_offset_t)offsetof(rxConfig_t, halfDuplex) },
	// PG_MOTOR_CONFIG
	{ {15, 194, 1, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 4}, (setting_offset_t)offsetof(motorConfig_t, mincommand) },
	{ {47, 65, 4, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {11, 78}, (setting_offset_t)offsetof(motorConfig_t, motorPwmRate) },
	{ {47, 65, 153, 1, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_MOTOR_PWM_PROTOCOL }, (setting_offset_t)offsetof(motorConfig_t, motorPwmProtocol) },
	{ {47, 163, 2, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {28, 1}, (setting_offset_t)offsetof(motorConfig_t, motorPoleCount) },
	// PG_FAILSAFE_CONFIG
	{ {18, 28, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 6}, (setting_offset_t)offsetof(failsafeConfig_t, failsafe_delay) },
	{ {18, 173, 2, 28, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 6}, (setting_offset_t)offsetof(failsafeConfig_t, failsafe_recovery_delay) },
	{ {18, 153, 2, 28, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 6}, (setting_offset_t)offsetof(failsafeConfig_t, failsafe_off_delay) },
	{ {18, 32, 100, 28, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 32}, (setting_offset_t)offsetof(failsafeConfig_t, failsafe_throttle_low_delay) },
	{ {18, 151, 1, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_FAILSAFE_PROCEDURE }, (setting_offset_t)offsetof(failsafeConfig_t, failsafe_procedure) },
	{ {18, 197, 2, 66, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 13}, (setting_offset_t)offsetof(failsafeConfig_t, failsafe_stick_motion_threshold) },
	{ {18, 2, 13, 22, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {35, 48}, (setting_offset_t)offsetof(failsafeConfig_t, failsafe_fw_roll_angle) },
	{ {18, 2, 8, 22, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {35, 48}, (setting_offset_t)offsetof(failsafeConfig_t, failsafe_fw_pitch_angle) },
	{ {18, 2, 5, 4, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {54, 3}, (setting_offset_t)offsetof(failsafeConfig_t, failsafe_fw_yaw_rate) },
	{ {18, 15, 53, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 16}, (setting_offset_t)offsetof(failsafeConfig_t, failsafe_min_distance) },
	{ {18, 15, 53, 151, 1, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_FAILSAFE_PROCEDURE }, (setting_offset_t)offsetof(failsafeConfig_t, failsafe_min_distance_procedure) },
	{ {18, 104, 28, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {37, 66}, (setting_offset_t)offsetof(failsafeConfig_t, failsafe_mission_delay) },
	// PG_BOARD_ALIGNMENT
	{ {43, 88, 13, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {17, 19}, (setting_offset_t)offsetof(boardAlignment_t, rollDeciDegrees) },
	{ {43, 88, 8, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {17, 19}, (setting_offset_t)offsetof(boardAlignment_t, pitchDeciDegrees) },
	{ {43, 88, 5, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {17, 19}, (setting_offset_t)offsetof(boardAlignment_t, yawDeciDegrees) },
	// PG_BATTERY_METERS_CONFIG
	{ {58, 71, 165, 1, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_BAT_CAPACITY_UNIT }, (setting_offset_t)offsetof(batteryMetersConfig_t, capacity_unit) },
	{ {91, 103, 160, 1, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {53, 15}, (setting_offset_t)offsetof(batteryMetersConfig_t, current.scale) },
	{ {91, 103, 79, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {9, 8}, (setting_offset_t)offsetof(batteryMetersConfig_t, current.offset) },
	{ {91, 103, 26, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_CURRENT_SENSOR }, (setting_offset_t)offsetof(batteryMetersConfig_t, current.type) },
	{ {181, 1, 167, 1, 194, 2}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_BAT_VOLTAGE_SOURCE }, (setting_offset_t)offsetof(batteryMetersConfig_t, voltageSource) },
	{ {73, 150, 1, 0, 0, 0}, VAR_UINT32 | MASTER_VALUE, .config.minmax.indexes = {0, 26}, (setting_offset_t)offsetof(batteryMetersConfig_t, cruise_power) },
	{ {78, 150, 1, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 20}, (setting_offset_t)offsetof(batteryMetersConfig_t, idle_power) },
	{ {16, 214, 1, 128, 2, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(batteryMetersConfig_t, rth_energy_margin) },
	{ {38, 90, 169, 1, 0, 0}, VAR_FLOAT | MASTER_VALUE, .config.minmax.indexes = {0, 12}, (setting_offset_t)offsetof(batteryMetersConfig_t, throttle_compensation_weight) },
	// PG_BATTERY_PROFILES
	{ {58, 71, 0, 0, 0, 0}, VAR_UINT32 | BATTERY_CONFIG_VALUE, .config.minmax.indexes = {0, 26}, (setting_offset_t)offsetof(batteryProfile_t, capacity.value) },
	{ {58, 71, 218, 2, 0, 0}, VAR_UINT32 | BATTERY_CONFIG_VALUE, .config.minmax.indexes = {0, 26}, (setting_offset_t)offsetof(batteryProfile_t, capacity.warning) },
	{ {58, 71, 198, 1, 0, 0}, VAR_UINT32 | BATTERY_CONFIG_VALUE, .config.minmax.indexes = {0, 26}, (setting_offset_t)offsetof(batteryProfile_t, capacity.critical) },
	{ {56, 45, 152, 1, 0, 0}, VAR_UINT8 | BATTERY_CONFIG_VALUE, .config.minmax.indexes = {0, 58}, (setting_offset_t)offsetof(batteryProfile_t, controlProfile) },
	{ {32, 160, 1, 0, 0, 0}, VAR_FLOAT | BATTERY_CONFIG_VALUE, .config.minmax.indexes = {0, 7}, (setting_offset_t)offsetof(batteryProfile_t, motor.throttleScale) },
	{ {32, 78, 0, 0, 0, 0}, VAR_FLOAT | BATTERY_CONFIG_VALUE, .config.minmax.indexes = {0, 29}, (setting_offset_t)offsetof(batteryProfile_t, motor.throttleIdle) },
	{ {18, 32, 0, 0, 0, 0}, VAR_UINT16 | BATTERY_CONFIG_VALUE, .config.minmax.indexes = {3, 4}, (setting_offset_t)offsetof(batteryProfile_t, failsafe_throttle) },
	{ {1, 3, 242, 1, 38, 0}, VAR_UINT16 | BATTERY_CONFIG_VALUE, .config.minmax.indexes = {3, 4}, (setting_offset_t)offsetof(batteryProfile_t, nav.mc.hover_throttle) },
	{ {1, 2, 73, 38, 0, 0}, VAR_UINT16 | BATTERY_CONFIG_VALUE, .config.minmax.indexes = {3, 4}, (setting_offset_t)offsetof(batteryProfile_t, nav.fw.cruise_throttle) },
	{ {1, 2, 15, 38, 0, 0}, VAR_UINT16 | BATTERY_CONFIG_VALUE, .config.minmax.indexes = {3, 4}, (setting_offset_t)offsetof(batteryProfile_t, nav.fw.min_throttle) },
	{ {1, 2, 14, 38, 0, 0}, VAR_UINT16 | BATTERY_CONFIG_VALUE, .config.minmax.indexes = {3, 4}, (setting_offset_t)offsetof(batteryProfile_t, nav.fw.max_throttle) },
	{ {1, 2, 109, 0, 0, 0}, VAR_UINT8 | BATTERY_CONFIG_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(batteryProfile_t, nav.fw.pitch_to_throttle) },
	{ {1, 2, 11, 38, 0, 0}, VAR_UINT16 | BATTERY_CONFIG_VALUE, .config.minmax.indexes = {3, 4}, (setting_offset_t)offsetof(batteryProfile_t, nav.fw.launch_throttle) },
	{ {1, 2, 11, 78, 38, 0}, VAR_UINT16 | BATTERY_CONFIG_VALUE, .config.minmax.indexes = {3, 4}, (setting_offset_t)offsetof(batteryProfile_t, nav.fw.launch_idle_throttle) },
	// PG_MIXER_PROFILE
	{ {47, 127, 139, 1, 0, 0}, VAR_UINT8 | MIXER_CONFIG_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(mixerProfile_t, mixer_config.motorDirectionInverted) },
	{ {162, 2, 26, 0, 0, 0}, VAR_UINT8 | MIXER_CONFIG_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_PLATFORM_TYPE }, (setting_offset_t)offsetof(mixerProfile_t, mixer_config.platformType) },
	{ {239, 1, 224, 1, 0, 0}, VAR_UINT8 | MIXER_CONFIG_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(mixerProfile_t, mixer_config.hasFlaps) },
	{ {145, 1, 166, 2, 26, 0}, VAR_INT16 | MIXER_CONFIG_VALUE, .config.minmax.indexes = {37, 8}, (setting_offset_t)offsetof(mixerProfile_t, mixer_config.appliedMixerPreset) },
	{ {133, 2, 108, 100, 0, 0}, VAR_UINT8 | MIXER_CONFIG_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(mixerProfile_t, mixer_config.motorstopOnLow) },
	{ {105, 45, 152, 1, 250, 1}, VAR_UINT8 | MIXER_CONFIG_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(mixerProfile_t, mixer_config.controlProfileLinking) },
	{ {105, 176, 1, 81, 0, 0}, VAR_UINT8 | MIXER_CONFIG_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(mixerProfile_t, mixer_config.automated_switch) },
	{ {105, 81, 208, 2, 206, 2}, VAR_INT16 | MIXER_CONFIG_VALUE, .config.minmax.indexes = {0, 6}, (setting_offset_t)offsetof(mixerProfile_t, mixer_config.switchTransitionTimer) },
	{ {203, 2, 154, 2, 79, 0}, VAR_UINT8 | MIXER_CONFIG_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(mixerProfile_t, mixer_config.tailsitterOrientationOffset) },
	{ {115, 64, 106, 107, 13, 0}, VAR_INT16 | MIXER_CONFIG_VALUE, .config.minmax.indexes = {27, 14}, (setting_offset_t)offsetof(mixerProfile_t, mixer_config.transition_PID_mmix_multiplier_roll) },
	{ {115, 64, 106, 107, 8, 0}, VAR_INT16 | MIXER_CONFIG_VALUE, .config.minmax.indexes = {27, 14}, (setting_offset_t)offsetof(mixerProfile_t, mixer_config.transition_PID_mmix_multiplier_pitch) },
	{ {115, 64, 106, 107, 5, 0}, VAR_INT16 | MIXER_CONFIG_VALUE, .config.minmax.indexes = {27, 14}, (setting_offset_t)offsetof(mixerProfile_t, mixer_config.transition_PID_mmix_multiplier_yaw) },
	// PG_REVERSIBLE_MOTORS_CONFIG
	{ {70, 27, 100, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {3, 4}, (setting_offset_t)offsetof(reversibleMotorsConfig_t, deadband_low) },
	{ {70, 27, 240, 1, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {3, 4}, (setting_offset_t)offsetof(reversibleMotorsConfig_t, deadband_high) },
	{ {70, 152, 2, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {3, 4}, (setting_offset_t)offsetof(reversibleMotorsConfig_t, neutral) },
	// PG_SERVO_CONFIG
	{ {54, 153, 1, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_SERVO_PROTOCOL }, (setting_offset_t)offsetof(servoConfig_t, servo_protocol) },
	{ {54, 190, 1, 168, 2, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {3, 4}, (setting_offset_t)offsetof(servoConfig_t, servoCenterPulse) },
	{ {54, 65, 4, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {11, 65}, (setting_offset_t)offsetof(servoConfig_t, servoPwmRate) },
	{ {54, 24, 23, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {0, 45}, (setting_offset_t)offsetof(servoConfig_t, servo_lowpass_freq) },
	{ {223, 1, 204, 2, 79, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {11, 46}, (setting_offset_t)offsetof(servoConfig_t, flaperon_throw_offset) },
	{ {209, 2, 212, 2, 54, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(servoConfig_t, tri_unarmed_servo) },
	{ {54, 179, 1, 178, 2, 63}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {7, 62}, (setting_offset_t)offsetof(servoConfig_t, servo_autotrim_rotation_limit) },
	// PG_CONTROL_PROFILES
	{ {38, 130, 2, 0, 0, 0}, VAR_UINT8 | CONTROL_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(controlConfig_t, throttle.rcMid8) },
	{ {38, 40, 0, 0, 0, 0}, VAR_UINT8 | CONTROL_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(controlConfig_t, throttle.rcExpo8) },
	{ {174, 1, 164, 2, 0, 0}, VAR_UINT16 | CONTROL_VALUE, .config.minmax.indexes = {0, 6}, (setting_offset_t)offsetof(controlConfig_t, throttle.apa_pow) },
	{ {67, 4, 0, 0, 0, 0}, VAR_UINT8 | CONTROL_VALUE, .config.minmax.indexes = {0, 6}, (setting_offset_t)offsetof(controlConfig_t, throttle.dynPID) },
	{ {67, 186, 1, 0, 0, 0}, VAR_UINT16 | CONTROL_VALUE, .config.minmax.indexes = {3, 4}, (setting_offset_t)offsetof(controlConfig_t, throttle.pa_breakpoint) },
	{ {67, 8, 195, 1, 0, 0}, VAR_UINT8 | CONTROL_VALUE, .config.minmax.indexes = {0, 21}, (setting_offset_t)offsetof(controlConfig_t, throttle.tpa_pitch_compensation) },
	{ {67, 108, 5, 0, 0, 0}, VAR_UINT8 | CONTROL_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(controlConfig_t, throttle.dynPID_on_YAW) },
	{ {2, 67, 48, 197, 1, 0}, VAR_UINT16 | CONTROL_VALUE, .config.minmax.indexes = {0, 14}, (setting_offset_t)offsetof(controlConfig_t, throttle.fixedWingTauMs) },
	{ {42, 40, 0, 0, 0, 0}, VAR_UINT8 | CONTROL_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(controlConfig_t, stabilized.rcExpo8) },
	{ {42, 5, 40, 0, 0, 0}, VAR_UINT8 | CONTROL_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(controlConfig_t, stabilized.rcYawExpo8) },
	{ {13, 4, 0, 0, 0, 0}, VAR_UINT8 | CONTROL_VALUE, .config.minmax.indexes = {28, 22}, (setting_offset_t)offsetof(controlConfig_t, stabilized.rates[FD_ROLL]) },
	{ {8, 4, 0, 0, 0, 0}, VAR_UINT8 | CONTROL_VALUE, .config.minmax.indexes = {28, 22}, (setting_offset_t)offsetof(controlConfig_t, stabilized.rates[FD_PITCH]) },
	{ {5, 4, 0, 0, 0, 0}, VAR_UINT8 | CONTROL_VALUE, .config.minmax.indexes = {7, 22}, (setting_offset_t)offsetof(controlConfig_t, stabilized.rates[FD_YAW]) },
	{ {36, 42, 40, 0, 0, 0}, VAR_UINT8 | CONTROL_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(controlConfig_t, manual.rcExpo8) },
	{ {36, 42, 5, 40, 0, 0}, VAR_UINT8 | CONTROL_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(controlConfig_t, manual.rcYawExpo8) },
	{ {36, 13, 4, 0, 0, 0}, VAR_UINT8 | CONTROL_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(controlConfig_t, manual.rates[FD_ROLL]) },
	{ {36, 8, 4, 0, 0, 0}, VAR_UINT8 | CONTROL_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(controlConfig_t, manual.rates[FD_PITCH]) },
	{ {36, 5, 4, 0, 0, 0}, VAR_UINT8 | CONTROL_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(controlConfig_t, manual.rates[FD_YAW]) },
	{ {225, 1, 131, 2, 208, 1}, VAR_UINT8 | CONTROL_VALUE, .config.minmax.indexes = {0, 11}, (setting_offset_t)offsetof(controlConfig_t, misc.fpvCamAngleDegrees) },
	// PG_IMU_CONFIG
	{ {34, 74, 141, 1, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 20}, (setting_offset_t)offsetof(imuConfig_t, dcm_kp_acc) },
	{ {34, 74, 140, 1, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 20}, (setting_offset_t)offsetof(imuConfig_t, dcm_ki_acc) },
	{ {34, 74, 141, 1, 31, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 20}, (setting_offset_t)offsetof(imuConfig_t, dcm_kp_mag) },
	{ {34, 74, 140, 1, 31, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 20}, (setting_offset_t)offsetof(imuConfig_t, dcm_ki_mag) },
	{ {187, 2, 22, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 22}, (setting_offset_t)offsetof(imuConfig_t, small_angle) },
	{ {34, 33, 99, 4, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 29}, (setting_offset_t)offsetof(imuConfig_t, acc_ignore_rate) },
	{ {34, 33, 99, 186, 2, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 5}, (setting_offset_t)offsetof(imuConfig_t, acc_ignore_slope) },
	{ {34, 10, 5, 219, 2, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(imuConfig_t, gps_yaw_windcomp) },
	{ {34, 244, 1, 90, 129, 2}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_IMU_INERTIA_COMP_METHOD }, (setting_offset_t)offsetof(imuConfig_t, inertia_comp_method) },
	{ {34, 10, 5, 169, 1, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 13}, (setting_offset_t)offsetof(imuConfig_t, gps_yaw_weight) },
	// PG_ARMING_CONFIG
	{ {222, 1, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(armingConfig_t, fixed_wing_auto_arm) },
	{ {75, 173, 1, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(armingConfig_t, disarm_always) },
	{ {81, 75, 28, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 3}, (setting_offset_t)offsetof(armingConfig_t, switchDisarmDelayMs) },
	{ {165, 2, 114, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 15}, (setting_offset_t)offsetof(armingConfig_t, prearmTimeoutMs) },
	// PG_GENERAL_SETTINGS
	{ {175, 1, 207, 1, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 63}, (setting_offset_t)offsetof(generalSettings_t, appliedDefaults) },
	// PG_EZ_TUNE
	{ {29, 92, 0, 0, 0, 0}, VAR_UINT8 | EZ_TUNE_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(ezTuneSettings_t, enabled) },
	{ {29, 60, 23, 0, 0, 0}, VAR_UINT16 | EZ_TUNE_VALUE, .config.minmax.indexes = {21, 32}, (setting_offset_t)offsetof(ezTuneSettings_t, filterHz) },
	{ {29, 180, 1, 170, 2, 0}, VAR_UINT8 | EZ_TUNE_VALUE, .config.minmax.indexes = {40, 64}, (setting_offset_t)offsetof(ezTuneSettings_t, axisRatio) },
	{ {29, 157, 1, 0, 0, 0}, VAR_UINT8 | EZ_TUNE_VALUE, .config.minmax.indexes = {0, 6}, (setting_offset_t)offsetof(ezTuneSettings_t, response) },
	{ {29, 200, 1, 0, 0, 0}, VAR_UINT8 | EZ_TUNE_VALUE, .config.minmax.indexes = {0, 6}, (setting_offset_t)offsetof(ezTuneSettings_t, damping) },
	{ {29, 195, 2, 0, 0, 0}, VAR_UINT8 | EZ_TUNE_VALUE, .config.minmax.indexes = {0, 6}, (setting_offset_t)offsetof(ezTuneSettings_t, stability) },
	{ {29, 170, 1, 0, 0, 0}, VAR_UINT8 | EZ_TUNE_VALUE, .config.minmax.indexes = {0, 6}, (setting_offset_t)offsetof(ezTuneSettings_t, aggressiveness) },
	{ {29, 4, 0, 0, 0, 0}, VAR_UINT8 | EZ_TUNE_VALUE, .config.minmax.indexes = {0, 6}, (setting_offset_t)offsetof(ezTuneSettings_t, rate) },
	{ {29, 40, 0, 0, 0, 0}, VAR_UINT8 | EZ_TUNE_VALUE, .config.minmax.indexes = {0, 6}, (setting_offset_t)offsetof(ezTuneSettings_t, expo) },
	{ {29, 190, 2, 0, 0, 0}, VAR_UINT8 | EZ_TUNE_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(ezTuneSettings_t, snappiness) },
	// PG_GPS_CONFIG
	{ {10, 167, 2, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_GPS_PROVIDER }, (setting_offset_t)offsetof(gpsConfig_t, provider) },
	{ {10, 181, 2, 37, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_GPS_SBAS_MODE }, (setting_offset_t)offsetof(gpsConfig_t, sbasMode) },
	{ {10, 77, 145, 1, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_GPS_DYN_MODEL }, (setting_offset_t)offsetof(gpsConfig_t, dynModel) },
	{ {10, 35, 196, 1, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(gpsConfig_t, autoConfig) },
	{ {10, 35, 182, 1, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(gpsConfig_t, autoBaud) },
	{ {235, 1, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_GPS_AUTO_BAUD_MAX }, (setting_offset_t)offsetof(gpsConfig_t, autoBaudMax) },
	{ {10, 83, 56, 233, 1, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(gpsConfig_t, ubloxUseGalileo) },
	{ {10, 83, 56, 183, 1, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(gpsConfig_t, ubloxUseBeidou) },
	{ {10, 83, 56, 234, 1, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(gpsConfig_t, ubloxUseGlonass) },
	{ {10, 15, 180, 2, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {10, 5}, (setting_offset_t)offsetof(gpsConfig_t, gpsMinSats) },
	{ {10, 83, 1, 23, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {10, 6}, (setting_offset_t)offsetof(gpsConfig_t, ubloxNavHz) },
	// PG_RC_CONTROLS_CONFIG
	{ {27, 0, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 60}, (setting_offset_t)offsetof(rcControlsConfig_t, deadband) },
	{ {5, 27, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(rcControlsConfig_t, yaw_deadband) },
	{ {12, 97, 27, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {12, 23}, (setting_offset_t)offsetof(rcControlsConfig_t, pos_hold_deadband) },
	{ {51, 97, 27, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {5, 23}, (setting_offset_t)offsetof(rcControlsConfig_t, alt_hold_deadband) },
	{ {70, 27, 32, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 6}, (setting_offset_t)offsetof(rcControlsConfig_t, mid_throttle_deadband) },
	{ {119, 26, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_AIRMODEHANDLINGTYPE }, (setting_offset_t)offsetof(rcControlsConfig_t, airmodeHandlingType) },
	{ {119, 32, 66, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {3, 4}, (setting_offset_t)offsetof(rcControlsConfig_t, airmodeThrottleThreshold) },
	// PG_PID_PROFILE
	{ {3, 7, 8, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_PITCH].P) },
	{ {3, 19, 8, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_PITCH].I) },
	{ {3, 17, 8, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_PITCH].D) },
	{ {3, 72, 8, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_PITCH].FF) },
	{ {3, 7, 13, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_ROLL].P) },
	{ {3, 19, 13, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_ROLL].I) },
	{ {3, 17, 13, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_ROLL].D) },
	{ {3, 72, 13, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_ROLL].FF) },
	{ {3, 7, 5, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_YAW].P) },
	{ {3, 19, 5, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_YAW].I) },
	{ {3, 17, 5, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_YAW].D) },
	{ {3, 72, 5, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_YAW].FF) },
	{ {3, 7, 41, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_LEVEL].P) },
	{ {3, 19, 41, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_LEVEL].I) },
	{ {3, 17, 41, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_LEVEL].D) },
	{ {2, 7, 8, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_PITCH].P) },
	{ {2, 19, 8, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_PITCH].I) },
	{ {2, 17, 8, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_PITCH].D) },
	{ {2, 59, 8, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_PITCH].FF) },
	{ {2, 7, 13, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_ROLL].P) },
	{ {2, 19, 13, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_ROLL].I) },
	{ {2, 17, 13, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_ROLL].D) },
	{ {2, 59, 13, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_ROLL].FF) },
	{ {2, 7, 5, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_YAW].P) },
	{ {2, 19, 5, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_YAW].I) },
	{ {2, 17, 5, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_YAW].D) },
	{ {2, 59, 5, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_YAW].FF) },
	{ {2, 7, 41, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_LEVEL].P) },
	{ {2, 19, 41, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_LEVEL].I) },
	{ {2, 17, 41, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_LEVEL].D) },
	{ {14, 22, 138, 1, 177, 2}, VAR_INT16 | PROFILE_VALUE, .config.minmax.indexes = {2, 33}, (setting_offset_t)offsetof(pidProfile_t, max_angle_inclination[FD_ROLL]) },
	{ {14, 22, 138, 1, 160, 2}, VAR_INT16 | PROFILE_VALUE, .config.minmax.indexes = {2, 33}, (setting_offset_t)offsetof(pidProfile_t, max_angle_inclination[FD_PITCH]) },
	{ {130, 1, 24, 23, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 13}, (setting_offset_t)offsetof(pidProfile_t, dterm_lpf_hz) },
	{ {130, 1, 24, 26, 0, 0}, VAR_UINT8 | PROFILE_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_FILTER_TYPE_FULL }, (setting_offset_t)offsetof(pidProfile_t, dterm_lpf_type) },
	{ {5, 24, 23, 0, 0, 0}, VAR_UINT8 | PROFILE_VALUE, .config.minmax.indexes = {0, 6}, (setting_offset_t)offsetof(pidProfile_t, yaw_lpf_hz) },
	{ {2, 174, 2, 171, 1, 0}, VAR_FLOAT | PROFILE_VALUE, .config.minmax.indexes = {32, 73}, (setting_offset_t)offsetof(pidProfile_t, fixedWingReferenceAirspeed) },
	{ {2, 116, 121, 5, 93, 0}, VAR_FLOAT | PROFILE_VALUE, .config.minmax.indexes = {0, 12}, (setting_offset_t)offsetof(pidProfile_t, fixedWingCoordinatedYawGain) },
	{ {2, 116, 121, 8, 93, 0}, VAR_FLOAT | PROFILE_VALUE, .config.minmax.indexes = {0, 12}, (setting_offset_t)offsetof(pidProfile_t, fixedWingCoordinatedPitchGain) },
	{ {232, 1, 0, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 30}, (setting_offset_t)offsetof(pidProfile_t, fixedWingYawItermBankFreeze) },
	{ {61, 220, 2, 0, 0, 0}, VAR_UINT8 | PROFILE_VALUE, .config.minmax.indexes = {0, 30}, (setting_offset_t)offsetof(pidProfile_t, itermWindupPointPercent) },
	{ {64, 61, 63, 157, 2, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 6}, (setting_offset_t)offsetof(pidProfile_t, pidItermLimitPercent) },
	{ {4, 84, 63, 13, 8, 0}, VAR_UINT32 | PROFILE_VALUE, .config.minmax.indexes = {0, 51}, (setting_offset_t)offsetof(pidProfile_t, axisAccelerationLimitRollPitch) },
	{ {4, 84, 63, 5, 0, 0}, VAR_UINT32 | PROFILE_VALUE, .config.minmax.indexes = {0, 51}, (setting_offset_t)offsetof(pidProfile_t, axisAccelerationLimitYaw) },
	{ {96, 97, 4, 63, 0, 0}, VAR_UINT8 | PROFILE_VALUE, .config.minmax.indexes = {5, 23}, (setting_offset_t)offsetof(pidProfile_t, heading_hold_rate_limit) },
	{ {1, 3, 12, 9, 7, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_POS_Z].P) },
	{ {1, 3, 50, 9, 7, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_VEL_Z].P) },
	{ {1, 3, 50, 9, 19, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_VEL_Z].I) },
	{ {1, 3, 50, 9, 17, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_VEL_Z].D) },
	{ {1, 3, 12, 21, 7, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_POS_XY].P) },
	{ {1, 3, 50, 21, 7, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_VEL_XY].P) },
	{ {1, 3, 50, 21, 19, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_VEL_XY].I) },
	{ {1, 3, 50, 21, 17, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_VEL_XY].D) },
	{ {1, 3, 50, 21, 59, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_VEL_XY].FF) },
	{ {1, 3, 96, 7, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_HEADING].P) },
	{ {146, 2, 0, 0, 0, 0}, VAR_FLOAT | PROFILE_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(pidProfile_t, navVelXyDTermLpfHz) },
	{ {143, 2, 0, 0, 0, 0}, VAR_UINT8 | PROFILE_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(pidProfile_t, navVelXyDtermAttenuation) },
	{ {145, 2, 0, 0, 0, 0}, VAR_UINT8 | PROFILE_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(pidProfile_t, navVelXyDtermAttenuationStart) },
	{ {144, 2, 0, 0, 0, 0}, VAR_UINT8 | PROFILE_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(pidProfile_t, navVelXyDtermAttenuationEnd) },
	{ {1, 2, 12, 9, 7, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_POS_Z].P) },
	{ {1, 2, 12, 9, 19, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_POS_Z].I) },
	{ {1, 2, 12, 9, 17, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_POS_Z].D) },
	{ {1, 2, 12, 9, 59, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_POS_Z].FF) },
	{ {1, 2, 51, 45, 157, 1}, VAR_UINT8 | PROFILE_VALUE, .config.minmax.indexes = {10, 2}, (setting_offset_t)offsetof(pidProfile_t, fwAltControlResponseFactor) },
	{ {1, 2, 51, 56, 149, 1}, VAR_UINT8 | PROFILE_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(pidProfile_t, fwAltControlUsePos) },
	{ {1, 2, 12, 21, 7, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_POS_XY].P) },
	{ {1, 2, 12, 21, 19, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_POS_XY].I) },
	{ {1, 2, 12, 21, 17, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_POS_XY].D) },
	{ {1, 2, 96, 7, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_HEADING].P) },
	{ {1, 2, 12, 95, 7, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_POS_HEADING].P) },
	{ {1, 2, 12, 95, 19, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_POS_HEADING].I) },
	{ {1, 2, 12, 95, 17, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_POS_HEADING].D) },
	{ {137, 2, 0, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {2, 3}, (setting_offset_t)offsetof(pidProfile_t, navFwPosHdgPidsumLimit) },
	{ {3, 61, 155, 1, 0, 0}, VAR_UINT8 | PROFILE_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_ITERM_RELAX }, (setting_offset_t)offsetof(pidProfile_t, iterm_relax) },
	{ {3, 61, 155, 1, 125, 0}, VAR_UINT8 | PROFILE_VALUE, .config.minmax.indexes = {7, 2}, (setting_offset_t)offsetof(pidProfile_t, iterm_relax_cutoff) },
	{ {64, 26, 0, 0, 0, 0}, VAR_UINT8 | PROFILE_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_PIDTYPETABLE }, (setting_offset_t)offsetof(pidProfile_t, pidControllerType) },
	{ {3, 72, 24, 23, 0, 0}, VAR_UINT8 | PROFILE_VALUE, .config.minmax.indexes = {0, 6}, (setting_offset_t)offsetof(pidProfile_t, controlDerivativeLpfHz) },
	{ {2, 41, 8, 210, 2, 0}, VAR_FLOAT | PROFILE_VALUE, .config.minmax.indexes = {57, 5}, (setting_offset_t)offsetof(pidProfile_t, fixedWingLevelTrim) },
	{ {2, 41, 8, 93, 0, 0}, VAR_FLOAT | PROFILE_VALUE, .config.minmax.indexes = {0, 21}, (setting_offset_t)offsetof(pidProfile_t, fixedWingLevelTrimGain) },
	{ {231, 1, 0, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {2, 3}, (setting_offset_t)offsetof(pidProfile_t, fwItermLockTimeMaxMs) },
	{ {2, 61, 251, 1, 4, 66}, VAR_UINT8 | PROFILE_VALUE, .config.minmax.indexes = {5, 2}, (setting_offset_t)offsetof(pidProfile_t, fwItermLockRateLimit) },
	{ {230, 1, 0, 0, 0, 0}, VAR_UINT8 | PROFILE_VALUE, .config.minmax.indexes = {10, 40}, (setting_offset_t)offsetof(pidProfile_t, fwItermLockEngageThreshold) },
	// PG_POSITION_ESTIMATION_CONFIG
	{ {6, 35, 31, 204, 1, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(positionEstimationConfig_t, automatic_mag_declination) },
	{ {6, 135, 1, 89, 162, 1}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(positionEstimationConfig_t, gravity_calibration_tolerance) },
	{ {6, 120, 201, 1, 172, 2}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(positionEstimationConfig_t, allow_dead_reckoning) },
	{ {6, 110, 44, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_RESET_TYPE }, (setting_offset_t)offsetof(positionEstimationConfig_t, reset_altitude_type) },
	{ {6, 110, 137, 1, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_RESET_TYPE }, (setting_offset_t)offsetof(positionEstimationConfig_t, reset_home_type) },
	{ {6, 14, 113, 44, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 3}, (setting_offset_t)offsetof(positionEstimationConfig_t, max_surface_altitude) },
	{ {6, 20, 9, 113, 7, 0}, VAR_FLOAT | MASTER_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(positionEstimationConfig_t, w_z_surface_p) },
	{ {6, 20, 9, 113, 49, 0}, VAR_FLOAT | MASTER_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(positionEstimationConfig_t, w_z_surface_v) },
	{ {6, 20, 21, 134, 1, 7}, VAR_FLOAT | MASTER_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(positionEstimationConfig_t, w_xy_flow_p) },
	{ {6, 20, 21, 134, 1, 49}, VAR_FLOAT | MASTER_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(positionEstimationConfig_t, w_xy_flow_v) },
	{ {6, 20, 9, 52, 7, 0}, VAR_FLOAT | MASTER_VALUE, .config.minmax.indexes = {0, 5}, (setting_offset_t)offsetof(positionEstimationConfig_t, w_z_baro_p) },
	{ {6, 20, 9, 52, 49, 0}, VAR_FLOAT | MASTER_VALUE, .config.minmax.indexes = {0, 5}, (setting_offset_t)offsetof(positionEstimationConfig_t, w_z_baro_v) },
	{ {6, 20, 9, 10, 7, 0}, VAR_FLOAT | MASTER_VALUE, .config.minmax.indexes = {0, 5}, (setting_offset_t)offsetof(positionEstimationConfig_t, w_z_gps_p) },
	{ {6, 20, 9, 10, 49, 0}, VAR_FLOAT | MASTER_VALUE, .config.minmax.indexes = {0, 5}, (setting_offset_t)offsetof(positionEstimationConfig_t, w_z_gps_v) },
	{ {6, 20, 21, 10, 7, 0}, VAR_FLOAT | MASTER_VALUE, .config.minmax.indexes = {0, 5}, (setting_offset_t)offsetof(positionEstimationConfig_t, w_xy_gps_p) },
	{ {6, 20, 21, 10, 49, 0}, VAR_FLOAT | MASTER_VALUE, .config.minmax.indexes = {0, 5}, (setting_offset_t)offsetof(positionEstimationConfig_t, w_xy_gps_v) },
	{ {6, 20, 9, 156, 1, 49}, VAR_FLOAT | MASTER_VALUE, .config.minmax.indexes = {0, 5}, (setting_offset_t)offsetof(positionEstimationConfig_t, w_z_res_v) },
	{ {6, 20, 21, 156, 1, 49}, VAR_FLOAT | MASTER_VALUE, .config.minmax.indexes = {0, 5}, (setting_offset_t)offsetof(positionEstimationConfig_t, w_xy_res_v) },
	{ {6, 20, 33, 184, 1, 0}, VAR_FLOAT | MASTER_VALUE, .config.minmax.indexes = {0, 7}, (setting_offset_t)offsetof(positionEstimationConfig_t, w_acc_bias) },
	{ {6, 14, 216, 1, 132, 1}, VAR_FLOAT | MASTER_VALUE, .config.minmax.indexes = {0, 50}, (setting_offset_t)offsetof(positionEstimationConfig_t, max_eph_epv) },
	{ {6, 52, 132, 1, 0, 0}, VAR_FLOAT | MASTER_VALUE, .config.minmax.indexes = {0, 50}, (setting_offset_t)offsetof(positionEstimationConfig_t, baro_epv) },
	{ {6, 206, 1, 51, 184, 2}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_DEFAULT_ALTITUDE_SOURCE }, (setting_offset_t)offsetof(positionEstimationConfig_t, default_alt_sensor) },
	// PG_NAV_CONFIG
	{ {1, 75, 108, 62, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(navConfig_t, general.flags.disarm_on_landing) },
	{ {1, 46, 126, 183, 2, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {7, 18}, (setting_offset_t)offsetof(navConfig_t, general.land_detect_sensitivity) },
	{ {1, 62, 187, 1, 209, 1}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(navConfig_t, general.flags.landing_bump_detection) },
	{ {142, 2, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 18}, (setting_offset_t)offsetof(navConfig_t, mc.inverted_crash_detection) },
	{ {1, 3, 172, 1, 32, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_NAV_MC_ALTHOLD_THROTTLE }, (setting_offset_t)offsetof(navConfig_t, mc.althold_throttle_type) },
	{ {134, 2, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_NAV_EXTRA_ARMING_SAFETY }, (setting_offset_t)offsetof(navConfig_t, general.flags.extra_arming_safety) },
	{ {1, 215, 2, 45, 37, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_NAV_USER_CONTROL_MODE }, (setting_offset_t)offsetof(navConfig_t, general.flags.user_control_mode) },
	{ {1, 149, 1, 114, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 5}, (setting_offset_t)offsetof(navConfig_t, general.pos_failure_timeout) },
	{ {151, 2, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(navConfig_t, general.waypoint_load_on_boot) },
	{ {1, 57, 154, 1, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {5, 15}, (setting_offset_t)offsetof(navConfig_t, general.waypoint_radius) },
	{ {1, 57, 215, 1, 44, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 4}, (setting_offset_t)offsetof(navConfig_t, general.waypoint_enforce_altitude) },
	{ {1, 57, 14, 179, 2, 53}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 69}, (setting_offset_t)offsetof(navConfig_t, general.waypoint_safe_distance) },
	{ {1, 57, 104, 176, 2, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_NAV_WP_MISSION_RESTART }, (setting_offset_t)offsetof(navConfig_t, general.flags.waypoint_mission_restart) },
	{ {139, 2, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 5}, (setting_offset_t)offsetof(navConfig_t, fw.wp_tracking_accuracy) },
	{ {140, 2, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {29, 24}, (setting_offset_t)offsetof(navConfig_t, fw.wp_tracking_max_angle) },
	{ {1, 2, 57, 116, 112, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_NAV_FW_WP_TURN_SMOOTHING }, (setting_offset_t)offsetof(navConfig_t, fw.wp_turn_smoothing) },
	{ {1, 35, 55, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {5, 4}, (setting_offset_t)offsetof(navConfig_t, general.auto_speed) },
	{ {1, 15, 236, 1, 55, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {59, 11}, (setting_offset_t)offsetof(navConfig_t, general.min_ground_speed) },
	{ {1, 14, 35, 55, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {5, 4}, (setting_offset_t)offsetof(navConfig_t, general.max_auto_speed) },
	{ {1, 36, 55, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {5, 4}, (setting_offset_t)offsetof(navConfig_t, general.max_manual_speed) },
	{ {1, 46, 144, 1, 168, 1}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {11, 13}, (setting_offset_t)offsetof(navConfig_t, general.land_minalt_vspd) },
	{ {1, 46, 143, 1, 168, 1}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {2, 4}, (setting_offset_t)offsetof(navConfig_t, general.land_maxalt_vspd) },
	{ {1, 46, 111, 144, 1, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {11, 3}, (setting_offset_t)offsetof(navConfig_t, general.land_slowdown_minalt) },
	{ {1, 46, 111, 143, 1, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {13, 72}, (setting_offset_t)offsetof(navConfig_t, general.land_slowdown_maxalt) },
	{ {1, 131, 1, 62, 55, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {2, 4}, (setting_offset_t)offsetof(navConfig_t, general.emerg_descent_rate) },
	{ {1, 15, 16, 53, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 14}, (setting_offset_t)offsetof(navConfig_t, general.min_rth_distance) },
	{ {1, 156, 2, 47, 198, 2}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_NAV_OVERRIDES_MOTOR_STOP }, (setting_offset_t)offsetof(navConfig_t, general.flags.nav_overrides_motor_stop) },
	{ {138, 2, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(navConfig_t, general.flags.soaring_motor_stop) },
	{ {1, 2, 191, 2, 8, 27}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 18}, (setting_offset_t)offsetof(navConfig_t, fw.soaring_pitch_deadband) },
	{ {1, 16, 39, 133, 1, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_NAV_RTH_CLIMB_FIRST }, (setting_offset_t)offsetof(navConfig_t, general.flags.rth_climb_first) },
	{ {148, 2, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_NAV_RTH_CLIMB_FIRST_STAGE_MODES }, (setting_offset_t)offsetof(navConfig_t, general.flags.rth_climb_first_stage_mode) },
	{ {147, 2, 0, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 16}, (setting_offset_t)offsetof(navConfig_t, general.rth_climb_first_stage_altitude) },
	{ {1, 16, 39, 99, 131, 1}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(navConfig_t, general.flags.rth_climb_ignore_emerg) },
	{ {1, 16, 202, 2, 133, 1}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(navConfig_t, general.flags.rth_tail_first) },
	{ {1, 16, 120, 62, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_NAV_RTH_ALLOW_LANDING }, (setting_offset_t)offsetof(navConfig_t, general.flags.rth_allow_landing) },
	{ {1, 16, 228, 1, 62, 28}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 70}, (setting_offset_t)offsetof(navConfig_t, general.rth_fs_landing_delay) },
	{ {1, 16, 51, 37, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_NAV_RTH_ALT_MODE }, (setting_offset_t)offsetof(navConfig_t, general.flags.rth_alt_control_mode) },
	{ {1, 16, 51, 45, 155, 2}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(navConfig_t, general.flags.rth_alt_control_override) },
	{ {1, 16, 118, 66, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 16}, (setting_offset_t)offsetof(navConfig_t, general.rth_abort_threshold) },
	{ {141, 2, 0, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 3}, (setting_offset_t)offsetof(navConfig_t, general.max_terrain_follow_altitude) },
	{ {1, 14, 44, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 16}, (setting_offset_t)offsetof(navConfig_t, general.max_altitude) },
	{ {1, 16, 44, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 16}, (setting_offset_t)offsetof(navConfig_t, general.rth_altitude) },
	{ {1, 16, 137, 1, 44, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 16}, (setting_offset_t)offsetof(navConfig_t, general.rth_home_altitude) },
	{ {149, 2, 0, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 15}, (setting_offset_t)offsetof(navConfig_t, general.rth_linear_descent_start_distance) },
	{ {150, 2, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(navConfig_t, general.flags.rth_use_linear_descent) },
	{ {1, 16, 163, 1, 37, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_RTH_TRACKBACK_MODE }, (setting_offset_t)offsetof(navConfig_t, general.flags.rth_trackback_mode) },
	{ {1, 16, 163, 1, 53, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {11, 4}, (setting_offset_t)offsetof(navConfig_t, general.rth_trackback_distance) },
	{ {159, 1, 14, 53, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 16}, (setting_offset_t)offsetof(navConfig_t, general.safehome_max_distance) },
	{ {159, 1, 214, 2, 37, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_SAFEHOME_USAGE_MODE }, (setting_offset_t)offsetof(navConfig_t, general.flags.safehome_usage_mode) },
	{ {1, 104, 161, 2, 110, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(navConfig_t, general.flags.mission_planner_reset) },
	{ {1, 73, 5, 4, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 31}, (setting_offset_t)offsetof(navConfig_t, general.cruise_yaw_rate) },
	{ {1, 3, 122, 22, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {18, 42}, (setting_offset_t)offsetof(navConfig_t, mc.max_bank_angle) },
	{ {1, 3, 35, 39, 4, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {5, 4}, (setting_offset_t)offsetof(navConfig_t, mc.max_auto_climb_rate) },
	{ {1, 3, 36, 39, 4, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {5, 4}, (setting_offset_t)offsetof(navConfig_t, mc.max_manual_climb_rate) },
	{ {1, 35, 75, 28, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {2, 15}, (setting_offset_t)offsetof(navConfig_t, general.auto_disarm_delay) },
	{ {1, 3, 12, 203, 1, 48}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(navConfig_t, mc.posDecelerationTime) },
	{ {1, 3, 12, 40, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(navConfig_t, mc.posResponseExpo) },
	{ {1, 3, 57, 111, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(navConfig_t, mc.slowDownForTurning) },
	{ {1, 2, 122, 22, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {10, 24}, (setting_offset_t)offsetof(navConfig_t, fw.max_bank_angle) },
	{ {1, 2, 35, 39, 4, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {5, 4}, (setting_offset_t)offsetof(navConfig_t, fw.max_auto_climb_rate) },
	{ {1, 2, 36, 39, 4, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {5, 71}, (setting_offset_t)offsetof(navConfig_t, fw.max_manual_climb_rate) },
	{ {1, 2, 39, 22, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {10, 24}, (setting_offset_t)offsetof(navConfig_t, fw.max_climb_angle) },
	{ {1, 2, 128, 1, 22, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {10, 24}, (setting_offset_t)offsetof(navConfig_t, fw.max_dive_angle) },
	{ {1, 2, 109, 112, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 38}, (setting_offset_t)offsetof(navConfig_t, fw.pitch_to_throttle_smooth) },
	{ {2, 15, 32, 211, 1, 8}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 46}, (setting_offset_t)offsetof(navConfig_t, fw.minThrottleDownPitchAngle) },
	{ {1, 2, 109, 66, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 33}, (setting_offset_t)offsetof(navConfig_t, fw.pitch_to_throttle_thresh) },
	{ {1, 2, 142, 1, 154, 1}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 77}, (setting_offset_t)offsetof(navConfig_t, fw.loiter_radius) },
	{ {2, 142, 1, 127, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_DIRECTION }, (setting_offset_t)offsetof(navConfig_t, fw.loiter_direction) },
	{ {1, 2, 73, 55, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 20}, (setting_offset_t)offsetof(navConfig_t, fw.cruise_speed) },
	{ {1, 2, 45, 189, 2, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 38}, (setting_offset_t)offsetof(navConfig_t, fw.control_smoothness) },
	{ {1, 2, 46, 128, 1, 22}, VAR_INT8 | MASTER_VALUE, .config.minmax.indexes = {56, 21}, (setting_offset_t)offsetof(navConfig_t, fw.land_dive_angle) },
	{ {1, 2, 11, 216, 2, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {2, 15}, (setting_offset_t)offsetof(navConfig_t, fw.launch_velocity_thresh) },
	{ {1, 2, 11, 84, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {68, 76}, (setting_offset_t)offsetof(navConfig_t, fw.launch_accel_thresh) },
	{ {1, 2, 11, 14, 22, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {10, 22}, (setting_offset_t)offsetof(navConfig_t, fw.launch_max_angle) },
	{ {1, 2, 11, 126, 48, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {5, 3}, (setting_offset_t)offsetof(navConfig_t, fw.launch_time_thresh) },
	{ {1, 2, 11, 78, 47, 28}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 25}, (setting_offset_t)offsetof(navConfig_t, fw.launch_idle_motor_timer) },
	{ {136, 2, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 12}, (setting_offset_t)offsetof(navConfig_t, fw.launch_wiggle_wake_idle) },
	{ {1, 2, 11, 47, 28, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 14}, (setting_offset_t)offsetof(navConfig_t, fw.launch_motor_timer) },
	{ {1, 2, 11, 193, 2, 48}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 3}, (setting_offset_t)offsetof(navConfig_t, fw.launch_motor_spinup_time) },
	{ {1, 2, 11, 213, 1, 48}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 14}, (setting_offset_t)offsetof(navConfig_t, fw.launch_end_time) },
	{ {1, 2, 11, 15, 48, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 25}, (setting_offset_t)offsetof(navConfig_t, fw.launch_min_time) },
	{ {1, 2, 11, 114, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 25}, (setting_offset_t)offsetof(navConfig_t, fw.launch_timeout) },
	{ {1, 2, 11, 14, 44, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 25}, (setting_offset_t)offsetof(navConfig_t, fw.launch_max_altitude) },
	{ {1, 2, 11, 39, 22, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {10, 42}, (setting_offset_t)offsetof(navConfig_t, fw.launch_climb_angle) },
	{ {1, 2, 11, 36, 32, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(navConfig_t, fw.launch_manual_throttle) },
	{ {1, 2, 11, 46, 118, 27}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {12, 23}, (setting_offset_t)offsetof(navConfig_t, fw.launch_land_abort_deadband) },
	{ {135, 2, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(navConfig_t, fw.allow_manual_thr_increase) },
	{ {1, 56, 2, 5, 45, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(navConfig_t, fw.useFwNavYawControl) },
	{ {1, 2, 5, 27, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 30}, (setting_offset_t)offsetof(navConfig_t, fw.yawControlDeadband) },
	// PG_TELEMETRY_CONFIG
	{ {82, 81, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(telemetryConfig_t, telemetry_switch) },
	{ {82, 139, 1, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(telemetryConfig_t, telemetry_inverted) },
	{ {226, 1, 8, 13, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(telemetryConfig_t, frsky_pitch_roll) },
	{ {227, 1, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(telemetryConfig_t, frsky_use_legacy_gps_mode_sensor_ids) },
	{ {175, 2, 189, 1, 167, 1}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(telemetryConfig_t, report_cell_voltage) },
	{ {241, 1, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 31}, (setting_offset_t)offsetof(telemetryConfig_t, hottAlarmSoundInterval) },
	{ {82, 136, 1, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(telemetryConfig_t, halfDuplex) },
	{ {188, 2, 229, 1, 165, 1}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_SMARTPORT_FUEL_UNIT }, (setting_offset_t)offsetof(telemetryConfig_t, smartportFuelUnit) },
	{ {243, 1, 82, 26, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(telemetryConfig_t, ibusTelemetryType) },
	{ {253, 1, 213, 2, 4, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_LTM_RATES }, (setting_offset_t)offsetof(telemetryConfig_t, ltmUpdateRate) },
	{ {25, 217, 1, 196, 2, 4}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(telemetryConfig_t, mavlink.extended_status_rate) },
	{ {25, 178, 1, 26, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_MAVLINK_AUTOPILOT_TYPE }, (setting_offset_t)offsetof(telemetryConfig_t, mavlink.autopilot_type) },
	{ {25, 42, 191, 1, 4, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(telemetryConfig_t, mavlink.rc_channels_rate) },
	{ {25, 12, 4, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(telemetryConfig_t, mavlink.position_rate) },
	{ {25, 218, 1, 4, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(telemetryConfig_t, mavlink.extra1_rate) },
	{ {25, 219, 1, 4, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(telemetryConfig_t, mavlink.extra2_rate) },
	{ {25, 220, 1, 4, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(telemetryConfig_t, mavlink.extra3_rate) },
	{ {25, 217, 2, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {7, 12}, (setting_offset_t)offsetof(telemetryConfig_t, mavlink.version) },
	{ {25, 15, 211, 2, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(telemetryConfig_t, mavlink.min_txbuff) },
	{ {25, 169, 2, 26, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_MAVLINK_RADIO_TYPE }, (setting_offset_t)offsetof(telemetryConfig_t, mavlink.radio_type) },
	{ {25, 201, 2, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {7, 1}, (setting_offset_t)offsetof(telemetryConfig_t, mavlink.sysid) },
	// PG_SYSTEM_CONFIG
	{ {202, 1, 37, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_DEBUG_MODES }, (setting_offset_t)offsetof(systemConfig_t, debug_mode) },
	{ {32, 205, 2, 90, 199, 2}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(systemConfig_t, throttle_tilt_compensation_strength) },
	{ {146, 1, 0, 0, 0, 0}, VAR_STRING | MASTER_VALUE, .config.minmax.indexes = {0, 39}, (setting_offset_t)offsetof(systemConfig_t, craftName) },
	{ {158, 2, 146, 1, 0, 0}, VAR_STRING | MASTER_VALUE, .config.minmax.indexes = {0, 39}, (setting_offset_t)offsetof(systemConfig_t, pilotName) },
	// PG_MODE_ACTIVATION_OPERATOR_CONFIG
	{ {132, 2, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_AUX_OPERATOR }, (setting_offset_t)offsetof(modeActivationOperatorConfig_t, modeActivationOperator) },
	// PG_TIME_CONFIG
	{ {164, 1, 79, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {55, 67}, (setting_offset_t)offsetof(timeConfig_t, tz_offset) },
	{ {164, 1, 177, 1, 212, 1}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_TZ_AUTOMATIC_DST }, (setting_offset_t)offsetof(timeConfig_t, tz_automatic_dst) },
	// PG_DISPLAY_CONFIG
	{ {210, 1, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(displayConfig_t, force_sw_blink) },
	// PG_BEEPER_CONFIG
	{ {129, 1, 87, 92, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(beeperConfig_t, dshot_beeper_enabled) },
	{ {129, 1, 87, 207, 2, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {7, 10}, (setting_offset_t)offsetof(beeperConfig_t, dshot_beeper_tone) },
	{ {87, 65, 37, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(beeperConfig_t, pwmMode) },
	// PG_LEDPIN_CONFIG
	{ {249, 1, 159, 2, 65, 37}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_LED_PIN_PWM_MODE }, (setting_offset_t)offsetof(ledPinConfig_t, led_pin_pwm_mode) },
	// PG_DRONECAN_CONFIG
	{ {76, 147, 1, 98, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {7, 44}, (setting_offset_t)offsetof(dronecanConfig_t, nodeID) },
	{ {76, 185, 1, 248, 1, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_DRONECAN_BITRATE_TABLE }, (setting_offset_t)offsetof(dronecanConfig_t, bitRateKbps) },
	{ {76, 58, 98, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(dronecanConfig_t, batteryId) },
	{ {76, 10, 147, 1, 98, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 44}, (setting_offset_t)offsetof(dronecanConfig_t, gpsNodeId) },
};
