// This file has been automatically generated by utils/settings.rb
// Don't make any modifications to it. They will be lost.

#include "platform.h"
#include "config/parameter_group_ids.h"
#include "fc/settings.h"
#include "sensors/gyro.h"
#include "sensors/acceleration.h"
#include "sensors/compass.h"
#include "sensors/barometer.h"
#include "rx/rx.h"
#include "rx/spektrum.h"
#include "flight/mixer.h"
#include "flight/failsafe.h"
#include "sensors/boardalignment.h"
#include "sensors/battery_config_structs.h"
#include "sensors/battery_config_structs.h"
#include "flight/mixer_profile.h"
#include "flight/servos.h"
#include "fc/control_profile_config_struct.h"
#include "flight/imu.h"
#include "config/general_settings.h"
#include "flight/ez_tune.h"
#include "io/gps.h"
#include "fc/rc_controls.h"
#include "flight/pid.h"
#include "navigation/navigation.h"
#include "io/serial.h"
#include "telemetry/telemetry.h"
#include "telemetry/sim.h"
#include "fc/config.h"
#include "fc/rc_modes.h"
#include "common/time.h"
#include "drivers/display.h"
#include "fc/config.h"
#include "drivers/light_ws2811strip.h"
#include "drivers/gimbal_common.h"
#include "io/gimbal_serial.h"
#include "drivers/headtracker_common.h"
#pragma GCC diagnostic ignored "-Wunused-const-variable"
const pgn_t settingsPgn[] = {
	PG_GYRO_CONFIG,
	PG_ACCELEROMETER_CONFIG,
	PG_COMPASS_CONFIG,
	PG_BAROMETER_CONFIG,
	PG_RX_CONFIG,
	PG_MOTOR_CONFIG,
	PG_FAILSAFE_CONFIG,
	PG_BOARD_ALIGNMENT,
	PG_BATTERY_METERS_CONFIG,
	PG_BATTERY_PROFILES,
	PG_MIXER_PROFILE,
	PG_REVERSIBLE_MOTORS_CONFIG,
	PG_SERVO_CONFIG,
	PG_CONTROL_PROFILES,
	PG_IMU_CONFIG,
	PG_ARMING_CONFIG,
	PG_GENERAL_SETTINGS,
	PG_EZ_TUNE,
	PG_GPS_CONFIG,
	PG_RC_CONTROLS_CONFIG,
	PG_PID_PROFILE,
	PG_POSITION_ESTIMATION_CONFIG,
	PG_NAV_CONFIG,
	PG_TELEMETRY_CONFIG,
	PG_SYSTEM_CONFIG,
	PG_MODE_ACTIVATION_OPERATOR_CONFIG,
	PG_TIME_CONFIG,
	PG_DISPLAY_CONFIG,
	PG_BEEPER_CONFIG,
	PG_LEDPIN_CONFIG,
	PG_GIMBAL_CONFIG,
	PG_GIMBAL_SERIAL_CONFIG,
	PG_HEADTRACKER_CONFIG,
};
const uint8_t settingsPgnCounts[] = {
	14,
	12,
	13,
	3,
	14,
	4,
	12,
	3,
	9,
	14,
	12,
	3,
	7,
	19,
	10,
	4,
	1,
	10,
	11,
	7,
	81,
	22,
	89,
	21,
	4,
	1,
	2,
	1,
	3,
	1,
	7,
	1,
	4,
};
static const uint8_t settingNamesWords[] = {
	0x70,0x6c, /* "nav" */ 
	0x3,0x5c, /* "fw" */ 
	0xd,0x18, /* "mc" */ 
	0x24,0x1a,0x14, /* "rate" */ 
	0x19,0xd, /* "yaw" */ 
	0xc0,0x97,0x6,0xc0, /* "inav" */ 
	0x80, /* "p" */ 
	0x20,0x9a,0xd,0x0, /* "pitch" */ 
	0xd0, /* "z" */ 
	0x24,0xf6,0x30, /* "roll" */ 
	0x7,0x84, /* "gps" */ 
	0xc0,0xc0,0xd5,0xc3,0x40, /* "launch" */ 
	0x20,0xf9, /* "pos" */ 
	0x81,0xa1,0xc0, /* "max" */ 
	0x1a,0x97, /* "min" */ 
	0x2,0x54,0x40, /* "rth" */ 
	0x8, /* "d" */ 
	0x3,0x5,0x2c,0x98,0x4c,0x50, /* "failsafe" */ 
	0x24, /* "i" */ 
	0x17, /* "w" */ 
	0x6,0x32, /* "xy" */ 
	0x0,0xb8,0xec,0x28, /* "angle" */ 
	0x11,0xa0, /* "hz" */ 
	0x32,0x6, /* "lpf" */ 
	0x5,0x33,0x2, /* "type" */ 
	0x81,0xa1,0xb3,0x12,0xe5, /* "mavlink" */ 
	0x80,0x85,0x9,0x4,0x17,0x10, /* "deadband" */ 
	0x4,0x2b,0x3,0x90, /* "delay" */ 
	0x17,0x40, /* "ez" */ 
	0x3e,0x64,0xf0, /* "gyro" */ 
	0x34,0x27, /* "mag" */ 
	0x5,0x11,0x27,0xd2,0x8c,0x28, /* "throttle" */ 
	0x2,0x31, /* "acc" */ 
	0x80,0x28,0x94, /* "ahrs" */ 
	0xc0,0x1a,0xd1,0xe0, /* "auto" */ 
	0x68,0x5d,0x50,0xb0, /* "manual" */ 
	0xd,0x79,0xa, /* "mode" */ 
	0xa,0x22,0x40, /* "thr" */ 
	0x1b,0x12,0xd1, /* "climb" */ 
	0x0,0xb8,0x83, /* "expo" */ 
	0xc0,0xc2,0xd8,0xac, /* "level" */ 
	0x4,0x86, /* "rc" */ 
	0x0,0xb1,0x27,0x70, /* "align" */ 
	0x2,0xca,0x26,0x95,0x21, /* "altitude" */ 
	0x40,0x37,0xba,0x92,0x7b, /* "control" */ 
	0x0,0x74,0xb4,0x41,0x60, /* "gimbal" */ 
	0x18,0x17,0x10, /* "land" */ 
	0xd,0x7d,0x1f,0x20, /* "motor" */ 
	0x51,0x2d,0x28, /* "time" */ 
	0x2c, /* "v" */ 
	0xb,0x15,0x80, /* "vel" */ 
	0xb,0x28, /* "alt" */ 
	0x1,0x6,0x4f, /* "baro" */ 
	0x1,0x13,0x3a,0x5,0xc3,0x28, /* "distance" */ 
	0x26,0x59,0x59,0xe0, /* "servo" */ 
	0x9c,0xa,0x52, /* "speed" */ 
	0x2,0xb3,0x28, /* "use" */ 
	0x2f,0x0, /* "wp" */ 
	0x18,0xc0, /* "ff" */ 
	0x32,0x59,0x42,0xc8, /* "filter" */ 
	0x9,0xa1,0x64,0xd0, /* "iterm" */ 
	0x30,0x2e,0x22,0x5c,0x70, /* "landing" */ 
	0x31,0x2d,0x4d, /* "limit" */ 
	0x1,0x4,0x90, /* "pid" */ 
	0x10,0xbb, /* "pwm" */ 
	0x41,0x44,0x48,0xb3,0x43,0xd8,0x40, /* "threshold" */ 
	0x52,0x1, /* "tpa" */ 
	0x6, /* "x" */ 
	0x1,0x90, /* "y" */ 
	0x6c,0x80, /* "3d" */ 
	0x10,0x69,0x42,0xcb,0x20, /* "battery" */ 
	0x18,0x60,0x11,0xa6,0x99, /* "capacity" */ 
	0x0,0xc8, /* "cd" */ 
	0x1,0xa0,0x2e,0x71,0x58, /* "channel" */ 
	0x1,0xca,0xa9,0x99, /* "cruise" */ 
	0x40,0x41,0xb4, /* "dcm" */ 
	0x4,0x4c,0xc3,0x26, /* "disarm" */ 
	0x80,0x99,0x70, /* "dyn" */ 
	0x10,0x50,0x92,0x92,0x8,0xd6,0x59, /* "headtracker" */ 
	0x1,0x24,0x61, /* "idle" */ 
	0x40,0xf3,0x1a,0x65,0xa0, /* "offset" */ 
	0x24,0x1a,0x25,0xe0, /* "ratio" */ 
	0x94,0xe6,0x90, /* "rssi" */ 
	0x4e,0xe9,0xa0,0xd0, /* "switch" */ 
	0xa,0x15,0x85,0x69,0x69,0x2c, /* "telemetry" */ 
	0x82,0x89,0x65, /* "tilt" */ 
	0x1,0x49,0x25,0xa0, /* "trim" */ 
	0xa8,0x98,0xfc, /* "ublox" */ 
	0x0,0x23,0x19,0x58, /* "accel" */ 
	0x0,0x8c,0x67,0xa,0x5c, /* "accgain" */ 
	0x0,0x8c,0x7a,0x2c,0x9e, /* "acczero" */ 
	0x1,0x14,0xb0,0x2c, /* "beeper" */ 
	0x80,0x27,0x86,0x44, /* "board" */ 
	0x0,0xc2,0xc0, /* "cal" */ 
	0xd,0xed,0x80, /* "comp" */ 
	0x7,0x59,0x48,0xae,0xa0, /* "current" */ 
	0xa,0xe0,0x89,0x85,0x20, /* "enabled" */ 
	0x10,0x19,0x12,0xe1,0x91, /* "hardware" */ 
	0x40,0x82,0x1c, /* "hdg" */ 
	0x8,0x28,0x48,0x97,0x1c, /* "heading" */ 
	0x8,0x7b,0x8, /* "hold" */ 
	0x4,0x9d,0xcf,0x91, /* "ignore" */ 
	0x40,0xc7,0xdc, /* "low" */ 
	0xd,0x9,0xce,0x14,0xb8, /* "maggain" */ 
	0xd,0x9,0xf4,0x59,0x3c, /* "magzero" */ 
	0xd,0x2d,0xb,0x20, /* "meter" */ 
	0x35,0x33,0x9a,0x5e,0xe0, /* "mission" */ 
	0x35,0x38,0x2c, /* "mixer" */ 
	0x80,0xd6,0xa7,0x0, /* "mmix" */ 
	0x6d,0x59,0x44,0xc1,0x89,0x2c, /* "multiplier" */ 
	0x80,0xf7, /* "on" */ 
	0x2,0x1,0x70, /* "pan" */ 
	0x20,0x9a,0xd,0x1c,0xa2,0x24, /* "pitch2thr" */ 
	0x9,0x16,0x65,0xa0, /* "reset" */ 
	0x26,0xc7,0xdc,0x8f,0xbb, /* "slowdown" */ 
	0x81,0x36,0xbd,0xf4,0x42,0x5c,0x70, /* "smoothing" */ 
	0x4e,0xb2,0x30,0x46,0x50, /* "surface" */ 
	0x51,0x2d,0x2b,0xeb,0x40, /* "timeout" */ 
	0x52,0x41,0x74,0xd3,0x44,0xbd,0xc0, /* "transition" */ 
	0xd1,0x64,0xf0, /* "zero" */ 
	0x4,0x4f,0x95, /* "abort" */ 
	0x0,0x14,0xc9,0xaf,0x21, /* "airmode" */ 
	0x40,0x16,0x31,0xf7, /* "allow" */ 
	0x0,0x82,0xe5, /* "bank" */ 
	0x80,0x68,0x28,0xd6, /* "check" */ 
	0x1,0xbe,0x52,0x28,0xe8,0x97,0xb8, /* "correction" */ 
	0x3,0xad,0x1e,0x63, /* "cutoff" */ 
	0x0,0x85,0xa1,0x47,0x40, /* "detect" */ 
	0x11,0x32,0x28,0xe8,0x97,0xb8, /* "direction" */ 
	0x4,0x4d,0x8a, /* "dive" */ 
	0x2,0x4d,0xf,0xa0, /* "dshot" */ 
	0x9,0x42,0xc9,0xa0, /* "dterm" */ 
	0x2b,0x4b,0x23, /* "emerg" */ 
	0x80,0xb0,0xb0, /* "epv" */ 
	0xc,0x99,0x4e,0x80, /* "first" */ 
	0x33,0x1f,0x70, /* "flow" */ 
	0x1e,0x41,0xb2,0x69,0x90, /* "gravity" */ 
	0x20,0x2c,0x31,0x2b,0x6,0x17,0x0, /* "halfduplex" */ 
	0x43,0xda,0x50, /* "home" */ 
	0x25,0xc3,0x62,0x5c,0x1a,0x25,0xee, /* "inclination" */ 
	0x2,0x5d,0x62,0xca,0x85,0x20, /* "inverted" */ 
	0x16,0x90, /* "ki" */ 
	0x2e,0x0, /* "kp" */ 
	0x63,0xd3,0x42,0xc8, /* "loiter" */ 
	0xd,0xe,0x2,0xca, /* "maxalt" */ 
	0x1,0xa9,0x70,0x59,0x40, /* "minalt" */ 
	0x35,0xe4,0x2b, /* "model" */ 
	0x0,0xe0,0xb4,0xa0, /* "name" */ 
	0x73,0xe8,0x34, /* "notch" */ 
	0x2,0xf,0x9a,0x68,0x97,0xb8, /* "position" */ 
	0x10,0x7d,0xcb,0x20, /* "power" */ 
	0x42,0x4f,0x19,0x49,0x59,0x14, /* "procedure" */ 
	0x10,0x93,0xcc,0x96,0x14, /* "profile" */ 
	0x10,0x93,0xe8,0xf1,0xbd,0x80, /* "protocol" */ 
	0x90,0x48,0x9a,0xcc, /* "radius" */ 
	0x12,0x2b,0x3,0x80, /* "relax" */ 
	0x48,0xb3, /* "res" */ 
	0x4,0x8b,0x38,0x3d,0xd3,0x28, /* "response" */ 
	0x25,0x80, /* "rx" */ 
	0x4c,0x26,0x2a,0x1e,0xd2, /* "safehome" */ 
	0x82,0x63,0xb,0xa, /* "scale" */ 
	0x9,0x95,0xd3,0x4d,0x13,0x64,0xd3,0x20, /* "sensitivity" */ 
	0xa1,0x5b,0x0, /* "temp" */ 
	0x51,0xec,0x2c,0x82,0xe1,0x94, /* "tolerance" */ 
	0x14,0x90,0x46,0xb1,0x4,0x6b, /* "trackback" */ 
	0x5,0x34, /* "tz" */ 
	0xa,0xb9,0x34, /* "unit" */ 
	0x5,0x66,0x51, /* "usec" */ 
	0x82,0xcf,0x65,0x2,0x72, /* "voltage" */ 
	0x82,0xd3,0x81, /* "vspd" */ 
	0x1,0x72,0xa4,0xe8,0xa0, /* "weight" */ 
	0x2,0x73,0xc8,0xb3,0x9a,0x6c,0x57,0x16,0x73, /* "aggressiveness" */ 
	0x0,0x53,0x29,0xc0,0xa5,0x20, /* "airspeed" */ 
	0x2,0xca,0x21,0xec,0x20, /* "althold" */ 
	0x2,0xcb,0x87,0x33, /* "always" */ 
	0x0,0x60,0x10, /* "apa" */ 
	0x6,0x10,0x62,0x4a,0x40, /* "applied" */ 
	0x6,0xb4,0x7b,0x43,0x42,0x90, /* "automated" */ 
	0x1,0xad,0x1e,0xd0,0xd1,0x23, /* "automatic" */ 
	0x0,0x6b,0x47,0xc1,0x2c,0x7d, /* "autopilot" */ 
	0x0,0x1a,0xd1,0xf4,0x92,0x5a, /* "autotrim" */ 
	0x0,0xe1,0x33, /* "axis" */ 
	0x0,0x83,0x40, /* "bat" */ 
	0x8,0x35,0x20, /* "baud" */ 
	0x4,0x54,0x91,0xf5, /* "beidou" */ 
	0x0,0x92,0x19, /* "bias" */ 
	0x80,0x52,0x28,0x57,0x7,0xa5,0xd4, /* "breakpoint" */ 
	0x0,0xaa,0xd8, /* "bump" */ 
	0x0,0x61,0x62,0x45,0x20,0xd1,0x2f,0x70, /* "calibration" */ 
	0x6,0x56,0x30, /* "cell" */ 
	0x3,0x2b,0xa8,0x59, /* "center" */ 
	0x0,0x68,0xb, /* "chan" */ 
	0x80,0x36,0xce,0x60, /* "cmss" */ 
	0x1b,0xda,0xd0,0xb8,0x80, /* "command" */ 
	0x1b,0xdb,0x2,0xba,0x61,0xa2,0x5e,0xe0, /* "compensation" */ 
	0xd,0xee,0x32,0x4e, /* "config" */ 
	0x1,0xbd,0xd3,0xa0,0x5d,0x40, /* "constant" */ 
	0xe,0x49,0xa2,0x46,0x16, /* "critical" */ 
	0x0,0x75,0x95,0x8a, /* "curve" */ 
	0x2,0x5,0xb0,0x4b,0x8e, /* "damping" */ 
	0x2,0x14,0x24, /* "dead" */ 
	0x1,0xa,0x2a,0x9c, /* "debug" */ 
	0x4,0x28,0xca,0xc2,0xc8,0x34,0x4b,0xdc, /* "deceleration" */ 
	0x2,0x14,0x6c, /* "decl" */ 
	0x1,0xa,0x36,0x25,0xc1,0xa2,0x5e,0xe0, /* "declination" */ 
	0x10,0xa6,0xd,0x59,0x40, /* "default" */ 
	0x10,0xa6,0xd,0x59,0x49, /* "defaults" */ 
	0x80,0x85,0x3c,0x8a,0x59, /* "degrees" */ 
	0x80,0x85,0xa1,0x47,0x44,0xbd,0xc0, /* "detection" */ 
	0x22,0x67,0x6,0x7,0x3d,0x33,0xe4,0x32,0xf6,0x77,0xe8,0x98,0x97,0x2c, /* "display_force_sw_blink" */ 
	0x4,0x7d,0xdc, /* "down" */ 
	0x2,0x4e,0x80, /* "dst" */ 
	0x2b,0x88, /* "end" */ 
	0x2,0xb8,0xb2,0x3e, /* "energy" */ 
	0x40,0x57,0x19,0xf2,0x19, /* "enforce" */ 
	0x40,0x58,0x20, /* "eph" */ 
	0x5,0xc5, /* "ext" */ 
	0x0,0x5c,0x52,0x41,0xf0, /* "extra1" */ 
	0xb,0x8a,0x48,0x3c, /* "extra2" */ 
	0x1,0x71,0x49,0x7,0x60, /* "extra3" */ 
	0x30,0x47,0x47,0xc8, /* "factor" */ 
	0x6,0x4e,0xa,0x4e,0xdd,0x2e,0x3f,0x43,0x5a,0x3f,0xa1,0x93, /* "fixed_wing_auto_arm" */ 
	0x40,0x66,0x6,0x5,0x93,0xdc, /* "flaperon" */ 
	0x3,0x30,0x30,0x98, /* "flaps" */ 
	0xd,0xb, /* "fpv" */ 
	0x0,0xd2,0x9a,0xf2, /* "frsky" */ 
	0x3,0x4a,0x6b,0xcf,0x6b,0x32,0xf5,0x85,0x38,0x47,0x9e,0x9e,0x13,0xeb,0x5e,0x42,0xf6,0x65,0x74,0xdf,0x2e,0xa4,0x93, /* "frsky_use_legacy_gps_mode_sensor_ids" */ 
	0x1,0xa6, /* "fs" */ 
	0x3,0x54,0xac, /* "fuel" */ 
	0x1,0xaf,0xd4,0xd0,0xb2,0x6f,0x58,0xf1,0xaf,0xa5,0x71,0xc2,0x72,0xf6,0x88,0x91,0x66,0x87,0xb0,0x80, /* "fw_iterm_lock_engage_threshold" */ 
	0x35,0xfa,0x9a,0x16,0x4d,0xeb,0x1e,0x35,0xf6,0x89,0x69,0x7a,0xd0,0xe3,0xad,0x98, /* "fw_iterm_lock_time_max_ms" */ 
	0xd,0x7e,0xd2,0xb2,0x77,0x43,0x39,0xa6,0x74,0xec,0x13,0x41,0xa3,0xa7,0xa,0x5c, /* "fw_turn_assist_pitch_gain" */ 
	0x3,0x5f,0xb4,0xac,0x9d,0xd0,0xce,0x69,0x9d,0x3b,0x90,0xdf,0xa7,0xa,0x5c, /* "fw_turn_assist_yaw_gain" */ 
	0x3,0x5f,0xb9,0xd,0xfa,0x9a,0x16,0x4d,0xe9,0xa4,0x52,0xe8,0xbd,0x10,0x5c,0xbe,0x85,0xc7,0x61, /* "fw_yaw_iterm_freeze_bank_angle" */ 
	0x40,0x70,0xa5,0xc0, /* "gain" */ 
	0x38,0x58,0x96,0x15,0xe0, /* "galileo" */ 
	0x3a,0x5a,0x20,0xb3,0xb3,0x2c,0x92,0x16,0x76,0x69,0x71,0xd8,0x5e,0xd4,0x32,0xa0, /* "gimbal_serial_single_uart" */ 
	0xe,0xc7,0xb8,0x33,0x98, /* "glonass" */ 
	0xf,0x9,0xf4,0x35,0xa3,0xfa,0x20,0xd4,0x9d,0x68,0x71,0xd9,0xd6,0x10,0x7c,0xa8,0x52, /* "gps_auto_baud_max_supported" */ 
	0x0,0xf2,0x7d,0x5c,0x40, /* "ground" */ 
	0x1f,0x32,0x7f,0x42,0xea,0x27,0xa1,0x62,0x43,0x34,0xb8,0xfd,0x64,0xd,0xd4,0x68, /* "gyro_anti_aliasing_lpf_hz" */ 
	0x7,0xcc,0x9f,0xd6,0x55,0x95,0xec,0xc2,0xd8,0x30,0xbd,0x1b,0xea,0xea, /* "gyro_lulu_sample_count" */ 
	0x1,0x1,0x98, /* "has" */ 
	0x10,0x93,0xa0, /* "high" */ 
	0x8,0x7d,0x29,0xd0,0xb0,0x32,0x6f,0x66,0xfa,0xb8,0x9d,0x4b,0xa8,0x59,0x58,0x2c, /* "hott_alarm_sound_interval" */ 
	0x2,0x1f,0x62,0xc8, /* "hover" */ 
	0x9,0x15,0x66, /* "ibus" */ 
	0x4,0xb8,0xb2,0xa2,0x42, /* "inertia" */ 
	0x4,0xb9,0x34, /* "init" */ 
	0x2,0x5d,0x30, /* "ins" */ 
	0x25,0xd4,0x2c,0xac,0x16, /* "interval" */ 
	0x1,0x85,0x20, /* "led" */ 
	0x18,0x97,0x2d,0x2e,0x38, /* "linking" */ 
	0x18,0xf1,0xac, /* "lock" */ 
	0xc,0x7b,0xe1,0x44,0xb4,0xa0, /* "looptime" */ 
	0x65,0x1a, /* "ltm" */ 
	0x6,0x55,0x95, /* "lulu" */ 
	0x3,0x42,0x97, /* "main" */ 
	0x1,0xa1,0x91,0xd2,0xe0, /* "margin" */ 
	0x34,0xb4,0x43,0xc8, /* "method" */ 
	0x6,0xa4,0x80, /* "mid" */ 
	0x6a,0x70, /* "mix" */ 
	0x6,0xbc,0x85,0xec,0x82,0xe3,0x97,0xac,0x79,0xd2,0x3e,0xbe,0x5,0x90,0x68,0xf9, /* "mode_range_logic_operator" */ 
	0x1,0xaf,0xa3,0xe5,0x3a,0x3e,0x0, /* "motorstop" */ 
	0x70,0x6d,0xd2,0xe2,0x92,0xf,0x43,0x26,0xa5,0xc7,0xec,0xc2,0x62,0xd3,0x20, /* "nav_extra_arming_safety" */ 
	0x70,0x6d,0xd3,0x5f,0xa1,0x63,0x1f,0x7e,0xb4,0x2e,0xa8,0x59,0xda,0x22,0x5d,0x4b,0x87,0x22,0x86,0x65, /* "nav_fw_allow_manual_thr_increase" */ 
	0x3,0x83,0x6e,0x9a,0xfd,0x60,0x6a,0xe1,0xa3,0xb7,0x49,0xce,0xc2,0xf6,0x8f,0xed,0xc2,0xb2,0xf5,0x24,0x61, /* "nav_fw_launch_wiggle_to_wake_idle" */ 
	0x40,0xe0,0xdb,0xa6,0xbf,0x60,0xf9,0xf5,0x4,0x3f,0x60,0x92,0x4e,0xad,0xeb,0x12,0xd4,0xd0, /* "nav_fw_pos_hdg_pidsum_limit" */ 
	0xe,0xd,0xba,0x6b,0xf6,0x6f,0xc,0x92,0xe3,0xf5,0xaf,0xa3,0xe5,0xd9,0xd1,0xf0, /* "nav_fw_soaring_motor_stop" */ 
	0x3,0x83,0x6e,0x9a,0xfd,0xbc,0x3b,0x49,0x4,0x6b,0x4b,0x8f,0xd0,0x8c,0x75,0x90,0x47,0x90, /* "nav_fw_wp_tracking_accuracy" */ 
	0x38,0x36,0xe9,0xaf,0xdb,0xc3,0xb4,0x90,0x46,0xb4,0xb8,0xfd,0x68,0x71,0xd0,0xb8,0xec,0x28, /* "nav_fw_wp_tracking_max_angle" */ 
	0x1c,0x1b,0x75,0xa1,0xc7,0x68,0x59,0x48,0x29,0x77,0x4c,0xf6,0x31,0xf7,0xe8,0x59,0x40, /* "nav_max_terrain_follow_alt" */ 
	0x38,0x36,0xeb,0x47,0xd4,0xba,0xc5,0x95,0xa,0x4e,0x8e,0x41,0x9a,0x3a,0x42,0xd0,0xa3,0xa2,0x5e,0xe0, /* "nav_mc_inverted_crash_detection" */ 
	0x38,0x36,0xeb,0x47,0xdb,0x15,0x9d,0xc6,0x7a,0x4a,0x16,0x4d,0xe8,0x69,0x42,0xba,0xa1,0xa2,0x5e,0xe0, /* "nav_mc_vel_xy_dterm_attenuation" */ 
	0x38,0x36,0xeb,0x47,0xdb,0x15,0x9d,0xc6,0x7a,0x4a,0x16,0x4d,0xe8,0x69,0x42,0xba,0xa1,0xa2,0x5e,0xee,0x95,0xc4, /* "nav_mc_vel_xy_dterm_attenuation_end" */ 
	0x3,0x83,0x6e,0xb4,0x7d,0xb1,0x59,0xdc,0x67,0xa4,0xa1,0x64,0xde,0x86,0x94,0x2b,0xaa,0x1a,0x25,0xee,0xec,0xe8,0x19,0x50, /* "nav_mc_vel_xy_dterm_attenuation_start" */ 
	0xe,0xd,0xba,0xd1,0xf6,0xc5,0x67,0x71,0x9e,0x92,0x85,0x93,0x7a,0xc8,0x1b,0xa8,0xd0, /* "nav_mc_vel_xy_dterm_lpf_hz" */ 
	0x1c,0x1b,0x76,0x54,0x47,0x46,0xc4,0xb4,0x5d,0x32,0x65,0x3a,0x76,0x74,0x9,0xcb,0xd0,0xb2,0x89,0xa5,0x48,0x50, /* "nav_rth_climb_first_stage_altitude" */ 
	0x38,0x36,0xec,0xa8,0x8e,0x8d,0x89,0x68,0xba,0x64,0xca,0x74,0xec,0xe8,0x13,0x97,0xad,0x79,0xa, /* "nav_rth_climb_first_stage_mode" */ 
	0x7,0x6,0xdd,0x95,0x11,0xd6,0x25,0xc5,0xc,0xba,0x42,0xcc,0x65,0x75,0x3b,0x3a,0x6,0x54,0xe9,0x13,0x3a,0x5,0xc3,0x28, /* "nav_rth_linear_descent_start_distance" */ 
	0x1c,0x1b,0x76,0x54,0x47,0x6b,0x32,0xf5,0x89,0x71,0x43,0x2e,0x90,0xb3,0x19,0x5d,0x40, /* "nav_rth_use_linear_descent" */ 
	0x38,0x36,0xed,0xe1,0xd6,0x3c,0x24,0xeb,0xdd,0xd1,0x3d,0xf4, /* "nav_wp_load_on_boot" */ 
	0x3,0x8b,0x5a,0x48,0x2c, /* "neutral" */ 
	0x3,0xcc,0x60, /* "off" */ 
	0x3e,0x49,0x2b,0xa8,0x1a,0x25,0xee, /* "orientation" */ 
	0x3,0xec,0x59,0x49,0x24,0x28, /* "override" */ 
	0x1f,0x62,0xca,0x49,0x21,0x66, /* "overrides" */ 
	0x8,0x16,0x43,0x2b,0xa8, /* "percent" */ 
	0x8,0x25,0x8f,0xa0, /* "pilot" */ 
	0x20,0x97, /* "pin" */ 
	0x2,0x9,0xa0, /* "pit" */ 
	0x20,0xc0,0xb9,0xc5,0x90, /* "planner" */ 
	0x20,0xc0,0xd0,0xcf,0x93, /* "platform" */ 
	0x41,0x7,0xb0,0xb3, /* "poles" */ 
	0x4,0x1f,0x70, /* "pow" */ 
	0x42,0x45,0xc,0x9a, /* "prearm" */ 
	0x8,0x48,0xb6,0x49,0x6e, /* "preview" */ 
	0x8,0x49,0xf6,0x49,0xb,0x20, /* "provider" */ 
	0x42,0xac,0x99, /* "pulse" */ 
	0x41,0x20,0x91,0x2f, /* "radio" */ 
	0x4,0x8a,0x32,0xa6,0xc5,0x90, /* "receiver" */ 
	0x24,0x51,0xad,0xee,0x4b,0x8e, /* "reckoning" */ 
	0x9,0x14,0x6f,0xb1,0x65,0x90, /* "recovery" */ 
	0x48,0xa6,0x2c,0x8a,0xe1,0x94, /* "reference" */ 
	0x12,0x2c,0x1f,0x2a, /* "report" */ 
	0x2,0x45,0x9d,0x3,0x2a, /* "restart" */ 
	0x2,0x4c,0x60, /* "rll" */ 
	0x24,0xfa,0x6,0x89,0x7b, /* "rotation" */ 
	0x81,0x30,0x98,0xa0, /* "safe" */ 
	0x98,0x69,0x30, /* "sats" */ 
	0x4c,0x41,0x98, /* "sbas" */ 
	0x26,0x2a,0xcc, /* "sbus" */ 
	0x13,0x2b,0xa6,0xf9, /* "sensor" */ 
	0x2,0x65,0x92,0x42,0xc9,0x60, /* "serialrx" */ 
	0x13,0x63,0xe0,0x50, /* "slope" */ 
	0x4d,0xa1,0x63, /* "small" */ 
	0x1,0x36,0x86,0x54,0x83,0xe5,0x40, /* "smartport" */ 
	0x4d,0xaf,0x7d,0x10,0xe2,0xce,0x60, /* "smoothness" */ 
	0x9b,0x83,0x8,0x25,0xc5,0x9c, /* "snappiness" */ 
	0xc1,0x37,0x86,0x49,0x71, /* "soaring" */ 
	0xc1,0x37,0xd6,0x43,0x28, /* "source" */ 
	0x27,0x4,0xba,0xb0, /* "spinup" */ 
	0x4,0xe4,0x30, /* "src" */ 
	0x4e,0x81,0x12,0x58,0x9a,0x64, /* "stability" */ 
	0x13,0xa0,0x69,0x59, /* "status" */ 
	0x82,0x74,0x48,0xd6, /* "stick" */ 
	0x9,0xd1,0xf0, /* "stop" */ 
	0x4,0xe9,0x20, /* "str" */ 
	0x4f,0x2e,0x18, /* "sync" */ 
	0x27,0x99,0xa4,0x80, /* "sysid" */ 
	0xa0,0x52,0xc0, /* "tail" */ 
	0x50,0x29,0x64,0xd3,0x4a,0x16,0x40, /* "tailsitter" */ 
	0xa2,0x24,0xfb, /* "throw" */ 
	0x82,0x89,0x69,0x64, /* "timer" */ 
	0xa,0x3d,0xc5, /* "tone" */ 
	0x5,0x24,0x17,0x4c, /* "trans" */ 
	0x14,0x92, /* "tri" */ 
	0x41,0x4a,0xc9,0xc0, /* "turn" */ 
	0xa6,0x5,0x53,0x18,0xb2, /* "txbuffer" */ 
	0x5,0x5c,0x19,0x34,0xa4, /* "unarmed" */ 
	0x5,0x60,0x40,0xd0,0xa0, /* "update" */ 
	0xac,0xc2,0x72, /* "usage" */ 
	0x82,0xb3,0x2c, /* "user" */ 
	0x81,0x62,0xb1,0xe3,0x4d,0x32, /* "velocity" */ 
	0xb,0x16,0x53,0x4b,0xdc, /* "version" */ 
	0xb,0x86,0x4e,0x4b,0x8e, /* "warning" */ 
	0xb,0xa5,0xc4,0x1b,0xdb,0x0, /* "windcomp" */ 
	0x5d,0x2e,0x25,0x60, /* "windup" */ 
	0x0,0x00
};
static const char wordSymbols[] = {'3','2','_','1',};
const char * const table_acc_hardware[] = {
	"NONE",
	"AUTO",
	"MPU6000",
	"MPU6500",
	"MPU9250",
	"BMI160",
	"ICM20689",
	"BMI088",
	"ICM42605",
	"BMI270",
	"LSM6DXX",
	"FAKE",
};
const char * const table_airmodeHandlingType[] = {
	"STICK_CENTER",
	"THROTTLE_THRESHOLD",
	"STICK_CENTER_ONCE",
};
const char * const table_alignment[] = {
	"DEFAULT",
	"CW0",
	"CW90",
	"CW180",
	"CW270",
	"CW0FLIP",
	"CW90FLIP",
	"CW180FLIP",
	"CW270FLIP",
};
const char * const table_aux_operator[] = {
	"OR",
	"AND",
};
const char * const table_baro_hardware[] = {
	"NONE",
	"AUTO",
	"BMP085",
	"MS5611",
	"BMP280",
	"MS5607",
	"LPS25H",
	"SPL06",
	"BMP388",
	"DPS310",
	"B2SMPB",
	"MSP",
	"FAKE",
};
const char * const table_bat_capacity_unit[] = {
	"MAH",
	"MWH",
};
const char * const table_bat_voltage_source[] = {
	"RAW",
	"SAG_COMP",
};
const char * const table_current_sensor[] = {
	"NONE",
	"ADC",
	"VIRTUAL",
	"FAKE",
	"ESC",
	"SMARTPORT",
	"CAN",
};
const char * const table_debug_modes[] = {
	"NONE",
	"AGL",
	"FLOW_RAW",
	"FLOW",
	"ALWAYS",
	"SAG_COMP_VOLTAGE",
	"VIBE",
	"CRUISE",
	"REM_FLIGHT_TIME",
	"SMARTAUDIO",
	"ACC",
	"NAV_YAW",
	"PCF8574",
	"DYN_GYRO_LPF",
	"AUTOLEVEL",
	"ALTITUDE",
	"AUTOTRIM",
	"AUTOTUNE",
	"RATE_DYNAMICS",
	"LANDING",
	"POS_EST",
	"ADAPTIVE_FILTER",
	"HEADTRACKER",
	"GPS",
	"LULU",
	"SBUS2",
};
const char * const table_default_altitude_source[] = {
	"GPS",
	"BARO",
	"GPS_ONLY",
	"BARO_ONLY",
};
const char * const table_direction[] = {
	"RIGHT",
	"LEFT",
	"YAW",
};
const char * const table_failsafe_procedure[] = {
	"LAND",
	"DROP",
	"RTH",
	"NONE",
};
const char * const table_filter_type[] = {
	"PT1",
	"BIQUAD",
};
const char * const table_filter_type_full[] = {
	"PT1",
	"BIQUAD",
	"PT2",
	"PT3",
	"LULU",
};
const char * const table_gps_auto_baud_max[] = {
	"115200",
	"57600",
	"38400",
	"19200",
	"9600",
	"230400",
	"460800",
	"921600",
};
const char * const table_gps_dyn_model[] = {
	"PEDESTRIAN",
	"AUTOMOTIVE",
	"AIR_1G",
	"AIR_2G",
	"AIR_4G",
	"SEA",
	"MOWER",
};
const char * const table_gps_provider[] = {
	"UBLOX",
	"MSP",
	"FAKE",
	"DRONECAN",
};
const char * const table_gps_sbas_mode[] = {
	"AUTO",
	"EGNOS",
	"WAAS",
	"MSAS",
	"GAGAN",
	"SPAN",
	"NONE",
};
const char * const table_gyro_filter_mode[] = {
	"OFF",
	"STATIC",
	"DYNAMIC",
	"ADAPTIVE",
};
const char * const table_headtracker_dev_type[] = {
	"NONE",
	"SERIAL",
	"MSP",
};
const char * const table_imu_inertia_comp_method[] = {
	"VELNED",
	"TURNRATE",
	"ADAPTIVE",
};
const char * const table_iterm_relax[] = {
	"OFF",
	"RP",
	"RPY",
};
const char * const table_led_pin_pwm_mode[] = {
	"SHARED_LOW",
	"SHARED_HIGH",
	"LOW",
	"HIGH",
};
const char * const table_ltm_rates[] = {
	"NORMAL",
	"MEDIUM",
	"SLOW",
};
const char * const table_mag_hardware[] = {
	"NONE",
	"AUTO",
	"HMC5883",
	"AK8975",
	"MAG3110",
	"AK8963",
	"IST8310",
	"QMC5883",
	"QMC5883P",
	"MPU9250",
	"IST8308",
	"LIS3MDL",
	"MSP",
	"RM3100",
	"VCM5883",
	"MLX90393",
	"FAKE",
};
const char * const table_mavlink_autopilot_type[] = {
	"GENERIC",
	"ARDUPILOT",
};
const char * const table_mavlink_radio_type[] = {
	"GENERIC",
	"ELRS",
	"SIK",
};
const char * const table_motor_pwm_protocol[] = {
	"STANDARD",
	"ONESHOT125",
	"MULTISHOT",
	"BRUSHED",
	"DSHOT150",
	"DSHOT300",
	"DSHOT600",
};
const char * const table_nav_extra_arming_safety[] = {
	"ON",
	"ALLOW_BYPASS",
};
const char * const table_nav_fw_wp_turn_smoothing[] = {
	"OFF",
	"ON",
	"ON-CUT",
};
const char * const table_nav_mc_althold_throttle[] = {
	"STICK",
	"MID_STICK",
	"HOVER",
};
const char * const table_nav_overrides_motor_stop[] = {
	"OFF_ALWAYS",
	"OFF",
	"AUTO_ONLY",
	"ALL_NAV",
};
const char * const table_nav_rth_allow_landing[] = {
	"NEVER",
	"ALWAYS",
	"FS_ONLY",
};
const char * const table_nav_rth_alt_mode[] = {
	"CURRENT",
	"EXTRA",
	"FIXED",
	"MAX",
	"AT_LEAST",
};
const char * const table_nav_rth_climb_first[] = {
	"OFF",
	"ON",
	"ON_FW_SPIRAL",
};
const char * const table_nav_rth_climb_first_stage_modes[] = {
	"AT_LEAST",
	"EXTRA",
};
const char * const table_nav_user_control_mode[] = {
	"ATTI",
	"CRUISE",
};
const char * const table_nav_wp_mission_restart[] = {
	"START",
	"RESUME",
	"SWITCH",
};
const char * const table_off_on[] = {
	"OFF",
	"ON",
};
const char * const table_pidTypeTable[] = {
	"NONE",
	"PID",
	"PIFF",
	"AUTO",
};
const char * const table_platform_type[] = {
	"MULTIROTOR",
	"AIRPLANE",
	"HELICOPTER",
	"TRICOPTER",
	"ROVER",
	"BOAT",
};
const char * const table_receiver_type[] = {
	"NONE",
	"SERIAL",
	"MSP",
	"SIM (SITL)",
};
const char * const table_reset_type[] = {
	"NEVER",
	"FIRST_ARM",
	"EACH_ARM",
};
const char * const table_rssi_source[] = {
	"NONE",
	"AUTO",
	"ADC",
	"CHANNEL",
	"PROTOCOL",
	"MSP",
};
const char * const table_rth_trackback_mode[] = {
	"OFF",
	"ON",
	"FS",
};
const char * const table_safehome_usage_mode[] = {
	"OFF",
	"RTH",
	"RTH_FS",
};
const char * const table_servo_protocol[] = {
	"PWM",
	"SBUS",
	"SBUS_PWM",
};
const char * const table_smartport_fuel_unit[] = {
	"PERCENT",
	"MAH",
	"MWH",
};
const char * const table_tristate[] = {
	"AUTO",
	"ON",
	"OFF",
};
const char * const table_tz_automatic_dst[] = {
	"OFF",
	"EU",
	"USA",
};
static const lookupTableEntry_t settingLookupTables[] = {
	{ table_acc_hardware, sizeof(table_acc_hardware) / sizeof(char*) },
	{ table_airmodeHandlingType, sizeof(table_airmodeHandlingType) / sizeof(char*) },
	{ table_alignment, sizeof(table_alignment) / sizeof(char*) },
	{ table_aux_operator, sizeof(table_aux_operator) / sizeof(char*) },
	{ table_baro_hardware, sizeof(table_baro_hardware) / sizeof(char*) },
	{ table_bat_capacity_unit, sizeof(table_bat_capacity_unit) / sizeof(char*) },
	{ table_bat_voltage_source, sizeof(table_bat_voltage_source) / sizeof(char*) },
	{ table_current_sensor, sizeof(table_current_sensor) / sizeof(char*) },
	{ table_debug_modes, sizeof(table_debug_modes) / sizeof(char*) },
	{ table_default_altitude_source, sizeof(table_default_altitude_source) / sizeof(char*) },
	{ table_direction, sizeof(table_direction) / sizeof(char*) },
	{ table_failsafe_procedure, sizeof(table_failsafe_procedure) / sizeof(char*) },
	{ table_filter_type, sizeof(table_filter_type) / sizeof(char*) },
	{ table_filter_type_full, sizeof(table_filter_type_full) / sizeof(char*) },
	{ table_gps_auto_baud_max, sizeof(table_gps_auto_baud_max) / sizeof(char*) },
	{ table_gps_dyn_model, sizeof(table_gps_dyn_model) / sizeof(char*) },
	{ table_gps_provider, sizeof(table_gps_provider) / sizeof(char*) },
	{ table_gps_sbas_mode, sizeof(table_gps_sbas_mode) / sizeof(char*) },
	{ table_gyro_filter_mode, sizeof(table_gyro_filter_mode) / sizeof(char*) },
	{ table_headtracker_dev_type, sizeof(table_headtracker_dev_type) / sizeof(char*) },
	{ table_imu_inertia_comp_method, sizeof(table_imu_inertia_comp_method) / sizeof(char*) },
	{ table_iterm_relax, sizeof(table_iterm_relax) / sizeof(char*) },
	{ table_led_pin_pwm_mode, sizeof(table_led_pin_pwm_mode) / sizeof(char*) },
	{ table_ltm_rates, sizeof(table_ltm_rates) / sizeof(char*) },
	{ table_mag_hardware, sizeof(table_mag_hardware) / sizeof(char*) },
	{ table_mavlink_autopilot_type, sizeof(table_mavlink_autopilot_type) / sizeof(char*) },
	{ table_mavlink_radio_type, sizeof(table_mavlink_radio_type) / sizeof(char*) },
	{ table_motor_pwm_protocol, sizeof(table_motor_pwm_protocol) / sizeof(char*) },
	{ table_nav_extra_arming_safety, sizeof(table_nav_extra_arming_safety) / sizeof(char*) },
	{ table_nav_fw_wp_turn_smoothing, sizeof(table_nav_fw_wp_turn_smoothing) / sizeof(char*) },
	{ table_nav_mc_althold_throttle, sizeof(table_nav_mc_althold_throttle) / sizeof(char*) },
	{ table_nav_overrides_motor_stop, sizeof(table_nav_overrides_motor_stop) / sizeof(char*) },
	{ table_nav_rth_allow_landing, sizeof(table_nav_rth_allow_landing) / sizeof(char*) },
	{ table_nav_rth_alt_mode, sizeof(table_nav_rth_alt_mode) / sizeof(char*) },
	{ table_nav_rth_climb_first, sizeof(table_nav_rth_climb_first) / sizeof(char*) },
	{ table_nav_rth_climb_first_stage_modes, sizeof(table_nav_rth_climb_first_stage_modes) / sizeof(char*) },
	{ table_nav_user_control_mode, sizeof(table_nav_user_control_mode) / sizeof(char*) },
	{ table_nav_wp_mission_restart, sizeof(table_nav_wp_mission_restart) / sizeof(char*) },
	{ table_off_on, sizeof(table_off_on) / sizeof(char*) },
	{ table_pidTypeTable, sizeof(table_pidTypeTable) / sizeof(char*) },
	{ table_platform_type, sizeof(table_platform_type) / sizeof(char*) },
	{ table_receiver_type, sizeof(table_receiver_type) / sizeof(char*) },
	{ table_reset_type, sizeof(table_reset_type) / sizeof(char*) },
	{ table_rssi_source, sizeof(table_rssi_source) / sizeof(char*) },
	{ table_rth_trackback_mode, sizeof(table_rth_trackback_mode) / sizeof(char*) },
	{ table_safehome_usage_mode, sizeof(table_safehome_usage_mode) / sizeof(char*) },
	{ table_servo_protocol, sizeof(table_servo_protocol) / sizeof(char*) },
	{ table_smartport_fuel_unit, sizeof(table_smartport_fuel_unit) / sizeof(char*) },
	{ table_tristate, sizeof(table_tristate) / sizeof(char*) },
	{ table_tz_automatic_dst, sizeof(table_tz_automatic_dst) / sizeof(char*) },
};
static const uint32_t settingMinMaxTable[] = {
	0,
	255,
	100,
	1000,
	2000,
	10,
	200,
	1,
	32767,
	-32768,
	5,
	500,
	50,
	2,
	15,
	5000,
	10000,
	65000,
	-1800,
	3600,
	65535,
	20,
	180,
	250,
	32,
	80,
	60000,
	4294967295,
	-5000,
	-500,
	4,
	30,
	90,
	120,
	300,
	900,
	8192,
	-800,
	-50,
	-1,
	9,
	16,
	25,
	40,
	45,
	51,
	400,
	450,
	750,
	800,
	2250,
	9999,
	500000,
	-18000,
	-10000,
	-1000,
	-720,
	-20,
	-16,
	-10,
	3,
	6,
	34,
	60,
	99,
	175,
	498,
	600,
	840,
	1350,
	1500,
	1800,
	2500,
	4000,
	6000,
	9000,
	18000,
	20000,
	30000,
	32000,
};
typedef uint8_t setting_min_max_idx_t;
#define SETTING_INDEXES_GET_MIN(val) (val->config.minmax.indexes[0])
#define SETTING_INDEXES_GET_MAX(val) (val->config.minmax.indexes[1])
static const setting_t settingsTable[] = {
	// PG_GYRO_CONFIG
	{ {255, 1, 0, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 75}, (setting_offset_t)offsetof(gyroConfig_t, looptime) },
	{ {241, 1, 0, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 3}, (setting_offset_t)offsetof(gyroConfig_t, gyro_anti_aliasing_lpf_hz) },
	{ {30, 129, 2, 97, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(gyroConfig_t, gyroLuluEnabled) },
	{ {242, 1, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {7, 14}, (setting_offset_t)offsetof(gyroConfig_t, gyroLuluSampleCount) },
	{ {30, 130, 2, 24, 23, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 11}, (setting_offset_t)offsetof(gyroConfig_t, gyro_main_lpf_hz) },
	{ {30, 60, 37, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_GYRO_FILTER_MODE }, (setting_offset_t)offsetof(gyroConfig_t, gyroFilterMode) },
	{ {30, 78, 24, 15, 23, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {43, 46}, (setting_offset_t)offsetof(gyroConfig_t, gyroDynamicLpfMinHz) },
	{ {30, 78, 24, 14, 23, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {43, 3}, (setting_offset_t)offsetof(gyroConfig_t, gyroDynamicLpfMaxHz) },
	{ {30, 78, 24, 199, 1, 40}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {7, 5}, (setting_offset_t)offsetof(gyroConfig_t, gyroDynamicLpfCurveExpo) },
	{ {249, 1, 30, 94, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(gyroConfig_t, init_gyro_cal_enabled) },
	{ {30, 120, 68, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {9, 8}, (setting_offset_t)offsetof(gyroConfig_t, gyro_zero_cal[X]) },
	{ {30, 120, 69, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {9, 8}, (setting_offset_t)offsetof(gyroConfig_t, gyro_zero_cal[Y]) },
	{ {30, 120, 9, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {9, 8}, (setting_offset_t)offsetof(gyroConfig_t, gyro_zero_cal[Z]) },
	{ {250, 1, 137, 1, 193, 1}, VAR_FLOAT | MASTER_VALUE, .config.minmax.indexes = {0, 4}, (setting_offset_t)offsetof(gyroConfig_t, gravity_cmss_cal) },
	// PG_ACCELEROMETER_CONFIG
	{ {33, 149, 1, 23, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(accelerometerConfig_t, acc_notch_hz) },
	{ {33, 149, 1, 127, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {7, 1}, (setting_offset_t)offsetof(accelerometerConfig_t, acc_notch_cutoff) },
	{ {33, 98, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_ACC_HARDWARE }, (setting_offset_t)offsetof(accelerometerConfig_t, acc_hardware) },
	{ {33, 24, 23, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 6}, (setting_offset_t)offsetof(accelerometerConfig_t, acc_lpf_hz) },
	{ {33, 24, 25, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_FILTER_TYPE }, (setting_offset_t)offsetof(accelerometerConfig_t, acc_soft_lpf_type) },
	{ {33, 163, 1, 126, 0, 0}, VAR_FLOAT | MASTER_VALUE, .config.minmax.indexes = {38, 45}, (setting_offset_t)offsetof(accelerometerConfig_t, acc_temp_correction) },
	{ {91, 68, 0, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {9, 8}, (setting_offset_t)offsetof(accelerometerConfig_t, accZero.raw[X]) },
	{ {91, 69, 0, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {9, 8}, (setting_offset_t)offsetof(accelerometerConfig_t, accZero.raw[Y]) },
	{ {91, 9, 0, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {9, 8}, (setting_offset_t)offsetof(accelerometerConfig_t, accZero.raw[Z]) },
	{ {90, 68, 0, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {7, 36}, (setting_offset_t)offsetof(accelerometerConfig_t, accGain.raw[X]) },
	{ {90, 69, 0, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {7, 36}, (setting_offset_t)offsetof(accelerometerConfig_t, accGain.raw[Y]) },
	{ {90, 9, 0, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {7, 36}, (setting_offset_t)offsetof(accelerometerConfig_t, accGain.raw[Z]) },
	// PG_COMPASS_CONFIG
	{ {43, 31, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_ALIGNMENT }, (setting_offset_t)offsetof(compassConfig_t, mag_align) },
	{ {31, 98, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_MAG_HARDWARE }, (setting_offset_t)offsetof(compassConfig_t, mag_hardware) },
	{ {31, 205, 1, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {53, 76}, (setting_offset_t)offsetof(compassConfig_t, mag_declination) },
	{ {105, 68, 0, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {9, 8}, (setting_offset_t)offsetof(compassConfig_t, magZero.raw[X]) },
	{ {105, 69, 0, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {9, 8}, (setting_offset_t)offsetof(compassConfig_t, magZero.raw[Y]) },
	{ {105, 9, 0, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {9, 8}, (setting_offset_t)offsetof(compassConfig_t, magZero.raw[Z]) },
	{ {104, 68, 0, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {9, 8}, (setting_offset_t)offsetof(compassConfig_t, magGain[X]) },
	{ {104, 69, 0, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {9, 8}, (setting_offset_t)offsetof(compassConfig_t, magGain[Y]) },
	{ {104, 9, 0, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {9, 8}, (setting_offset_t)offsetof(compassConfig_t, magGain[Z]) },
	{ {31, 189, 1, 49, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {21, 33}, (setting_offset_t)offsetof(compassConfig_t, magCalibrationTimeLimit) },
	{ {43, 31, 10, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {18, 19}, (setting_offset_t)offsetof(compassConfig_t, rollDeciDegrees) },
	{ {43, 31, 8, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {18, 19}, (setting_offset_t)offsetof(compassConfig_t, pitchDeciDegrees) },
	{ {43, 31, 5, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {18, 19}, (setting_offset_t)offsetof(compassConfig_t, yawDeciDegrees) },
	// PG_BAROMETER_CONFIG
	{ {53, 98, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_BARO_HARDWARE }, (setting_offset_t)offsetof(barometerConfig_t, baro_hardware) },
	{ {53, 94, 164, 1, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 3}, (setting_offset_t)offsetof(barometerConfig_t, baro_calibration_tolerance) },
	{ {53, 163, 1, 126, 0, 0}, VAR_FLOAT | MASTER_VALUE, .config.minmax.indexes = {38, 45}, (setting_offset_t)offsetof(barometerConfig_t, baro_temp_correction) },
	// PG_RX_CONFIG
	{ {173, 2, 25, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_RECEIVER_TYPE }, (setting_offset_t)offsetof(rxConfig_t, receiverType) },
	{ {15, 125, 0, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {3, 4}, (setting_offset_t)offsetof(rxConfig_t, mincheck) },
	{ {14, 125, 0, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {3, 4}, (setting_offset_t)offsetof(rxConfig_t, maxcheck) },
	{ {83, 193, 2, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_RSSI_SOURCE }, (setting_offset_t)offsetof(rxConfig_t, rssi_source) },
	{ {83, 74, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 62}, (setting_offset_t)offsetof(rxConfig_t, rssi_channel) },
	{ {83, 15, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(rxConfig_t, rssiMin) },
	{ {83, 14, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(rxConfig_t, rssiMax) },
	{ {184, 2, 201, 2, 251, 1}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {11, 16}, (setting_offset_t)offsetof(rxConfig_t, sbusSyncInterval) },
	{ {42, 60, 24, 23, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {14, 23}, (setting_offset_t)offsetof(rxConfig_t, rcFilterFrequency) },
	{ {42, 60, 35, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(rxConfig_t, autoSmooth) },
	{ {42, 60, 116, 221, 1, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {7, 2}, (setting_offset_t)offsetof(rxConfig_t, autoSmoothFactor) },
	{ {159, 1, 15, 168, 1, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {48, 50}, (setting_offset_t)offsetof(rxConfig_t, rx_min_usec) },
	{ {159, 1, 14, 168, 1, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {48, 50}, (setting_offset_t)offsetof(rxConfig_t, rx_max_usec) },
	{ {186, 2, 138, 1, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_TRISTATE }, (setting_offset_t)offsetof(rxConfig_t, halfDuplex) },
	// PG_MOTOR_CONFIG
	{ {15, 194, 1, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 4}, (setting_offset_t)offsetof(motorConfig_t, mincommand) },
	{ {48, 65, 4, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {12, 79}, (setting_offset_t)offsetof(motorConfig_t, motorPwmRate) },
	{ {48, 65, 154, 1, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_MOTOR_PWM_PROTOCOL }, (setting_offset_t)offsetof(motorConfig_t, motorPwmProtocol) },
	{ {48, 166, 2, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {30, 1}, (setting_offset_t)offsetof(motorConfig_t, motorPoleCount) },
	// PG_FAILSAFE_CONFIG
	{ {18, 28, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 6}, (setting_offset_t)offsetof(failsafeConfig_t, failsafe_delay) },
	{ {18, 175, 2, 28, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 6}, (setting_offset_t)offsetof(failsafeConfig_t, failsafe_recovery_delay) },
	{ {18, 156, 2, 28, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 6}, (setting_offset_t)offsetof(failsafeConfig_t, failsafe_off_delay) },
	{ {18, 32, 103, 28, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 34}, (setting_offset_t)offsetof(failsafeConfig_t, failsafe_throttle_low_delay) },
	{ {18, 152, 1, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_FAILSAFE_PROCEDURE }, (setting_offset_t)offsetof(failsafeConfig_t, failsafe_procedure) },
	{ {18, 198, 2, 66, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 11}, (setting_offset_t)offsetof(failsafeConfig_t, failsafe_stick_motion_threshold) },
	{ {18, 2, 10, 22, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {37, 49}, (setting_offset_t)offsetof(failsafeConfig_t, failsafe_fw_roll_angle) },
	{ {18, 2, 8, 22, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {37, 49}, (setting_offset_t)offsetof(failsafeConfig_t, failsafe_fw_pitch_angle) },
	{ {18, 2, 5, 4, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {55, 3}, (setting_offset_t)offsetof(failsafeConfig_t, failsafe_fw_yaw_rate) },
	{ {18, 15, 54, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 17}, (setting_offset_t)offsetof(failsafeConfig_t, failsafe_min_distance) },
	{ {18, 15, 54, 152, 1, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_FAILSAFE_PROCEDURE }, (setting_offset_t)offsetof(failsafeConfig_t, failsafe_min_distance_procedure) },
	{ {18, 107, 28, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {39, 67}, (setting_offset_t)offsetof(failsafeConfig_t, failsafe_mission_delay) },
	// PG_BOARD_ALIGNMENT
	{ {43, 93, 10, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {18, 19}, (setting_offset_t)offsetof(boardAlignment_t, rollDeciDegrees) },
	{ {43, 93, 8, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {18, 19}, (setting_offset_t)offsetof(boardAlignment_t, pitchDeciDegrees) },
	{ {43, 93, 5, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {18, 19}, (setting_offset_t)offsetof(boardAlignment_t, yawDeciDegrees) },
	// PG_BATTERY_METERS_CONFIG
	{ {71, 72, 167, 1, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_BAT_CAPACITY_UNIT }, (setting_offset_t)offsetof(batteryMetersConfig_t, capacity_unit) },
	{ {96, 106, 161, 1, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {54, 16}, (setting_offset_t)offsetof(batteryMetersConfig_t, current.scale) },
	{ {96, 106, 81, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {9, 8}, (setting_offset_t)offsetof(batteryMetersConfig_t, current.offset) },
	{ {96, 106, 25, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_CURRENT_SENSOR }, (setting_offset_t)offsetof(batteryMetersConfig_t, current.type) },
	{ {183, 1, 169, 1, 195, 2}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_BAT_VOLTAGE_SOURCE }, (setting_offset_t)offsetof(batteryMetersConfig_t, voltageSource) },
	{ {75, 151, 1, 0, 0, 0}, VAR_UINT32 | MASTER_VALUE, .config.minmax.indexes = {0, 27}, (setting_offset_t)offsetof(batteryMetersConfig_t, cruise_power) },
	{ {80, 151, 1, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 20}, (setting_offset_t)offsetof(batteryMetersConfig_t, idle_power) },
	{ {16, 214, 1, 131, 2, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(batteryMetersConfig_t, rth_energy_margin) },
	{ {38, 95, 171, 1, 0, 0}, VAR_FLOAT | MASTER_VALUE, .config.minmax.indexes = {0, 13}, (setting_offset_t)offsetof(batteryMetersConfig_t, throttle_compensation_weight) },
	// PG_BATTERY_PROFILES
	{ {71, 72, 0, 0, 0, 0}, VAR_UINT32 | BATTERY_CONFIG_VALUE, .config.minmax.indexes = {0, 27}, (setting_offset_t)offsetof(batteryProfile_t, capacity.value) },
	{ {71, 72, 218, 2, 0, 0}, VAR_UINT32 | BATTERY_CONFIG_VALUE, .config.minmax.indexes = {0, 27}, (setting_offset_t)offsetof(batteryProfile_t, capacity.warning) },
	{ {71, 72, 198, 1, 0, 0}, VAR_UINT32 | BATTERY_CONFIG_VALUE, .config.minmax.indexes = {0, 27}, (setting_offset_t)offsetof(batteryProfile_t, capacity.critical) },
	{ {57, 45, 153, 1, 0, 0}, VAR_UINT8 | BATTERY_CONFIG_VALUE, .config.minmax.indexes = {0, 60}, (setting_offset_t)offsetof(batteryProfile_t, controlProfile) },
	{ {32, 161, 1, 0, 0, 0}, VAR_FLOAT | BATTERY_CONFIG_VALUE, .config.minmax.indexes = {0, 7}, (setting_offset_t)offsetof(batteryProfile_t, motor.throttleScale) },
	{ {32, 80, 0, 0, 0, 0}, VAR_FLOAT | BATTERY_CONFIG_VALUE, .config.minmax.indexes = {0, 31}, (setting_offset_t)offsetof(batteryProfile_t, motor.throttleIdle) },
	{ {18, 32, 0, 0, 0, 0}, VAR_UINT16 | BATTERY_CONFIG_VALUE, .config.minmax.indexes = {3, 4}, (setting_offset_t)offsetof(batteryProfile_t, failsafe_throttle) },
	{ {1, 3, 246, 1, 38, 0}, VAR_UINT16 | BATTERY_CONFIG_VALUE, .config.minmax.indexes = {3, 4}, (setting_offset_t)offsetof(batteryProfile_t, nav.mc.hover_throttle) },
	{ {1, 2, 75, 38, 0, 0}, VAR_UINT16 | BATTERY_CONFIG_VALUE, .config.minmax.indexes = {3, 4}, (setting_offset_t)offsetof(batteryProfile_t, nav.fw.cruise_throttle) },
	{ {1, 2, 15, 38, 0, 0}, VAR_UINT16 | BATTERY_CONFIG_VALUE, .config.minmax.indexes = {3, 4}, (setting_offset_t)offsetof(batteryProfile_t, nav.fw.min_throttle) },
	{ {1, 2, 14, 38, 0, 0}, VAR_UINT16 | BATTERY_CONFIG_VALUE, .config.minmax.indexes = {3, 4}, (setting_offset_t)offsetof(batteryProfile_t, nav.fw.max_throttle) },
	{ {1, 2, 113, 0, 0, 0}, VAR_UINT8 | BATTERY_CONFIG_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(batteryProfile_t, nav.fw.pitch_to_throttle) },
	{ {1, 2, 12, 38, 0, 0}, VAR_UINT16 | BATTERY_CONFIG_VALUE, .config.minmax.indexes = {3, 4}, (setting_offset_t)offsetof(batteryProfile_t, nav.fw.launch_throttle) },
	{ {1, 2, 12, 80, 38, 0}, VAR_UINT16 | BATTERY_CONFIG_VALUE, .config.minmax.indexes = {3, 4}, (setting_offset_t)offsetof(batteryProfile_t, nav.fw.launch_idle_throttle) },
	// PG_MIXER_PROFILE
	{ {48, 129, 1, 141, 1, 0}, VAR_UINT8 | MIXER_CONFIG_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(mixerProfile_t, mixer_config.motorDirectionInverted) },
	{ {165, 2, 25, 0, 0, 0}, VAR_UINT8 | MIXER_CONFIG_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_PLATFORM_TYPE }, (setting_offset_t)offsetof(mixerProfile_t, mixer_config.platformType) },
	{ {243, 1, 224, 1, 0, 0}, VAR_UINT8 | MIXER_CONFIG_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(mixerProfile_t, mixer_config.hasFlaps) },
	{ {147, 1, 169, 2, 25, 0}, VAR_INT16 | MIXER_CONFIG_VALUE, .config.minmax.indexes = {39, 8}, (setting_offset_t)offsetof(mixerProfile_t, mixer_config.appliedMixerPreset) },
	{ {136, 2, 111, 103, 0, 0}, VAR_UINT8 | MIXER_CONFIG_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(mixerProfile_t, mixer_config.motorstopOnLow) },
	{ {108, 45, 153, 1, 253, 1}, VAR_UINT8 | MIXER_CONFIG_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(mixerProfile_t, mixer_config.controlProfileLinking) },
	{ {108, 178, 1, 84, 0, 0}, VAR_UINT8 | MIXER_CONFIG_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(mixerProfile_t, mixer_config.automated_switch) },
	{ {108, 84, 208, 2, 206, 2}, VAR_INT16 | MIXER_CONFIG_VALUE, .config.minmax.indexes = {0, 6}, (setting_offset_t)offsetof(mixerProfile_t, mixer_config.switchTransitionTimer) },
	{ {204, 2, 157, 2, 81, 0}, VAR_UINT8 | MIXER_CONFIG_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(mixerProfile_t, mixer_config.tailsitterOrientationOffset) },
	{ {119, 64, 109, 110, 10, 0}, VAR_INT16 | MIXER_CONFIG_VALUE, .config.minmax.indexes = {28, 15}, (setting_offset_t)offsetof(mixerProfile_t, mixer_config.transition_PID_mmix_multiplier_roll) },
	{ {119, 64, 109, 110, 8, 0}, VAR_INT16 | MIXER_CONFIG_VALUE, .config.minmax.indexes = {28, 15}, (setting_offset_t)offsetof(mixerProfile_t, mixer_config.transition_PID_mmix_multiplier_pitch) },
	{ {119, 64, 109, 110, 5, 0}, VAR_INT16 | MIXER_CONFIG_VALUE, .config.minmax.indexes = {28, 15}, (setting_offset_t)offsetof(mixerProfile_t, mixer_config.transition_PID_mmix_multiplier_yaw) },
	// PG_REVERSIBLE_MOTORS_CONFIG
	{ {70, 27, 103, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {3, 4}, (setting_offset_t)offsetof(reversibleMotorsConfig_t, deadband_low) },
	{ {70, 27, 244, 1, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {3, 4}, (setting_offset_t)offsetof(reversibleMotorsConfig_t, deadband_high) },
	{ {70, 155, 2, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {3, 4}, (setting_offset_t)offsetof(reversibleMotorsConfig_t, neutral) },
	// PG_SERVO_CONFIG
	{ {55, 154, 1, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_SERVO_PROTOCOL }, (setting_offset_t)offsetof(servoConfig_t, servo_protocol) },
	{ {55, 191, 1, 171, 2, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {3, 4}, (setting_offset_t)offsetof(servoConfig_t, servoCenterPulse) },
	{ {55, 65, 4, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {12, 66}, (setting_offset_t)offsetof(servoConfig_t, servoPwmRate) },
	{ {55, 24, 23, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {0, 46}, (setting_offset_t)offsetof(servoConfig_t, servo_lowpass_freq) },
	{ {223, 1, 205, 2, 81, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {12, 47}, (setting_offset_t)offsetof(servoConfig_t, flaperon_throw_offset) },
	{ {209, 2, 212, 2, 55, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(servoConfig_t, tri_unarmed_servo) },
	{ {55, 181, 1, 180, 2, 63}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {7, 63}, (setting_offset_t)offsetof(servoConfig_t, servo_autotrim_rotation_limit) },
	// PG_CONTROL_PROFILES
	{ {38, 133, 2, 0, 0, 0}, VAR_UINT8 | CONTROL_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(controlConfig_t, throttle.rcMid8) },
	{ {38, 40, 0, 0, 0, 0}, VAR_UINT8 | CONTROL_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(controlConfig_t, throttle.rcExpo8) },
	{ {176, 1, 167, 2, 0, 0}, VAR_UINT16 | CONTROL_VALUE, .config.minmax.indexes = {0, 6}, (setting_offset_t)offsetof(controlConfig_t, throttle.apa_pow) },
	{ {67, 4, 0, 0, 0, 0}, VAR_UINT8 | CONTROL_VALUE, .config.minmax.indexes = {0, 6}, (setting_offset_t)offsetof(controlConfig_t, throttle.dynPID) },
	{ {67, 187, 1, 0, 0, 0}, VAR_UINT16 | CONTROL_VALUE, .config.minmax.indexes = {3, 4}, (setting_offset_t)offsetof(controlConfig_t, throttle.pa_breakpoint) },
	{ {67, 8, 195, 1, 0, 0}, VAR_UINT8 | CONTROL_VALUE, .config.minmax.indexes = {0, 21}, (setting_offset_t)offsetof(controlConfig_t, throttle.tpa_pitch_compensation) },
	{ {67, 111, 5, 0, 0, 0}, VAR_UINT8 | CONTROL_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(controlConfig_t, throttle.dynPID_on_YAW) },
	{ {2, 67, 49, 197, 1, 0}, VAR_UINT16 | CONTROL_VALUE, .config.minmax.indexes = {0, 15}, (setting_offset_t)offsetof(controlConfig_t, throttle.fixedWingTauMs) },
	{ {42, 40, 0, 0, 0, 0}, VAR_UINT8 | CONTROL_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(controlConfig_t, stabilized.rcExpo8) },
	{ {42, 5, 40, 0, 0, 0}, VAR_UINT8 | CONTROL_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(controlConfig_t, stabilized.rcYawExpo8) },
	{ {10, 4, 0, 0, 0, 0}, VAR_UINT8 | CONTROL_VALUE, .config.minmax.indexes = {30, 22}, (setting_offset_t)offsetof(controlConfig_t, stabilized.rates[FD_ROLL]) },
	{ {8, 4, 0, 0, 0, 0}, VAR_UINT8 | CONTROL_VALUE, .config.minmax.indexes = {30, 22}, (setting_offset_t)offsetof(controlConfig_t, stabilized.rates[FD_PITCH]) },
	{ {5, 4, 0, 0, 0, 0}, VAR_UINT8 | CONTROL_VALUE, .config.minmax.indexes = {7, 22}, (setting_offset_t)offsetof(controlConfig_t, stabilized.rates[FD_YAW]) },
	{ {36, 42, 40, 0, 0, 0}, VAR_UINT8 | CONTROL_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(controlConfig_t, manual.rcExpo8) },
	{ {36, 42, 5, 40, 0, 0}, VAR_UINT8 | CONTROL_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(controlConfig_t, manual.rcYawExpo8) },
	{ {36, 10, 4, 0, 0, 0}, VAR_UINT8 | CONTROL_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(controlConfig_t, manual.rates[FD_ROLL]) },
	{ {36, 8, 4, 0, 0, 0}, VAR_UINT8 | CONTROL_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(controlConfig_t, manual.rates[FD_PITCH]) },
	{ {36, 5, 4, 0, 0, 0}, VAR_UINT8 | CONTROL_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(controlConfig_t, manual.rates[FD_YAW]) },
	{ {225, 1, 134, 2, 208, 1}, VAR_UINT8 | CONTROL_VALUE, .config.minmax.indexes = {0, 12}, (setting_offset_t)offsetof(controlConfig_t, misc.fpvCamAngleDegrees) },
	// PG_IMU_CONFIG
	{ {34, 76, 143, 1, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 20}, (setting_offset_t)offsetof(imuConfig_t, dcm_kp_acc) },
	{ {34, 76, 142, 1, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 20}, (setting_offset_t)offsetof(imuConfig_t, dcm_ki_acc) },
	{ {34, 76, 143, 1, 31, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 20}, (setting_offset_t)offsetof(imuConfig_t, dcm_kp_mag) },
	{ {34, 76, 142, 1, 31, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 20}, (setting_offset_t)offsetof(imuConfig_t, dcm_ki_mag) },
	{ {188, 2, 22, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 22}, (setting_offset_t)offsetof(imuConfig_t, small_angle) },
	{ {34, 33, 102, 4, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 31}, (setting_offset_t)offsetof(imuConfig_t, acc_ignore_rate) },
	{ {34, 33, 102, 187, 2, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 5}, (setting_offset_t)offsetof(imuConfig_t, acc_ignore_slope) },
	{ {34, 11, 5, 219, 2, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(imuConfig_t, gps_yaw_windcomp) },
	{ {34, 248, 1, 95, 132, 2}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_IMU_INERTIA_COMP_METHOD }, (setting_offset_t)offsetof(imuConfig_t, inertia_comp_method) },
	{ {34, 11, 5, 171, 1, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 11}, (setting_offset_t)offsetof(imuConfig_t, gps_yaw_weight) },
	// PG_ARMING_CONFIG
	{ {222, 1, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(armingConfig_t, fixed_wing_auto_arm) },
	{ {77, 175, 1, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(armingConfig_t, disarm_always) },
	{ {84, 77, 28, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 3}, (setting_offset_t)offsetof(armingConfig_t, switchDisarmDelayMs) },
	{ {168, 2, 118, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 16}, (setting_offset_t)offsetof(armingConfig_t, prearmTimeoutMs) },
	// PG_GENERAL_SETTINGS
	{ {177, 1, 207, 1, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 64}, (setting_offset_t)offsetof(generalSettings_t, appliedDefaults) },
	// PG_EZ_TUNE
	{ {29, 97, 0, 0, 0, 0}, VAR_UINT8 | EZ_TUNE_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(ezTuneSettings_t, enabled) },
	{ {29, 60, 23, 0, 0, 0}, VAR_UINT16 | EZ_TUNE_VALUE, .config.minmax.indexes = {21, 34}, (setting_offset_t)offsetof(ezTuneSettings_t, filterHz) },
	{ {29, 182, 1, 82, 0, 0}, VAR_UINT8 | EZ_TUNE_VALUE, .config.minmax.indexes = {42, 65}, (setting_offset_t)offsetof(ezTuneSettings_t, axisRatio) },
	{ {29, 158, 1, 0, 0, 0}, VAR_UINT8 | EZ_TUNE_VALUE, .config.minmax.indexes = {0, 6}, (setting_offset_t)offsetof(ezTuneSettings_t, response) },
	{ {29, 200, 1, 0, 0, 0}, VAR_UINT8 | EZ_TUNE_VALUE, .config.minmax.indexes = {0, 6}, (setting_offset_t)offsetof(ezTuneSettings_t, damping) },
	{ {29, 196, 2, 0, 0, 0}, VAR_UINT8 | EZ_TUNE_VALUE, .config.minmax.indexes = {0, 6}, (setting_offset_t)offsetof(ezTuneSettings_t, stability) },
	{ {29, 172, 1, 0, 0, 0}, VAR_UINT8 | EZ_TUNE_VALUE, .config.minmax.indexes = {0, 6}, (setting_offset_t)offsetof(ezTuneSettings_t, aggressiveness) },
	{ {29, 4, 0, 0, 0, 0}, VAR_UINT8 | EZ_TUNE_VALUE, .config.minmax.indexes = {0, 6}, (setting_offset_t)offsetof(ezTuneSettings_t, rate) },
	{ {29, 40, 0, 0, 0, 0}, VAR_UINT8 | EZ_TUNE_VALUE, .config.minmax.indexes = {0, 6}, (setting_offset_t)offsetof(ezTuneSettings_t, expo) },
	{ {29, 191, 2, 0, 0, 0}, VAR_UINT8 | EZ_TUNE_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(ezTuneSettings_t, snappiness) },
	// PG_GPS_CONFIG
	{ {11, 170, 2, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_GPS_PROVIDER }, (setting_offset_t)offsetof(gpsConfig_t, provider) },
	{ {11, 183, 2, 37, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_GPS_SBAS_MODE }, (setting_offset_t)offsetof(gpsConfig_t, sbasMode) },
	{ {11, 78, 147, 1, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_GPS_DYN_MODEL }, (setting_offset_t)offsetof(gpsConfig_t, dynModel) },
	{ {11, 35, 196, 1, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(gpsConfig_t, autoConfig) },
	{ {11, 35, 184, 1, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(gpsConfig_t, autoBaud) },
	{ {239, 1, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_GPS_AUTO_BAUD_MAX }, (setting_offset_t)offsetof(gpsConfig_t, autoBaudMax) },
	{ {11, 88, 57, 236, 1, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(gpsConfig_t, ubloxUseGalileo) },
	{ {11, 88, 57, 185, 1, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(gpsConfig_t, ubloxUseBeidou) },
	{ {11, 88, 57, 238, 1, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(gpsConfig_t, ubloxUseGlonass) },
	{ {11, 15, 182, 2, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {10, 5}, (setting_offset_t)offsetof(gpsConfig_t, gpsMinSats) },
	{ {11, 88, 1, 23, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {10, 6}, (setting_offset_t)offsetof(gpsConfig_t, ubloxNavHz) },
	// PG_RC_CONTROLS_CONFIG
	{ {27, 0, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 24}, (setting_offset_t)offsetof(rcControlsConfig_t, deadband) },
	{ {5, 27, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(rcControlsConfig_t, yaw_deadband) },
	{ {13, 101, 27, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {13, 23}, (setting_offset_t)offsetof(rcControlsConfig_t, pos_hold_deadband) },
	{ {52, 101, 27, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {5, 23}, (setting_offset_t)offsetof(rcControlsConfig_t, alt_hold_deadband) },
	{ {70, 27, 32, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 6}, (setting_offset_t)offsetof(rcControlsConfig_t, mid_throttle_deadband) },
	{ {122, 25, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_AIRMODEHANDLINGTYPE }, (setting_offset_t)offsetof(rcControlsConfig_t, airmodeHandlingType) },
	{ {122, 32, 66, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {3, 4}, (setting_offset_t)offsetof(rcControlsConfig_t, airmodeThrottleThreshold) },
	// PG_PID_PROFILE
	{ {3, 7, 8, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_PITCH].P) },
	{ {3, 19, 8, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_PITCH].I) },
	{ {3, 17, 8, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_PITCH].D) },
	{ {3, 73, 8, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_PITCH].FF) },
	{ {3, 7, 10, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_ROLL].P) },
	{ {3, 19, 10, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_ROLL].I) },
	{ {3, 17, 10, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_ROLL].D) },
	{ {3, 73, 10, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_ROLL].FF) },
	{ {3, 7, 5, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_YAW].P) },
	{ {3, 19, 5, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_YAW].I) },
	{ {3, 17, 5, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_YAW].D) },
	{ {3, 73, 5, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_YAW].FF) },
	{ {3, 7, 41, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_LEVEL].P) },
	{ {3, 19, 41, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_LEVEL].I) },
	{ {3, 17, 41, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_LEVEL].D) },
	{ {2, 7, 8, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_PITCH].P) },
	{ {2, 19, 8, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_PITCH].I) },
	{ {2, 17, 8, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_PITCH].D) },
	{ {2, 59, 8, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_PITCH].FF) },
	{ {2, 7, 10, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_ROLL].P) },
	{ {2, 19, 10, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_ROLL].I) },
	{ {2, 17, 10, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_ROLL].D) },
	{ {2, 59, 10, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_ROLL].FF) },
	{ {2, 7, 5, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_YAW].P) },
	{ {2, 19, 5, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_YAW].I) },
	{ {2, 17, 5, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_YAW].D) },
	{ {2, 59, 5, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_YAW].FF) },
	{ {2, 7, 41, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_LEVEL].P) },
	{ {2, 19, 41, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_LEVEL].I) },
	{ {2, 17, 41, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_LEVEL].D) },
	{ {14, 22, 140, 1, 179, 2}, VAR_INT16 | PROFILE_VALUE, .config.minmax.indexes = {2, 35}, (setting_offset_t)offsetof(pidProfile_t, max_angle_inclination[FD_ROLL]) },
	{ {14, 22, 140, 1, 163, 2}, VAR_INT16 | PROFILE_VALUE, .config.minmax.indexes = {2, 35}, (setting_offset_t)offsetof(pidProfile_t, max_angle_inclination[FD_PITCH]) },
	{ {132, 1, 24, 23, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 11}, (setting_offset_t)offsetof(pidProfile_t, dterm_lpf_hz) },
	{ {132, 1, 24, 25, 0, 0}, VAR_UINT8 | PROFILE_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_FILTER_TYPE_FULL }, (setting_offset_t)offsetof(pidProfile_t, dterm_lpf_type) },
	{ {5, 24, 23, 0, 0, 0}, VAR_UINT8 | PROFILE_VALUE, .config.minmax.indexes = {0, 6}, (setting_offset_t)offsetof(pidProfile_t, yaw_lpf_hz) },
	{ {2, 176, 2, 173, 1, 0}, VAR_FLOAT | PROFILE_VALUE, .config.minmax.indexes = {34, 74}, (setting_offset_t)offsetof(pidProfile_t, fixedWingReferenceAirspeed) },
	{ {233, 1, 0, 0, 0, 0}, VAR_FLOAT | PROFILE_VALUE, .config.minmax.indexes = {0, 13}, (setting_offset_t)offsetof(pidProfile_t, fixedWingCoordinatedYawGain) },
	{ {232, 1, 0, 0, 0, 0}, VAR_FLOAT | PROFILE_VALUE, .config.minmax.indexes = {0, 13}, (setting_offset_t)offsetof(pidProfile_t, fixedWingCoordinatedPitchGain) },
	{ {234, 1, 0, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 32}, (setting_offset_t)offsetof(pidProfile_t, fixedWingYawItermBankFreeze) },
	{ {61, 220, 2, 0, 0, 0}, VAR_UINT8 | PROFILE_VALUE, .config.minmax.indexes = {0, 32}, (setting_offset_t)offsetof(pidProfile_t, itermWindupPointPercent) },
	{ {64, 61, 63, 160, 2, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 6}, (setting_offset_t)offsetof(pidProfile_t, pidItermLimitPercent) },
	{ {4, 89, 63, 10, 8, 0}, VAR_UINT32 | PROFILE_VALUE, .config.minmax.indexes = {0, 52}, (setting_offset_t)offsetof(pidProfile_t, axisAccelerationLimitRollPitch) },
	{ {4, 89, 63, 5, 0, 0}, VAR_UINT32 | PROFILE_VALUE, .config.minmax.indexes = {0, 52}, (setting_offset_t)offsetof(pidProfile_t, axisAccelerationLimitYaw) },
	{ {100, 101, 4, 63, 0, 0}, VAR_UINT8 | PROFILE_VALUE, .config.minmax.indexes = {5, 23}, (setting_offset_t)offsetof(pidProfile_t, heading_hold_rate_limit) },
	{ {1, 3, 13, 9, 7, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_POS_Z].P) },
	{ {1, 3, 51, 9, 7, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_VEL_Z].P) },
	{ {1, 3, 51, 9, 19, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_VEL_Z].I) },
	{ {1, 3, 51, 9, 17, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_VEL_Z].D) },
	{ {1, 3, 13, 21, 7, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_POS_XY].P) },
	{ {1, 3, 51, 21, 7, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_VEL_XY].P) },
	{ {1, 3, 51, 21, 19, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_VEL_XY].I) },
	{ {1, 3, 51, 21, 17, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_VEL_XY].D) },
	{ {1, 3, 51, 21, 59, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_VEL_XY].FF) },
	{ {1, 3, 100, 7, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_HEADING].P) },
	{ {149, 2, 0, 0, 0, 0}, VAR_FLOAT | PROFILE_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(pidProfile_t, navVelXyDTermLpfHz) },
	{ {146, 2, 0, 0, 0, 0}, VAR_UINT8 | PROFILE_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(pidProfile_t, navVelXyDtermAttenuation) },
	{ {148, 2, 0, 0, 0, 0}, VAR_UINT8 | PROFILE_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(pidProfile_t, navVelXyDtermAttenuationStart) },
	{ {147, 2, 0, 0, 0, 0}, VAR_UINT8 | PROFILE_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(pidProfile_t, navVelXyDtermAttenuationEnd) },
	{ {1, 2, 13, 9, 7, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_POS_Z].P) },
	{ {1, 2, 13, 9, 19, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_POS_Z].I) },
	{ {1, 2, 13, 9, 17, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_POS_Z].D) },
	{ {1, 2, 13, 9, 59, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_POS_Z].FF) },
	{ {1, 2, 52, 45, 158, 1}, VAR_UINT8 | PROFILE_VALUE, .config.minmax.indexes = {10, 2}, (setting_offset_t)offsetof(pidProfile_t, fwAltControlResponseFactor) },
	{ {1, 2, 52, 57, 150, 1}, VAR_UINT8 | PROFILE_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(pidProfile_t, fwAltControlUsePos) },
	{ {1, 2, 13, 21, 7, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_POS_XY].P) },
	{ {1, 2, 13, 21, 19, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_POS_XY].I) },
	{ {1, 2, 13, 21, 17, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_POS_XY].D) },
	{ {1, 2, 100, 7, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_HEADING].P) },
	{ {1, 2, 13, 99, 7, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_POS_HEADING].P) },
	{ {1, 2, 13, 99, 19, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_POS_HEADING].I) },
	{ {1, 2, 13, 99, 17, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_POS_HEADING].D) },
	{ {140, 2, 0, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {2, 3}, (setting_offset_t)offsetof(pidProfile_t, navFwPosHdgPidsumLimit) },
	{ {3, 61, 156, 1, 0, 0}, VAR_UINT8 | PROFILE_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_ITERM_RELAX }, (setting_offset_t)offsetof(pidProfile_t, iterm_relax) },
	{ {3, 61, 156, 1, 127, 0}, VAR_UINT8 | PROFILE_VALUE, .config.minmax.indexes = {7, 2}, (setting_offset_t)offsetof(pidProfile_t, iterm_relax_cutoff) },
	{ {64, 25, 0, 0, 0, 0}, VAR_UINT8 | PROFILE_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_PIDTYPETABLE }, (setting_offset_t)offsetof(pidProfile_t, pidControllerType) },
	{ {3, 73, 24, 23, 0, 0}, VAR_UINT8 | PROFILE_VALUE, .config.minmax.indexes = {0, 6}, (setting_offset_t)offsetof(pidProfile_t, controlDerivativeLpfHz) },
	{ {2, 41, 8, 87, 0, 0}, VAR_FLOAT | PROFILE_VALUE, .config.minmax.indexes = {59, 5}, (setting_offset_t)offsetof(pidProfile_t, fixedWingLevelTrim) },
	{ {2, 41, 8, 235, 1, 0}, VAR_FLOAT | PROFILE_VALUE, .config.minmax.indexes = {0, 21}, (setting_offset_t)offsetof(pidProfile_t, fixedWingLevelTrimGain) },
	{ {231, 1, 0, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {2, 3}, (setting_offset_t)offsetof(pidProfile_t, fwItermLockTimeMaxMs) },
	{ {2, 61, 254, 1, 4, 66}, VAR_UINT8 | PROFILE_VALUE, .config.minmax.indexes = {5, 2}, (setting_offset_t)offsetof(pidProfile_t, fwItermLockRateLimit) },
	{ {230, 1, 0, 0, 0, 0}, VAR_UINT8 | PROFILE_VALUE, .config.minmax.indexes = {10, 42}, (setting_offset_t)offsetof(pidProfile_t, fwItermLockEngageThreshold) },
	// PG_POSITION_ESTIMATION_CONFIG
	{ {6, 35, 31, 204, 1, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(positionEstimationConfig_t, automatic_mag_declination) },
	{ {6, 137, 1, 94, 164, 1}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(positionEstimationConfig_t, gravity_calibration_tolerance) },
	{ {6, 123, 201, 1, 174, 2}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(positionEstimationConfig_t, allow_dead_reckoning) },
	{ {6, 114, 44, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_RESET_TYPE }, (setting_offset_t)offsetof(positionEstimationConfig_t, reset_altitude_type) },
	{ {6, 114, 139, 1, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_RESET_TYPE }, (setting_offset_t)offsetof(positionEstimationConfig_t, reset_home_type) },
	{ {6, 14, 117, 44, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 3}, (setting_offset_t)offsetof(positionEstimationConfig_t, max_surface_altitude) },
	{ {6, 20, 9, 117, 7, 0}, VAR_FLOAT | MASTER_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(positionEstimationConfig_t, w_z_surface_p) },
	{ {6, 20, 9, 117, 50, 0}, VAR_FLOAT | MASTER_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(positionEstimationConfig_t, w_z_surface_v) },
	{ {6, 20, 21, 136, 1, 7}, VAR_FLOAT | MASTER_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(positionEstimationConfig_t, w_xy_flow_p) },
	{ {6, 20, 21, 136, 1, 50}, VAR_FLOAT | MASTER_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(positionEstimationConfig_t, w_xy_flow_v) },
	{ {6, 20, 9, 53, 7, 0}, VAR_FLOAT | MASTER_VALUE, .config.minmax.indexes = {0, 5}, (setting_offset_t)offsetof(positionEstimationConfig_t, w_z_baro_p) },
	{ {6, 20, 9, 53, 50, 0}, VAR_FLOAT | MASTER_VALUE, .config.minmax.indexes = {0, 5}, (setting_offset_t)offsetof(positionEstimationConfig_t, w_z_baro_v) },
	{ {6, 20, 9, 11, 7, 0}, VAR_FLOAT | MASTER_VALUE, .config.minmax.indexes = {0, 5}, (setting_offset_t)offsetof(positionEstimationConfig_t, w_z_gps_p) },
	{ {6, 20, 9, 11, 50, 0}, VAR_FLOAT | MASTER_VALUE, .config.minmax.indexes = {0, 5}, (setting_offset_t)offsetof(positionEstimationConfig_t, w_z_gps_v) },
	{ {6, 20, 21, 11, 7, 0}, VAR_FLOAT | MASTER_VALUE, .config.minmax.indexes = {0, 5}, (setting_offset_t)offsetof(positionEstimationConfig_t, w_xy_gps_p) },
	{ {6, 20, 21, 11, 50, 0}, VAR_FLOAT | MASTER_VALUE, .config.minmax.indexes = {0, 5}, (setting_offset_t)offsetof(positionEstimationConfig_t, w_xy_gps_v) },
	{ {6, 20, 9, 157, 1, 50}, VAR_FLOAT | MASTER_VALUE, .config.minmax.indexes = {0, 5}, (setting_offset_t)offsetof(positionEstimationConfig_t, w_z_res_v) },
	{ {6, 20, 21, 157, 1, 50}, VAR_FLOAT | MASTER_VALUE, .config.minmax.indexes = {0, 5}, (setting_offset_t)offsetof(positionEstimationConfig_t, w_xy_res_v) },
	{ {6, 20, 33, 186, 1, 0}, VAR_FLOAT | MASTER_VALUE, .config.minmax.indexes = {0, 7}, (setting_offset_t)offsetof(positionEstimationConfig_t, w_acc_bias) },
	{ {6, 14, 216, 1, 134, 1}, VAR_FLOAT | MASTER_VALUE, .config.minmax.indexes = {0, 51}, (setting_offset_t)offsetof(positionEstimationConfig_t, max_eph_epv) },
	{ {6, 53, 134, 1, 0, 0}, VAR_FLOAT | MASTER_VALUE, .config.minmax.indexes = {0, 51}, (setting_offset_t)offsetof(positionEstimationConfig_t, baro_epv) },
	{ {6, 206, 1, 52, 185, 2}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_DEFAULT_ALTITUDE_SOURCE }, (setting_offset_t)offsetof(positionEstimationConfig_t, default_alt_sensor) },
	// PG_NAV_CONFIG
	{ {1, 77, 111, 62, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(navConfig_t, general.flags.disarm_on_landing) },
	{ {1, 47, 128, 1, 162, 1}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {7, 14}, (setting_offset_t)offsetof(navConfig_t, general.land_detect_sensitivity) },
	{ {1, 62, 188, 1, 209, 1}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(navConfig_t, general.flags.landing_bump_detection) },
	{ {145, 2, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 14}, (setting_offset_t)offsetof(navConfig_t, mc.inverted_crash_detection) },
	{ {1, 3, 174, 1, 32, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_NAV_MC_ALTHOLD_THROTTLE }, (setting_offset_t)offsetof(navConfig_t, mc.althold_throttle_type) },
	{ {137, 2, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_NAV_EXTRA_ARMING_SAFETY }, (setting_offset_t)offsetof(navConfig_t, general.flags.extra_arming_safety) },
	{ {1, 215, 2, 45, 37, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_NAV_USER_CONTROL_MODE }, (setting_offset_t)offsetof(navConfig_t, general.flags.user_control_mode) },
	{ {1, 150, 1, 118, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 5}, (setting_offset_t)offsetof(navConfig_t, general.pos_failure_timeout) },
	{ {154, 2, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(navConfig_t, general.waypoint_load_on_boot) },
	{ {1, 58, 155, 1, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {5, 16}, (setting_offset_t)offsetof(navConfig_t, general.waypoint_radius) },
	{ {1, 58, 215, 1, 44, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 4}, (setting_offset_t)offsetof(navConfig_t, general.waypoint_enforce_altitude) },
	{ {1, 58, 14, 181, 2, 54}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 70}, (setting_offset_t)offsetof(navConfig_t, general.waypoint_safe_distance) },
	{ {1, 58, 107, 178, 2, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_NAV_WP_MISSION_RESTART }, (setting_offset_t)offsetof(navConfig_t, general.flags.waypoint_mission_restart) },
	{ {142, 2, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 5}, (setting_offset_t)offsetof(navConfig_t, fw.wp_tracking_accuracy) },
	{ {143, 2, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {31, 25}, (setting_offset_t)offsetof(navConfig_t, fw.wp_tracking_max_angle) },
	{ {1, 2, 58, 210, 2, 116}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_NAV_FW_WP_TURN_SMOOTHING }, (setting_offset_t)offsetof(navConfig_t, fw.wp_turn_smoothing) },
	{ {1, 35, 56, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {5, 4}, (setting_offset_t)offsetof(navConfig_t, general.auto_speed) },
	{ {1, 15, 240, 1, 56, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {61, 12}, (setting_offset_t)offsetof(navConfig_t, general.min_ground_speed) },
	{ {1, 14, 35, 56, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {5, 4}, (setting_offset_t)offsetof(navConfig_t, general.max_auto_speed) },
	{ {1, 36, 56, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {5, 4}, (setting_offset_t)offsetof(navConfig_t, general.max_manual_speed) },
	{ {1, 47, 146, 1, 170, 1}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {12, 11}, (setting_offset_t)offsetof(navConfig_t, general.land_minalt_vspd) },
	{ {1, 47, 145, 1, 170, 1}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {2, 4}, (setting_offset_t)offsetof(navConfig_t, general.land_maxalt_vspd) },
	{ {1, 47, 115, 146, 1, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {12, 3}, (setting_offset_t)offsetof(navConfig_t, general.land_slowdown_minalt) },
	{ {1, 47, 115, 145, 1, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {11, 73}, (setting_offset_t)offsetof(navConfig_t, general.land_slowdown_maxalt) },
	{ {1, 133, 1, 62, 56, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {2, 4}, (setting_offset_t)offsetof(navConfig_t, general.emerg_descent_rate) },
	{ {1, 15, 16, 54, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 15}, (setting_offset_t)offsetof(navConfig_t, general.min_rth_distance) },
	{ {1, 159, 2, 48, 199, 2}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_NAV_OVERRIDES_MOTOR_STOP }, (setting_offset_t)offsetof(navConfig_t, general.flags.nav_overrides_motor_stop) },
	{ {141, 2, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(navConfig_t, general.flags.soaring_motor_stop) },
	{ {1, 2, 192, 2, 8, 27}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 14}, (setting_offset_t)offsetof(navConfig_t, fw.soaring_pitch_deadband) },
	{ {1, 16, 39, 135, 1, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_NAV_RTH_CLIMB_FIRST }, (setting_offset_t)offsetof(navConfig_t, general.flags.rth_climb_first) },
	{ {151, 2, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_NAV_RTH_CLIMB_FIRST_STAGE_MODES }, (setting_offset_t)offsetof(navConfig_t, general.flags.rth_climb_first_stage_mode) },
	{ {150, 2, 0, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 17}, (setting_offset_t)offsetof(navConfig_t, general.rth_climb_first_stage_altitude) },
	{ {1, 16, 39, 102, 133, 1}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(navConfig_t, general.flags.rth_climb_ignore_emerg) },
	{ {1, 16, 203, 2, 135, 1}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(navConfig_t, general.flags.rth_tail_first) },
	{ {1, 16, 123, 62, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_NAV_RTH_ALLOW_LANDING }, (setting_offset_t)offsetof(navConfig_t, general.flags.rth_allow_landing) },
	{ {1, 16, 228, 1, 62, 28}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 71}, (setting_offset_t)offsetof(navConfig_t, general.rth_fs_landing_delay) },
	{ {1, 16, 52, 37, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_NAV_RTH_ALT_MODE }, (setting_offset_t)offsetof(navConfig_t, general.flags.rth_alt_control_mode) },
	{ {1, 16, 52, 45, 158, 2}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(navConfig_t, general.flags.rth_alt_control_override) },
	{ {1, 16, 121, 66, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 17}, (setting_offset_t)offsetof(navConfig_t, general.rth_abort_threshold) },
	{ {144, 2, 0, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 3}, (setting_offset_t)offsetof(navConfig_t, general.max_terrain_follow_altitude) },
	{ {1, 14, 44, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 17}, (setting_offset_t)offsetof(navConfig_t, general.max_altitude) },
	{ {1, 16, 44, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 17}, (setting_offset_t)offsetof(navConfig_t, general.rth_altitude) },
	{ {1, 16, 139, 1, 44, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 17}, (setting_offset_t)offsetof(navConfig_t, general.rth_home_altitude) },
	{ {152, 2, 0, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 16}, (setting_offset_t)offsetof(navConfig_t, general.rth_linear_descent_start_distance) },
	{ {153, 2, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(navConfig_t, general.flags.rth_use_linear_descent) },
	{ {1, 16, 165, 1, 37, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_RTH_TRACKBACK_MODE }, (setting_offset_t)offsetof(navConfig_t, general.flags.rth_trackback_mode) },
	{ {1, 16, 165, 1, 54, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {12, 4}, (setting_offset_t)offsetof(navConfig_t, general.rth_trackback_distance) },
	{ {160, 1, 14, 54, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 17}, (setting_offset_t)offsetof(navConfig_t, general.safehome_max_distance) },
	{ {160, 1, 214, 2, 37, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_SAFEHOME_USAGE_MODE }, (setting_offset_t)offsetof(navConfig_t, general.flags.safehome_usage_mode) },
	{ {1, 107, 164, 2, 114, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(navConfig_t, general.flags.mission_planner_reset) },
	{ {1, 75, 5, 4, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 33}, (setting_offset_t)offsetof(navConfig_t, general.cruise_yaw_rate) },
	{ {1, 3, 124, 22, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {14, 44}, (setting_offset_t)offsetof(navConfig_t, mc.max_bank_angle) },
	{ {1, 3, 35, 39, 4, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {5, 4}, (setting_offset_t)offsetof(navConfig_t, mc.max_auto_climb_rate) },
	{ {1, 3, 36, 39, 4, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {5, 4}, (setting_offset_t)offsetof(navConfig_t, mc.max_manual_climb_rate) },
	{ {1, 35, 77, 28, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {2, 16}, (setting_offset_t)offsetof(navConfig_t, general.auto_disarm_delay) },
	{ {1, 3, 13, 203, 1, 49}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(navConfig_t, mc.posDecelerationTime) },
	{ {1, 3, 13, 40, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(navConfig_t, mc.posResponseExpo) },
	{ {1, 3, 58, 115, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(navConfig_t, mc.slowDownForTurning) },
	{ {1, 2, 124, 22, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {10, 25}, (setting_offset_t)offsetof(navConfig_t, fw.max_bank_angle) },
	{ {1, 2, 35, 39, 4, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {5, 4}, (setting_offset_t)offsetof(navConfig_t, fw.max_auto_climb_rate) },
	{ {1, 2, 36, 39, 4, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {5, 72}, (setting_offset_t)offsetof(navConfig_t, fw.max_manual_climb_rate) },
	{ {1, 2, 39, 22, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {10, 25}, (setting_offset_t)offsetof(navConfig_t, fw.max_climb_angle) },
	{ {1, 2, 130, 1, 22, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {10, 25}, (setting_offset_t)offsetof(navConfig_t, fw.max_dive_angle) },
	{ {1, 2, 113, 116, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 40}, (setting_offset_t)offsetof(navConfig_t, fw.pitch_to_throttle_smooth) },
	{ {2, 15, 32, 211, 1, 8}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 47}, (setting_offset_t)offsetof(navConfig_t, fw.minThrottleDownPitchAngle) },
	{ {1, 2, 113, 66, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 35}, (setting_offset_t)offsetof(navConfig_t, fw.pitch_to_throttle_thresh) },
	{ {1, 2, 144, 1, 155, 1}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 78}, (setting_offset_t)offsetof(navConfig_t, fw.loiter_radius) },
	{ {2, 144, 1, 129, 1, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_DIRECTION }, (setting_offset_t)offsetof(navConfig_t, fw.loiter_direction) },
	{ {1, 2, 75, 56, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 20}, (setting_offset_t)offsetof(navConfig_t, fw.cruise_speed) },
	{ {1, 2, 45, 190, 2, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 40}, (setting_offset_t)offsetof(navConfig_t, fw.control_smoothness) },
	{ {1, 2, 47, 130, 1, 22}, VAR_INT8 | MASTER_VALUE, .config.minmax.indexes = {57, 21}, (setting_offset_t)offsetof(navConfig_t, fw.land_dive_angle) },
	{ {1, 2, 12, 216, 2, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {2, 16}, (setting_offset_t)offsetof(navConfig_t, fw.launch_velocity_thresh) },
	{ {1, 2, 12, 89, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {69, 77}, (setting_offset_t)offsetof(navConfig_t, fw.launch_accel_thresh) },
	{ {1, 2, 12, 14, 22, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {10, 22}, (setting_offset_t)offsetof(navConfig_t, fw.launch_max_angle) },
	{ {1, 2, 12, 128, 1, 49}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {5, 3}, (setting_offset_t)offsetof(navConfig_t, fw.launch_time_thresh) },
	{ {1, 2, 12, 80, 48, 28}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 26}, (setting_offset_t)offsetof(navConfig_t, fw.launch_idle_motor_timer) },
	{ {139, 2, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 13}, (setting_offset_t)offsetof(navConfig_t, fw.launch_wiggle_wake_idle) },
	{ {1, 2, 12, 48, 28, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 15}, (setting_offset_t)offsetof(navConfig_t, fw.launch_motor_timer) },
	{ {1, 2, 12, 194, 2, 49}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 3}, (setting_offset_t)offsetof(navConfig_t, fw.launch_motor_spinup_time) },
	{ {1, 2, 12, 213, 1, 49}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 15}, (setting_offset_t)offsetof(navConfig_t, fw.launch_end_time) },
	{ {1, 2, 12, 15, 49, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 26}, (setting_offset_t)offsetof(navConfig_t, fw.launch_min_time) },
	{ {1, 2, 12, 118, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 26}, (setting_offset_t)offsetof(navConfig_t, fw.launch_timeout) },
	{ {1, 2, 12, 14, 44, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 26}, (setting_offset_t)offsetof(navConfig_t, fw.launch_max_altitude) },
	{ {1, 2, 12, 39, 22, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {10, 44}, (setting_offset_t)offsetof(navConfig_t, fw.launch_climb_angle) },
	{ {1, 2, 12, 36, 32, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(navConfig_t, fw.launch_manual_throttle) },
	{ {1, 2, 12, 47, 121, 27}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {13, 23}, (setting_offset_t)offsetof(navConfig_t, fw.launch_land_abort_deadband) },
	{ {138, 2, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(navConfig_t, fw.allow_manual_thr_increase) },
	{ {1, 57, 2, 5, 45, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(navConfig_t, fw.useFwNavYawControl) },
	{ {1, 2, 5, 27, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 32}, (setting_offset_t)offsetof(navConfig_t, fw.yawControlDeadband) },
	// PG_TELEMETRY_CONFIG
	{ {85, 84, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(telemetryConfig_t, telemetry_switch) },
	{ {85, 141, 1, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(telemetryConfig_t, telemetry_inverted) },
	{ {226, 1, 8, 10, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(telemetryConfig_t, frsky_pitch_roll) },
	{ {227, 1, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(telemetryConfig_t, frsky_use_legacy_gps_mode_sensor_ids) },
	{ {177, 2, 190, 1, 169, 1}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(telemetryConfig_t, report_cell_voltage) },
	{ {245, 1, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 33}, (setting_offset_t)offsetof(telemetryConfig_t, hottAlarmSoundInterval) },
	{ {85, 138, 1, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(telemetryConfig_t, halfDuplex) },
	{ {189, 2, 229, 1, 167, 1}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_SMARTPORT_FUEL_UNIT }, (setting_offset_t)offsetof(telemetryConfig_t, smartportFuelUnit) },
	{ {247, 1, 85, 25, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(telemetryConfig_t, ibusTelemetryType) },
	{ {128, 2, 213, 2, 4, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_LTM_RATES }, (setting_offset_t)offsetof(telemetryConfig_t, ltmUpdateRate) },
	{ {26, 217, 1, 197, 2, 4}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(telemetryConfig_t, mavlink.extended_status_rate) },
	{ {26, 180, 1, 25, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_MAVLINK_AUTOPILOT_TYPE }, (setting_offset_t)offsetof(telemetryConfig_t, mavlink.autopilot_type) },
	{ {26, 42, 192, 1, 4, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(telemetryConfig_t, mavlink.rc_channels_rate) },
	{ {26, 13, 4, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(telemetryConfig_t, mavlink.position_rate) },
	{ {26, 218, 1, 4, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(telemetryConfig_t, mavlink.extra1_rate) },
	{ {26, 219, 1, 4, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(telemetryConfig_t, mavlink.extra2_rate) },
	{ {26, 220, 1, 4, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(telemetryConfig_t, mavlink.extra3_rate) },
	{ {26, 217, 2, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {7, 13}, (setting_offset_t)offsetof(telemetryConfig_t, mavlink.version) },
	{ {26, 15, 211, 2, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(telemetryConfig_t, mavlink.min_txbuff) },
	{ {26, 172, 2, 25, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_MAVLINK_RADIO_TYPE }, (setting_offset_t)offsetof(telemetryConfig_t, mavlink.radio_type) },
	{ {26, 202, 2, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {7, 1}, (setting_offset_t)offsetof(telemetryConfig_t, mavlink.sysid) },
	// PG_SYSTEM_CONFIG
	{ {202, 1, 37, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_DEBUG_MODES }, (setting_offset_t)offsetof(systemConfig_t, debug_mode) },
	{ {32, 86, 95, 200, 2, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(systemConfig_t, throttle_tilt_compensation_strength) },
	{ {148, 1, 0, 0, 0, 0}, VAR_STRING | MASTER_VALUE, .config.minmax.indexes = {0, 41}, (setting_offset_t)offsetof(systemConfig_t, craftName) },
	{ {161, 2, 148, 1, 0, 0}, VAR_STRING | MASTER_VALUE, .config.minmax.indexes = {0, 41}, (setting_offset_t)offsetof(systemConfig_t, pilotName) },
	// PG_MODE_ACTIVATION_OPERATOR_CONFIG
	{ {135, 2, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_AUX_OPERATOR }, (setting_offset_t)offsetof(modeActivationOperatorConfig_t, modeActivationOperator) },
	// PG_TIME_CONFIG
	{ {166, 1, 81, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {56, 68}, (setting_offset_t)offsetof(timeConfig_t, tz_offset) },
	{ {166, 1, 179, 1, 212, 1}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_TZ_AUTOMATIC_DST }, (setting_offset_t)offsetof(timeConfig_t, tz_automatic_dst) },
	// PG_DISPLAY_CONFIG
	{ {210, 1, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(displayConfig_t, force_sw_blink) },
	// PG_BEEPER_CONFIG
	{ {131, 1, 92, 97, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(beeperConfig_t, dshot_beeper_enabled) },
	{ {131, 1, 92, 207, 2, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {7, 10}, (setting_offset_t)offsetof(beeperConfig_t, dshot_beeper_tone) },
	{ {92, 65, 37, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(beeperConfig_t, pwmMode) },
	// PG_LEDPIN_CONFIG
	{ {252, 1, 162, 2, 65, 37}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_LED_PIN_PWM_MODE }, (setting_offset_t)offsetof(ledPinConfig_t, led_pin_pwm_mode) },
	// PG_GIMBAL_CONFIG
	{ {46, 112, 74, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 24}, (setting_offset_t)offsetof(gimbalConfig_t, panChannel) },
	{ {46, 10, 74, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 24}, (setting_offset_t)offsetof(gimbalConfig_t, rollChannel) },
	{ {46, 86, 74, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 24}, (setting_offset_t)offsetof(gimbalConfig_t, tiltChannel) },
	{ {46, 162, 1, 0, 0, 0}, VAR_INT8 | MASTER_VALUE, .config.minmax.indexes = {58, 14}, (setting_offset_t)offsetof(gimbalConfig_t, sensitivity) },
	{ {46, 112, 87, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {29, 11}, (setting_offset_t)offsetof(gimbalConfig_t, panTrim) },
	{ {46, 86, 87, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {29, 11}, (setting_offset_t)offsetof(gimbalConfig_t, tiltTrim) },
	{ {46, 10, 87, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {29, 11}, (setting_offset_t)offsetof(gimbalConfig_t, rollTrim) },
	// PG_GIMBAL_SERIAL_CONFIG
	{ {237, 1, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(gimbalSerialConfig_t, singleUart) },
	// PG_HEADTRACKER_CONFIG
	{ {79, 25, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_HEADTRACKER_DEV_TYPE }, (setting_offset_t)offsetof(headTrackerConfig_t, devType) },
	{ {79, 112, 82, 0, 0, 0}, VAR_FLOAT | MASTER_VALUE, .config.minmax.indexes = {0, 10}, (setting_offset_t)offsetof(headTrackerConfig_t, pan_ratio) },
	{ {79, 86, 82, 0, 0, 0}, VAR_FLOAT | MASTER_VALUE, .config.minmax.indexes = {0, 10}, (setting_offset_t)offsetof(headTrackerConfig_t, tilt_ratio) },
	{ {79, 10, 82, 0, 0, 0}, VAR_FLOAT | MASTER_VALUE, .config.minmax.indexes = {0, 10}, (setting_offset_t)offsetof(headTrackerConfig_t, roll_ratio) },
};
