if(EXISTS "/home/robs/Projects/inav-claude/inav/testing/src/test/unit/bitarray_unittest[1]_tests.cmake")
  include("/home/robs/Projects/inav-claude/inav/testing/src/test/unit/bitarray_unittest[1]_tests.cmake")
else()
  add_test(bitarray_unittest_NOT_BUILT bitarray_unittest_NOT_BUILT)
endif()
