if(EXISTS "/home/robs/Projects/inav-claude/inav/testing/src/test/unit/olc_unittest[1]_tests.cmake")
  include("/home/robs/Projects/inav-claude/inav/testing/src/test/unit/olc_unittest[1]_tests.cmake")
else()
  add_test(olc_unittest_NOT_BUILT olc_unittest_NOT_BUILT)
endif()
