if(EXISTS "/home/robs/Projects/inav-claude/inav/testing/src/test/unit/telemetry_hott_unittest[1]_tests.cmake")
  include("/home/robs/Projects/inav-claude/inav/testing/src/test/unit/telemetry_hott_unittest[1]_tests.cmake")
else()
  add_test(telemetry_hott_unittest_NOT_BUILT telemetry_hott_unittest_NOT_BUILT)
endif()
