if(EXISTS "/home/robs/Projects/inav-claude/inav/testing/src/test/unit/time_unittest[1]_tests.cmake")
  include("/home/robs/Projects/inav-claude/inav/testing/src/test/unit/time_unittest[1]_tests.cmake")
else()
  add_test(time_unittest_NOT_BUILT time_unittest_NOT_BUILT)
endif()
