// This file has been automatically generated by utils/settings.rb
// Don't make any modifications to it. They will be lost.

#include "platform.h"
#include "config/parameter_group_ids.h"
#include "fc/settings.h"
#include "sensors/gyro.h"
#include "sensors/acceleration.h"
#include "sensors/compass.h"
#include "sensors/barometer.h"
#include "rx/rx.h"
#include "rx/spektrum.h"
#include "flight/mixer.h"
#include "flight/failsafe.h"
#include "sensors/boardalignment.h"
#include "sensors/battery_config_structs.h"
#include "sensors/battery_config_structs.h"
#include "flight/mixer_profile.h"
#include "flight/servos.h"
#include "fc/control_profile_config_struct.h"
#include "flight/imu.h"
#include "config/general_settings.h"
#include "flight/ez_tune.h"
#include "io/gps.h"
#include "fc/rc_controls.h"
#include "flight/pid.h"
#include "navigation/navigation.h"
#include "io/serial.h"
#include "telemetry/telemetry.h"
#include "telemetry/sim.h"
#include "fc/config.h"
#include "fc/rc_modes.h"
#include "common/time.h"
#include "drivers/display.h"
#include "fc/config.h"
#include "drivers/light_ws2811strip.h"
#pragma GCC diagnostic ignored "-Wunused-const-variable"
const pgn_t settingsPgn[] = {
	PG_GYRO_CONFIG,
	PG_ACCELEROMETER_CONFIG,
	PG_COMPASS_CONFIG,
	PG_BAROMETER_CONFIG,
	PG_RX_CONFIG,
	PG_MOTOR_CONFIG,
	PG_FAILSAFE_CONFIG,
	PG_BOARD_ALIGNMENT,
	PG_BATTERY_METERS_CONFIG,
	PG_BATTERY_PROFILES,
	PG_MIXER_PROFILE,
	PG_REVERSIBLE_MOTORS_CONFIG,
	PG_SERVO_CONFIG,
	PG_CONTROL_PROFILES,
	PG_IMU_CONFIG,
	PG_ARMING_CONFIG,
	PG_GENERAL_SETTINGS,
	PG_EZ_TUNE,
	PG_GPS_CONFIG,
	PG_RC_CONTROLS_CONFIG,
	PG_PID_PROFILE,
	PG_POSITION_ESTIMATION_CONFIG,
	PG_NAV_CONFIG,
	PG_TELEMETRY_CONFIG,
	PG_SYSTEM_CONFIG,
	PG_MODE_ACTIVATION_OPERATOR_CONFIG,
	PG_TIME_CONFIG,
	PG_DISPLAY_CONFIG,
	PG_BEEPER_CONFIG,
	PG_LEDPIN_CONFIG,
};
const uint8_t settingsPgnCounts[] = {
	14,
	12,
	13,
	3,
	14,
	4,
	12,
	3,
	9,
	14,
	12,
	3,
	7,
	19,
	10,
	4,
	1,
	10,
	11,
	7,
	81,
	22,
	89,
	21,
	4,
	1,
	2,
	1,
	3,
	1,
};
static const uint8_t settingNamesWords[] = {
	0x70,0x6c, /* "nav" */ 
	0x3,0x5c, /* "fw" */ 
	0xd,0x18, /* "mc" */ 
	0x24,0x1a,0x14, /* "rate" */ 
	0x19,0xd, /* "yaw" */ 
	0xc0,0x97,0x6,0xc0, /* "inav" */ 
	0x80, /* "p" */ 
	0x20,0x9a,0xd,0x0, /* "pitch" */ 
	0xd0, /* "z" */ 
	0xf,0x9, /* "gps" */ 
	0x81,0x81,0xab,0x86,0x80, /* "launch" */ 
	0x34,0x38, /* "max" */ 
	0x4,0x1f,0x30, /* "pos" */ 
	0x49,0xec,0x60, /* "roll" */ 
	0x1a,0x97, /* "min" */ 
	0x2,0x54,0x40, /* "rth" */ 
	0x8, /* "d" */ 
	0x3,0x5,0x2c,0x98,0x4c,0x50, /* "failsafe" */ 
	0x24, /* "i" */ 
	0x17, /* "w" */ 
	0x6,0x32, /* "xy" */ 
	0x0,0xb8,0xec,0x28, /* "angle" */ 
	0x11,0xa0, /* "hz" */ 
	0x32,0x6, /* "lpf" */ 
	0x3,0x43,0x66,0x25,0xcb, /* "mavlink" */ 
	0x5,0x33,0x2, /* "type" */ 
	0x80,0x35,0xa3, /* "auto" */ 
	0xc0,0x42,0x84,0x82,0xb,0x88, /* "deadband" */ 
	0x2,0x15,0x81,0xc8, /* "delay" */ 
	0xb,0xa0, /* "ez" */ 
	0x1f,0x32,0x78, /* "gyro" */ 
	0x1a,0x13, /* "mag" */ 
	0x82,0x88,0x93,0xe9,0x46,0x14, /* "throttle" */ 
	0x1,0x18, /* "acc" */ 
	0xc0,0x14,0x4a,0x60, /* "ahrs" */ 
	0x68,0x5d,0x50,0xb0, /* "manual" */ 
	0xd,0x79,0xa, /* "mode" */ 
	0xa,0x22,0x40, /* "thr" */ 
	0x1b,0x12,0xd1, /* "climb" */ 
	0x0,0xb8,0x83, /* "expo" */ 
	0xc0,0xc2,0xd8,0xac, /* "level" */ 
	0x4,0x86, /* "rc" */ 
	0x0,0xb1,0x27,0x70, /* "align" */ 
	0x2,0xca,0x26,0x95,0x21, /* "altitude" */ 
	0x40,0x37,0xba,0x92,0x7b, /* "control" */ 
	0x0,0xc0,0xb8,0x80, /* "land" */ 
	0x6b,0xe8,0xf9, /* "motor" */ 
	0x2,0x89,0x69, /* "time" */ 
	0x41,0x60, /* "v" */ 
	0x58,0xac, /* "vel" */ 
	0x0,0x59,0x40, /* "alt" */ 
	0x8,0x32,0x78, /* "baro" */ 
	0x8,0x99,0xd0,0x2e,0x19, /* "distance" */ 
	0x41,0x32,0xca,0xcf, /* "servo" */ 
	0x4,0xe0,0x52,0x90, /* "speed" */ 
	0x15,0x99, /* "use" */ 
	0x41,0x78, /* "wp" */ 
	0x0,0xc6, /* "ff" */ 
	0x1,0x92,0xca,0x16,0x40, /* "filter" */ 
	0x4d,0xb,0x26, /* "iterm" */ 
	0x81,0x81,0x71,0x12,0xe3, /* "landing" */ 
	0x81,0x89,0x6a,0x68, /* "limit" */ 
	0x8,0x24,0x80, /* "pid" */ 
	0x85,0xda, /* "pwm" */ 
	0xa,0x22,0x45,0x9a,0x1e,0xc2, /* "threshold" */ 
	0x2,0x90,0x8, /* "tpa" */ 
	0x30, /* "x" */ 
	0xc, /* "y" */ 
	0x83,0x64, /* "3d" */ 
	0x0,0x83,0x4a,0x16,0x59, /* "battery" */ 
	0x0,0xc3,0x0,0x8d,0x34,0xc8, /* "capacity" */ 
	0x6,0x40, /* "cd" */ 
	0xe,0x55,0x4c,0xca, /* "cruise" */ 
	0x2,0xd,0xa0, /* "dcm" */ 
	0x22,0x66,0x19,0x34, /* "disarm" */ 
	0x4,0xcb, /* "dyn" */ 
	0x80,0x92,0x30,0xa0, /* "idle" */ 
	0x79,0x8d,0x32,0xd0, /* "offset" */ 
	0x12,0x9c,0xd2, /* "rssi" */ 
	0x9,0xdd,0x34,0x1a, /* "switch" */ 
	0x1,0x42,0xb0,0xad,0x2d,0x25,0x90, /* "telemetry" */ 
	0x54,0x4c,0x7e, /* "ublox" */ 
	0x0,0x11,0x8c,0xac, /* "accel" */ 
	0x0,0x46,0x33,0x85,0x2e, /* "accgain" */ 
	0x0,0x46,0x3d,0x16,0x4f, /* "acczero" */ 
	0x0,0x8a,0x58,0x16,0x40, /* "beeper" */ 
	0x13,0xc3,0x22, /* "board" */ 
	0x0,0x61,0x60, /* "cal" */ 
	0x6,0xf6,0xc0, /* "comp" */ 
	0x3,0xac,0xa4,0x57,0x50, /* "current" */ 
	0x5,0x70,0x44,0xc2,0x90, /* "enabled" */ 
	0x7,0xa,0x5c, /* "gain" */ 
	0x4,0x6,0x44,0xb8,0x64,0x50, /* "hardware" */ 
	0x20,0x87, /* "hdg" */ 
	0x2,0xa,0x12,0x25,0xc7, /* "heading" */ 
	0x2,0x1e,0xc2, /* "hold" */ 
	0x1,0x27,0x73,0xe4,0x50, /* "ignore" */ 
	0x31,0xf7, /* "low" */ 
	0x3,0x42,0x73,0x85,0x2e, /* "maggain" */ 
	0x3,0x42,0x7d,0x16,0x4f, /* "magzero" */ 
	0x3,0x4b,0x42,0xc8, /* "meter" */ 
	0xd,0x4c,0xe6,0x97,0xb8, /* "mission" */ 
	0xd,0x4e,0xb,0x20, /* "mixer" */ 
	0x35,0xa9,0xc0, /* "mmix" */ 
	0x1b,0x56,0x51,0x30,0x62,0x4b,0x20, /* "multiplier" */ 
	0x3d,0xc0, /* "on" */ 
	0x82,0x68,0x34,0x72,0x88,0x90, /* "pitch2thr" */ 
	0x24,0x59,0x96,0x80, /* "reset" */ 
	0x9b,0x1f,0x72,0x3e,0xee, /* "slowdown" */ 
	0x4,0xda,0xf7,0xd1,0x9,0x71, /* "smoothing" */ 
	0xc1,0x3a,0xc8,0xc1,0x19, /* "surface" */ 
	0x41,0x44,0xb4,0xaf,0xad, /* "timeout" */ 
	0x1,0x49,0x5,0xd3,0x4d,0x12,0xf7, /* "transition" */ 
	0x2,0x95,0x93, /* "turn" */ 
	0x81,0xa2,0xc9,0xe0, /* "zero" */ 
	0x8,0x9f,0x2a, /* "abort" */ 
	0x0,0x29,0x93,0x5e,0x42, /* "airmode" */ 
	0x80,0x2c,0x63,0xee, /* "allow" */ 
	0x0,0xce,0x69,0x9d, /* "assist" */ 
	0x0,0x20,0xb9,0x60, /* "bank" */ 
	0x10,0x6a,0x40, /* "baud" */ 
	0xd,0x5,0x1a, /* "check" */ 
	0xc0,0x37,0xca,0x45,0x1d,0x12,0xf7, /* "correction" */ 
	0x0,0x75,0xa3,0xcc,0x60, /* "cutoff" */ 
	0x10,0xb4,0x28,0xe8, /* "detect" */ 
	0x2,0x26,0x45,0x1d,0x12,0xf7, /* "direction" */ 
	0x0,0x89,0xb1, /* "dive" */ 
	0x40,0x49,0xa1,0xf4, /* "dshot" */ 
	0x1,0x28,0x59,0x34, /* "dterm" */ 
	0x5,0x69,0x64,0x70, /* "emerg" */ 
	0x16,0x16, /* "epv" */ 
	0x1,0x93,0x29,0xd0, /* "first" */ 
	0x6,0x63,0xee, /* "flow" */ 
	0x3,0xc8,0x36,0x4d,0x32, /* "gravity" */ 
	0x4,0x5,0x86,0x25,0x60,0xc2,0xe0, /* "halfduplex" */ 
	0x8,0x7b,0x4a, /* "home" */ 
	0x4,0xb8,0x6c,0x4b,0x83,0x44,0xbd,0xc0, /* "inclination" */ 
	0x4b,0xac,0x59,0x50,0xa4, /* "inverted" */ 
	0x2,0xd2, /* "ki" */ 
	0x5,0xc0, /* "kp" */ 
	0xc,0x7a,0x68,0x59, /* "loiter" */ 
	0x1,0xa1,0xc0,0x59,0x40, /* "maxalt" */ 
	0x35,0x2e,0xb,0x28, /* "minalt" */ 
	0x6,0xbc,0x85,0x60, /* "model" */ 
	0x1c,0x16,0x94, /* "name" */ 
	0xe,0x7d,0x6,0x80, /* "notch" */ 
	0x41,0xf3,0x4d,0x12,0xf7, /* "position" */ 
	0x2,0xf,0xb9,0x64, /* "power" */ 
	0x8,0x49,0xe3,0x29,0x2b,0x22, /* "procedure" */ 
	0x82,0x12,0x79,0x92,0xc2, /* "profile" */ 
	0x82,0x12,0x7d,0x1e,0x37,0xb0, /* "protocol" */ 
	0x12,0x9,0x13,0x59, /* "radius" */ 
	0x82,0x45,0x60,0x70, /* "relax" */ 
	0x9,0x16,0x60, /* "res" */ 
	0x91,0x67,0x7,0xba,0x65, /* "response" */ 
	0x4,0xb0, /* "rx" */ 
	0x9,0x84,0xc5,0x43,0xda,0x50, /* "safehome" */ 
	0x4c,0x61,0x61, /* "scale" */ 
	0x41,0x42,0xb6,0x0, /* "temp" */ 
	0xa3,0xd8,0x59,0x5,0xc3,0x28, /* "tolerance" */ 
	0x29,0x20,0x8d,0x62,0x8,0xd6, /* "trackback" */ 
	0xa,0x68, /* "tz" */ 
	0x15,0x72,0x68, /* "unit" */ 
	0xa,0xcc,0xa3, /* "usec" */ 
	0x5,0x9e,0xca,0x4,0xe5, /* "voltage" */ 
	0x5,0xa7,0x2, /* "vspd" */ 
	0x2,0xe5,0x49,0xd1,0x40, /* "weight" */ 
	0x4,0xe7,0x91,0x67,0x34,0xd8,0xae,0x2c,0xe6, /* "aggressiveness" */ 
	0x0,0xa6,0x53,0x81,0x4a,0x40, /* "airspeed" */ 
	0x5,0x94,0x43,0xd8,0x40, /* "althold" */ 
	0x5,0x97,0xe,0x66, /* "always" */ 
	0x0,0xc0,0x20, /* "apa" */ 
	0xc,0x20,0xc4,0x94,0x80, /* "applied" */ 
	0xd,0x68,0xf6,0x86,0x85,0x20, /* "automated" */ 
	0x3,0x5a,0x3d,0xa1,0xa2,0x46, /* "automatic" */ 
	0x0,0xd6,0x8f,0x82,0x58,0xfa, /* "autopilot" */ 
	0x0,0x35,0xa3,0xe9,0x24,0xb4, /* "autotrim" */ 
	0x1,0xc2,0x66, /* "axis" */ 
	0x1,0x6,0x80, /* "bat" */ 
	0x11,0x52,0x47,0xd4, /* "beidou" */ 
	0x2,0x48,0x66, /* "bias" */ 
	0x1,0x48,0xa1,0x5c,0x1e,0x97,0x50, /* "breakpoint" */ 
	0x2,0xab,0x60, /* "bump" */ 
	0x1,0x85,0x89,0x14,0x83,0x44,0xbd,0xc0, /* "calibration" */ 
	0x19,0x58,0xc0, /* "cell" */ 
	0xc,0xae,0xa1,0x64, /* "center" */ 
	0x1,0xa0,0x2e, /* "chan" */ 
	0x0,0xd0,0x17,0x38,0xac, /* "channel" */ 
	0x0,0xdb,0x39, /* "cmss" */ 
	0x80,0x6f,0x6b,0x42,0xe2, /* "command" */ 
	0x0,0x6f,0x6c,0xa,0xe9,0x86,0x89,0x7b, /* "compensation" */ 
	0x80,0x37,0xb8,0xc9,0x38, /* "config" */ 
	0x6,0xf7,0x4e,0x81,0x75, /* "constant" */ 
	0x0,0x39,0x26,0x89,0x18,0x58, /* "critical" */ 
	0x1,0xd6,0x56,0x28, /* "curve" */ 
	0x8,0x16,0xc1,0x2e,0x38, /* "damping" */ 
	0x8,0x50,0x90, /* "dead" */ 
	0x4,0x28,0xaa,0x70, /* "debug" */ 
	0x10,0xa3,0x2b,0xb,0x20,0xd1,0x2f,0x70, /* "deceleration" */ 
	0x8,0x51,0xb0, /* "decl" */ 
	0x4,0x28,0xd8,0x97,0x6,0x89,0x7b, /* "declination" */ 
	0x80,0x42,0x98,0x35,0x65, /* "default" */ 
	0x0,0x42,0x98,0x35,0x65,0x26, /* "defaults" */ 
	0x2,0x14,0xf2,0x29,0x66, /* "degrees" */ 
	0x2,0x16,0x85,0x1d,0x12,0xf7, /* "detection" */ 
	0x0,0x89,0x9c,0x18,0x1c,0xf4,0xcf,0x90,0xcb,0xd9,0xdf,0xa2,0x62,0x5c,0xb0, /* "display_force_sw_blink" */ 
	0x11,0xf7,0x70, /* "down" */ 
	0x9,0x3a, /* "dst" */ 
	0x0,0xae,0x20, /* "end" */ 
	0xa,0xe2,0xc8,0xf9, /* "energy" */ 
	0x1,0x5c,0x67,0xc8,0x65, /* "enforce" */ 
	0x1,0x60,0x80, /* "eph" */ 
	0x17,0x14, /* "ext" */ 
	0x1,0x71,0x49,0x7,0xc0, /* "extra1" */ 
	0x2e,0x29,0x20,0xf0, /* "extra2" */ 
	0x5,0xc5,0x24,0x1d, /* "extra3" */ 
	0x80,0xc1,0x1d,0x1f,0x20, /* "factor" */ 
	0x19,0x38,0x29,0x3b,0x74,0xb8,0xfd,0xd,0x68,0xfe,0x86,0x4d, /* "fixed_wing_auto_arm" */ 
	0x1,0x98,0x18,0x16,0x4f,0x70, /* "flaperon" */ 
	0xc,0xc0,0xc2,0x60, /* "flaps" */ 
	0x34,0x2c, /* "fpv" */ 
	0x3,0x4a,0x6b,0xc8, /* "frsky" */ 
	0xd,0x29,0xaf,0x3d,0xac,0xcb,0xd6,0x14,0xe1,0x1e,0x7a,0x78,0x4f,0xad,0x79,0xb,0xd9,0x95,0xd3,0x7c,0xba,0x92,0x4c, /* "frsky_use_legacy_gps_mode_sensor_ids" */ 
	0x6,0x98, /* "fs" */ 
	0xd,0x52,0xb0, /* "fuel" */ 
	0x6,0xbf,0x53,0x42,0xc9,0xbd,0x63,0xc6,0xbe,0x95,0xc7,0x9,0xcb,0xda,0x22,0x45,0x9a,0x1e,0xc2, /* "fw_iterm_lock_engage_threshold" */ 
	0x0,0xd7,0xea,0x68,0x59,0x37,0xac,0x78,0xd7,0xda,0x25,0xa5,0xeb,0x43,0x8e,0xb6,0x60, /* "fw_iterm_lock_time_max_ms" */ 
	0x35,0xfb,0x90,0xdf,0xa9,0xa1,0x64,0xde,0x9a,0x45,0x2e,0x8b,0xd1,0x5,0xcb,0xe8,0x5c,0x76,0x14, /* "fw_yaw_iterm_freeze_bank_angle" */ 
	0x7,0xb,0x12,0xc2,0xbc, /* "galileo" */ 
	0x7,0x63,0xdc,0x19,0xcc, /* "glonass" */ 
	0x7,0x93,0xea,0xe2, /* "ground" */ 
	0x0,0xf9,0x93,0xfa,0x17,0x51,0x3d,0xb,0x12,0x19,0xa5,0xc7,0xeb,0x20,0x6e,0xa3,0x40, /* "gyro_anti_aliasing_lpf_hz" */ 
	0x3e,0x64,0xfe,0xb2,0xac,0xaf,0x66,0x16,0xc1,0x85,0xe8,0xdf,0x57,0x50, /* "gyro_lulu_sample_count" */ 
	0x8,0xc, /* "has" */ 
	0xc0,0x84,0x9d,0x0, /* "high" */ 
	0x43,0xe9,0x4e,0x85,0x81,0x93,0x7b,0x37,0xd5,0xc4,0xea,0x5d,0x42,0xca,0xc1,0x60, /* "hott_alarm_sound_interval" */ 
	0x10,0xfb,0x16,0x40, /* "hover" */ 
	0x48,0xab,0x30, /* "ibus" */ 
	0x25,0xc5,0x95,0x12,0x10, /* "inertia" */ 
	0x25,0xc9,0xa0, /* "init" */ 
	0x12,0xe9, /* "ins" */ 
	0x81,0x2e,0xa1,0x65,0x60,0xb0, /* "interval" */ 
	0xc,0x29, /* "led" */ 
	0x0,0xc4,0xb9,0x69,0x71, /* "linking" */ 
	0xc0,0xc7,0x8d,0x60, /* "lock" */ 
	0x63,0xdf,0xa,0x25,0xa5, /* "looptime" */ 
	0x3,0x28,0xd0, /* "ltm" */ 
	0x32,0xac,0xa8, /* "lulu" */ 
	0x1a,0x14,0xb8, /* "main" */ 
	0xd,0xc,0x8e,0x97, /* "margin" */ 
	0x1,0xa5,0xa2,0x1e,0x40, /* "method" */ 
	0x35,0x24, /* "mid" */ 
	0x3,0x53,0x80, /* "mix" */ 
	0x35,0xe4,0x2f,0x64,0x17,0x1c,0xbd,0x63,0xce,0x91,0xf5,0xf0,0x2c,0x83,0x47,0xc8, /* "mode_range_logic_operator" */ 
	0xd,0x7d,0x1f,0x29,0xd1,0xf0, /* "motorstop" */ 
	0x3,0x83,0x6e,0x97,0x14,0x90,0x7a,0x19,0x35,0x2e,0x3f,0x66,0x13,0x16,0x99, /* "nav_extra_arming_safety" */ 
	0x3,0x83,0x6e,0x9a,0xfd,0xb,0x18,0xfb,0xf5,0xa1,0x75,0x42,0xce,0xd1,0x12,0xea,0x5c,0x39,0x14,0x33,0x28, /* "nav_fw_allow_manual_thr_increase" */ 
	0x1c,0x1b,0x74,0xd7,0xeb,0x3,0x57,0xd,0x1d,0xba,0x4e,0x76,0x17,0xb4,0x7f,0x6e,0x15,0x97,0xa9,0x23,0xa, /* "nav_fw_launch_wiggle_to_wake_idle" */ 
	0x7,0x6,0xdd,0x35,0xfb,0x7,0xcf,0xa8,0x21,0xfb,0x4,0x92,0x75,0x6f,0x58,0x96,0xa6,0x80, /* "nav_fw_pos_hdg_pidsum_limit" */ 
	0x70,0x6d,0xd3,0x5f,0xb3,0x78,0x64,0x97,0x1f,0xad,0x7d,0x1f,0x2e,0xce,0x8f,0x80, /* "nav_fw_soaring_motor_stop" */ 
	0x1c,0x1b,0x74,0xd7,0xed,0xe1,0xda,0x48,0x23,0x5a,0x5c,0x7e,0x84,0x63,0xac,0x82,0x3c, /* "nav_fw_wp_tracking_accuracy" */ 
	0x81,0xc1,0xb7,0x4d,0x7e,0xde,0x1d,0xa4,0x82,0x35,0xa5,0xc7,0xeb,0x43,0x8e,0x85,0xc7,0x61, /* "nav_fw_wp_tracking_max_angle" */ 
	0x40,0xe0,0xdb,0xad,0xe,0x3b,0x42,0xca,0x41,0x4b,0xba,0x67,0xb1,0x8f,0xbf,0x42,0xca, /* "nav_max_terrain_follow_alt" */ 
	0x1,0xc1,0xb7,0x5a,0x3e,0xa5,0xd6,0x2c,0xa8,0x52,0x74,0x72,0xc,0xd1,0xd2,0x16,0x85,0x1d,0x12,0xf7, /* "nav_mc_inverted_crash_detection" */ 
	0x1,0xc1,0xb7,0x5a,0x3e,0xd8,0xac,0xee,0x33,0xd2,0x50,0xb2,0x6f,0x43,0x4a,0x15,0xd5,0xd,0x12,0xf7, /* "nav_mc_vel_xy_dterm_attenuation" */ 
	0x1,0xc1,0xb7,0x5a,0x3e,0xd8,0xac,0xee,0x33,0xd2,0x50,0xb2,0x6f,0x43,0x4a,0x15,0xd5,0xd,0x12,0xf7,0x74,0xae,0x20, /* "nav_mc_vel_xy_dterm_attenuation_end" */ 
	0x1c,0x1b,0x75,0xa3,0xed,0x8a,0xce,0xe3,0x3d,0x25,0xb,0x26,0xf4,0x34,0xa1,0x5d,0x50,0xd1,0x2f,0x77,0x67,0x40,0xca,0x80, /* "nav_mc_vel_xy_dterm_attenuation_start" */ 
	0x70,0x6d,0xd6,0x8f,0xb6,0x2b,0x3b,0x8c,0xf4,0x94,0x2c,0x9b,0xd6,0x40,0xdd,0x46, /* "nav_mc_vel_xy_dterm_lpf_hz" */ 
	0x80,0xe0,0xdb,0xb2,0xa2,0x3a,0x36,0x25,0xa2,0xe9,0x93,0x29,0xd3,0xb3,0xa0,0x4e,0x5e,0x85,0x94,0x4d,0x2a,0x42, /* "nav_rth_climb_first_stage_altitude" */ 
	0x81,0xc1,0xb7,0x65,0x44,0x74,0x6c,0x4b,0x45,0xd3,0x26,0x53,0xa7,0x67,0x40,0x9c,0xbd,0x6b,0xc8,0x50, /* "nav_rth_climb_first_stage_mode" */ 
	0x38,0x36,0xec,0xa8,0x8e,0xb1,0x2e,0x28,0x65,0xd2,0x16,0x63,0x2b,0xa9,0xd9,0xd0,0x32,0xa7,0x48,0x99,0xd0,0x2e,0x19, /* "nav_rth_linear_descent_start_distance" */ 
	0x40,0xe0,0xdb,0xb2,0xa2,0x3b,0x59,0x97,0xac,0x4b,0x8a,0x19,0x74,0x85,0x98,0xca,0xea, /* "nav_rth_use_linear_descent" */ 
	0x1,0xc1,0xb7,0x6f,0xe,0xb1,0xe1,0x27,0x5e,0xee,0x89,0xef,0xa0, /* "nav_wp_load_on_boot" */ 
	0x1c,0x5a,0xd2,0x41,0x60, /* "neutral" */ 
	0x1e,0x63, /* "off" */ 
	0x1,0xf2,0x49,0x5d,0x40,0xd1,0x2f,0x70, /* "orientation" */ 
	0x1f,0x62,0xca,0x49,0x21, /* "override" */ 
	0x40,0xfb,0x16,0x52,0x49,0xb,0x30, /* "overrides" */ 
	0x40,0xb2,0x19,0x5d,0x40, /* "percent" */ 
	0x41,0x2c,0x7d, /* "pilot" */ 
	0x1,0x4,0xb8, /* "pin" */ 
	0x10,0x4d, /* "pit" */ 
	0x1,0x6,0x5,0xce,0x2c, /* "planner" */ 
	0x81,0x6,0x6,0x86,0x7c,0x9a, /* "platform" */ 
	0x8,0x3d,0x85,0x98, /* "poles" */ 
	0x20,0xfb, /* "pow" */ 
	0x82,0x12,0x28,0x64,0xd0, /* "prearm" */ 
	0x42,0x45,0xb2,0x4b,0x70, /* "preview" */ 
	0x42,0x4f,0xb2,0x48,0x59, /* "provider" */ 
	0x2,0x15,0x64,0xca, /* "pulse" */ 
	0x9,0x4,0x89,0x78, /* "radio" */ 
	0x24,0x1a,0x25,0xe0, /* "ratio" */ 
	0x91,0x46,0x54,0xd8,0xb2, /* "receiver" */ 
	0x4,0x8a,0x35,0xbd,0xc9,0x71, /* "reckoning" */ 
	0xc1,0x22,0x8d,0xf6,0x2c,0xb2, /* "recovery" */ 
	0x9,0x14,0xc5,0x91,0x5c,0x32, /* "reference" */ 
	0x82,0x45,0x83,0xe5,0x40, /* "report" */ 
	0x48,0xb3,0xa0,0x65,0x40, /* "restart" */ 
	0x49,0x8c, /* "rll" */ 
	0x4,0x9f,0x40,0xd1,0x2f,0x70, /* "rotation" */ 
	0x26,0x13,0x14, /* "safe" */ 
	0x13,0xd,0x26, /* "sats" */ 
	0x9,0x88,0x33, /* "sbas" */ 
	0x4,0xc5,0x59, /* "sbus" */ 
	0x82,0x65,0x74,0xd3,0x44,0xd9,0x34,0xc8, /* "sensitivity" */ 
	0x26,0x57,0x4d,0xf2, /* "sensor" */ 
	0x4,0xcb,0x24,0x85,0x92,0xc0, /* "serialrx" */ 
	0x26,0xc7,0xc0,0xa0, /* "slope" */ 
	0x9b,0x42,0xc6, /* "small" */ 
	0x2,0x6d,0xc,0xa9,0x7,0xca,0x80, /* "smartport" */ 
	0x9b,0x5e,0xfa,0x21,0xc5,0x9c, /* "smoothness" */ 
	0xc1,0x37,0x6,0x10,0x4b,0x8b,0x39, /* "snappiness" */ 
	0x82,0x6f,0xc,0x92,0xe3, /* "soaring" */ 
	0x82,0x6f,0xac,0x86,0x50, /* "source" */ 
	0x4e,0x9,0x75,0x60, /* "spinup" */ 
	0x9,0xc8,0x60, /* "src" */ 
	0x9d,0x2,0x24,0xb1,0x34,0xc8, /* "stability" */ 
	0x27,0x40,0xd2,0xb3, /* "status" */ 
	0x4,0xe8,0x91,0xac, /* "stick" */ 
	0x13,0xa3,0xe0, /* "stop" */ 
	0x9,0xd2,0x40, /* "str" */ 
	0x9d,0x61,0x7,0xca,0x85,0x20, /* "supported" */ 
	0x27,0x97,0xc, /* "sync" */ 
	0x13,0xcc,0xd2,0x40, /* "sysid" */ 
	0x50,0x29,0x60, /* "tail" */ 
	0x28,0x14,0xb2,0x69,0xa5,0xb,0x20, /* "tailsitter" */ 
	0x51,0x12,0x7d, /* "throw" */ 
	0xc1,0x44,0xb2,0x80, /* "tilt" */ 
	0xa2,0x5a,0x59, /* "timer" */ 
	0x2,0x8f,0x71, /* "tone" */ 
	0x41,0x49,0x5,0xd3, /* "trans" */ 
	0x5,0x24,0x90, /* "tri" */ 
	0x52,0x49,0x68, /* "trim" */ 
	0x29,0x81,0x54,0xc6,0x2c, /* "txbuffer" */ 
	0x81,0x57,0x6,0x4d,0x29, /* "unarmed" */ 
	0x1,0x58,0x10,0x34,0x28, /* "update" */ 
	0x2b,0x30,0x9c,0xa0, /* "usage" */ 
	0xac,0xcb,0x20, /* "user" */ 
	0x58,0xac,0x78,0xd3,0x4c, /* "velocity" */ 
	0x82,0xc5,0x94,0xd2,0xf7, /* "version" */ 
	0x2,0xe1,0x93,0x92,0xe3, /* "warning" */ 
	0x82,0xe9,0x71,0x6,0xf6,0xc0, /* "windcomp" */ 
	0x17,0x4b,0x89,0x58, /* "windup" */ 
	0x0,0x00
};
static const char wordSymbols[] = {'3','2','_','1',};
const char * const table_acc_hardware[] = {
	"NONE",
	"AUTO",
	"MPU6000",
	"MPU6500",
	"MPU9250",
	"BMI160",
	"ICM20689",
	"BMI088",
	"ICM42605",
	"BMI270",
	"LSM6DXX",
	"FAKE",
};
const char * const table_airmodeHandlingType[] = {
	"STICK_CENTER",
	"THROTTLE_THRESHOLD",
	"STICK_CENTER_ONCE",
};
const char * const table_alignment[] = {
	"DEFAULT",
	"CW0",
	"CW90",
	"CW180",
	"CW270",
	"CW0FLIP",
	"CW90FLIP",
	"CW180FLIP",
	"CW270FLIP",
};
const char * const table_aux_operator[] = {
	"OR",
	"AND",
};
const char * const table_baro_hardware[] = {
	"NONE",
	"AUTO",
	"BMP085",
	"MS5611",
	"BMP280",
	"MS5607",
	"LPS25H",
	"SPL06",
	"BMP388",
	"DPS310",
	"B2SMPB",
	"MSP",
	"FAKE",
};
const char * const table_bat_capacity_unit[] = {
	"MAH",
	"MWH",
};
const char * const table_bat_voltage_source[] = {
	"RAW",
	"SAG_COMP",
};
const char * const table_current_sensor[] = {
	"NONE",
	"ADC",
	"VIRTUAL",
	"FAKE",
	"ESC",
	"SMARTPORT",
	"CAN",
};
const char * const table_debug_modes[] = {
	"NONE",
	"AGL",
	"FLOW_RAW",
	"FLOW",
	"ALWAYS",
	"SAG_COMP_VOLTAGE",
	"VIBE",
	"CRUISE",
	"REM_FLIGHT_TIME",
	"SMARTAUDIO",
	"ACC",
	"NAV_YAW",
	"PCF8574",
	"DYN_GYRO_LPF",
	"AUTOLEVEL",
	"ALTITUDE",
	"AUTOTRIM",
	"AUTOTUNE",
	"RATE_DYNAMICS",
	"LANDING",
	"POS_EST",
	"ADAPTIVE_FILTER",
	"HEADTRACKER",
	"GPS",
	"LULU",
	"SBUS2",
};
const char * const table_default_altitude_source[] = {
	"GPS",
	"BARO",
	"GPS_ONLY",
	"BARO_ONLY",
};
const char * const table_direction[] = {
	"RIGHT",
	"LEFT",
	"YAW",
};
const char * const table_failsafe_procedure[] = {
	"LAND",
	"DROP",
	"RTH",
	"NONE",
};
const char * const table_filter_type[] = {
	"PT1",
	"BIQUAD",
};
const char * const table_filter_type_full[] = {
	"PT1",
	"BIQUAD",
	"PT2",
	"PT3",
	"LULU",
};
const char * const table_gps_auto_baud_max[] = {
	"115200",
	"57600",
	"38400",
	"19200",
	"9600",
	"230400",
	"460800",
	"921600",
};
const char * const table_gps_dyn_model[] = {
	"PEDESTRIAN",
	"AUTOMOTIVE",
	"AIR_1G",
	"AIR_2G",
	"AIR_4G",
	"SEA",
	"MOWER",
};
const char * const table_gps_provider[] = {
	"UBLOX",
	"MSP",
	"FAKE",
	"DRONECAN",
};
const char * const table_gps_sbas_mode[] = {
	"AUTO",
	"EGNOS",
	"WAAS",
	"MSAS",
	"GAGAN",
	"SPAN",
	"NONE",
};
const char * const table_gyro_filter_mode[] = {
	"OFF",
	"STATIC",
	"DYNAMIC",
	"ADAPTIVE",
};
const char * const table_imu_inertia_comp_method[] = {
	"VELNED",
	"TURNRATE",
	"ADAPTIVE",
};
const char * const table_iterm_relax[] = {
	"OFF",
	"RP",
	"RPY",
};
const char * const table_led_pin_pwm_mode[] = {
	"SHARED_LOW",
	"SHARED_HIGH",
	"LOW",
	"HIGH",
};
const char * const table_ltm_rates[] = {
	"NORMAL",
	"MEDIUM",
	"SLOW",
};
const char * const table_mag_hardware[] = {
	"NONE",
	"AUTO",
	"HMC5883",
	"AK8975",
	"MAG3110",
	"AK8963",
	"IST8310",
	"QMC5883",
	"QMC5883P",
	"MPU9250",
	"IST8308",
	"LIS3MDL",
	"MSP",
	"RM3100",
	"VCM5883",
	"MLX90393",
	"FAKE",
};
const char * const table_mavlink_autopilot_type[] = {
	"GENERIC",
	"ARDUPILOT",
};
const char * const table_mavlink_radio_type[] = {
	"GENERIC",
	"ELRS",
	"SIK",
};
const char * const table_motor_pwm_protocol[] = {
	"STANDARD",
	"ONESHOT125",
	"MULTISHOT",
	"BRUSHED",
	"DSHOT150",
	"DSHOT300",
	"DSHOT600",
};
const char * const table_nav_extra_arming_safety[] = {
	"ON",
	"ALLOW_BYPASS",
};
const char * const table_nav_fw_wp_turn_smoothing[] = {
	"OFF",
	"ON",
	"ON-CUT",
};
const char * const table_nav_mc_althold_throttle[] = {
	"STICK",
	"MID_STICK",
	"HOVER",
};
const char * const table_nav_overrides_motor_stop[] = {
	"OFF_ALWAYS",
	"OFF",
	"AUTO_ONLY",
	"ALL_NAV",
};
const char * const table_nav_rth_allow_landing[] = {
	"NEVER",
	"ALWAYS",
	"FS_ONLY",
};
const char * const table_nav_rth_alt_mode[] = {
	"CURRENT",
	"EXTRA",
	"FIXED",
	"MAX",
	"AT_LEAST",
};
const char * const table_nav_rth_climb_first[] = {
	"OFF",
	"ON",
	"ON_FW_SPIRAL",
};
const char * const table_nav_rth_climb_first_stage_modes[] = {
	"AT_LEAST",
	"EXTRA",
};
const char * const table_nav_user_control_mode[] = {
	"ATTI",
	"CRUISE",
};
const char * const table_nav_wp_mission_restart[] = {
	"START",
	"RESUME",
	"SWITCH",
};
const char * const table_off_on[] = {
	"OFF",
	"ON",
};
const char * const table_pidTypeTable[] = {
	"NONE",
	"PID",
	"PIFF",
	"AUTO",
};
const char * const table_platform_type[] = {
	"MULTIROTOR",
	"AIRPLANE",
	"HELICOPTER",
	"TRICOPTER",
	"ROVER",
	"BOAT",
};
const char * const table_receiver_type[] = {
	"NONE",
	"SERIAL",
	"MSP",
	"SIM (SITL)",
};
const char * const table_reset_type[] = {
	"NEVER",
	"FIRST_ARM",
	"EACH_ARM",
};
const char * const table_rssi_source[] = {
	"NONE",
	"AUTO",
	"ADC",
	"CHANNEL",
	"PROTOCOL",
	"MSP",
};
const char * const table_rth_trackback_mode[] = {
	"OFF",
	"ON",
	"FS",
};
const char * const table_safehome_usage_mode[] = {
	"OFF",
	"RTH",
	"RTH_FS",
};
const char * const table_servo_protocol[] = {
	"PWM",
	"SBUS",
	"SBUS_PWM",
};
const char * const table_smartport_fuel_unit[] = {
	"PERCENT",
	"MAH",
	"MWH",
};
const char * const table_tristate[] = {
	"AUTO",
	"ON",
	"OFF",
};
const char * const table_tz_automatic_dst[] = {
	"OFF",
	"EU",
	"USA",
};
static const lookupTableEntry_t settingLookupTables[] = {
	{ table_acc_hardware, sizeof(table_acc_hardware) / sizeof(char*) },
	{ table_airmodeHandlingType, sizeof(table_airmodeHandlingType) / sizeof(char*) },
	{ table_alignment, sizeof(table_alignment) / sizeof(char*) },
	{ table_aux_operator, sizeof(table_aux_operator) / sizeof(char*) },
	{ table_baro_hardware, sizeof(table_baro_hardware) / sizeof(char*) },
	{ table_bat_capacity_unit, sizeof(table_bat_capacity_unit) / sizeof(char*) },
	{ table_bat_voltage_source, sizeof(table_bat_voltage_source) / sizeof(char*) },
	{ table_current_sensor, sizeof(table_current_sensor) / sizeof(char*) },
	{ table_debug_modes, sizeof(table_debug_modes) / sizeof(char*) },
	{ table_default_altitude_source, sizeof(table_default_altitude_source) / sizeof(char*) },
	{ table_direction, sizeof(table_direction) / sizeof(char*) },
	{ table_failsafe_procedure, sizeof(table_failsafe_procedure) / sizeof(char*) },
	{ table_filter_type, sizeof(table_filter_type) / sizeof(char*) },
	{ table_filter_type_full, sizeof(table_filter_type_full) / sizeof(char*) },
	{ table_gps_auto_baud_max, sizeof(table_gps_auto_baud_max) / sizeof(char*) },
	{ table_gps_dyn_model, sizeof(table_gps_dyn_model) / sizeof(char*) },
	{ table_gps_provider, sizeof(table_gps_provider) / sizeof(char*) },
	{ table_gps_sbas_mode, sizeof(table_gps_sbas_mode) / sizeof(char*) },
	{ table_gyro_filter_mode, sizeof(table_gyro_filter_mode) / sizeof(char*) },
	{ table_imu_inertia_comp_method, sizeof(table_imu_inertia_comp_method) / sizeof(char*) },
	{ table_iterm_relax, sizeof(table_iterm_relax) / sizeof(char*) },
	{ table_led_pin_pwm_mode, sizeof(table_led_pin_pwm_mode) / sizeof(char*) },
	{ table_ltm_rates, sizeof(table_ltm_rates) / sizeof(char*) },
	{ table_mag_hardware, sizeof(table_mag_hardware) / sizeof(char*) },
	{ table_mavlink_autopilot_type, sizeof(table_mavlink_autopilot_type) / sizeof(char*) },
	{ table_mavlink_radio_type, sizeof(table_mavlink_radio_type) / sizeof(char*) },
	{ table_motor_pwm_protocol, sizeof(table_motor_pwm_protocol) / sizeof(char*) },
	{ table_nav_extra_arming_safety, sizeof(table_nav_extra_arming_safety) / sizeof(char*) },
	{ table_nav_fw_wp_turn_smoothing, sizeof(table_nav_fw_wp_turn_smoothing) / sizeof(char*) },
	{ table_nav_mc_althold_throttle, sizeof(table_nav_mc_althold_throttle) / sizeof(char*) },
	{ table_nav_overrides_motor_stop, sizeof(table_nav_overrides_motor_stop) / sizeof(char*) },
	{ table_nav_rth_allow_landing, sizeof(table_nav_rth_allow_landing) / sizeof(char*) },
	{ table_nav_rth_alt_mode, sizeof(table_nav_rth_alt_mode) / sizeof(char*) },
	{ table_nav_rth_climb_first, sizeof(table_nav_rth_climb_first) / sizeof(char*) },
	{ table_nav_rth_climb_first_stage_modes, sizeof(table_nav_rth_climb_first_stage_modes) / sizeof(char*) },
	{ table_nav_user_control_mode, sizeof(table_nav_user_control_mode) / sizeof(char*) },
	{ table_nav_wp_mission_restart, sizeof(table_nav_wp_mission_restart) / sizeof(char*) },
	{ table_off_on, sizeof(table_off_on) / sizeof(char*) },
	{ table_pidTypeTable, sizeof(table_pidTypeTable) / sizeof(char*) },
	{ table_platform_type, sizeof(table_platform_type) / sizeof(char*) },
	{ table_receiver_type, sizeof(table_receiver_type) / sizeof(char*) },
	{ table_reset_type, sizeof(table_reset_type) / sizeof(char*) },
	{ table_rssi_source, sizeof(table_rssi_source) / sizeof(char*) },
	{ table_rth_trackback_mode, sizeof(table_rth_trackback_mode) / sizeof(char*) },
	{ table_safehome_usage_mode, sizeof(table_safehome_usage_mode) / sizeof(char*) },
	{ table_servo_protocol, sizeof(table_servo_protocol) / sizeof(char*) },
	{ table_smartport_fuel_unit, sizeof(table_smartport_fuel_unit) / sizeof(char*) },
	{ table_tristate, sizeof(table_tristate) / sizeof(char*) },
	{ table_tz_automatic_dst, sizeof(table_tz_automatic_dst) / sizeof(char*) },
};
static const uint32_t settingMinMaxTable[] = {
	0,
	255,
	100,
	1000,
	2000,
	10,
	200,
	1,
	32767,
	-32768,
	5,
	50,
	2,
	500,
	5000,
	10000,
	65000,
	-1800,
	15,
	3600,
	65535,
	20,
	180,
	250,
	80,
	60000,
	4294967295,
	-5000,
	4,
	30,
	90,
	120,
	300,
	900,
	8192,
	-800,
	-50,
	-1,
	9,
	16,
	25,
	40,
	45,
	51,
	400,
	450,
	750,
	800,
	2250,
	9999,
	500000,
	-18000,
	-10000,
	-1000,
	-720,
	-20,
	-10,
	3,
	6,
	32,
	34,
	60,
	99,
	175,
	498,
	600,
	840,
	1350,
	1500,
	1800,
	2500,
	4000,
	6000,
	9000,
	18000,
	20000,
	30000,
	32000,
};
typedef uint8_t setting_min_max_idx_t;
#define SETTING_INDEXES_GET_MIN(val) (val->config.minmax.indexes[0])
#define SETTING_INDEXES_GET_MAX(val) (val->config.minmax.indexes[1])
static const setting_t settingsTable[] = {
	// PG_GYRO_CONFIG
	{ {246, 1, 0, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 73}, (setting_offset_t)offsetof(gyroConfig_t, looptime) },
	{ {232, 1, 0, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 3}, (setting_offset_t)offsetof(gyroConfig_t, gyro_anti_aliasing_lpf_hz) },
	{ {31, 248, 1, 91, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(gyroConfig_t, gyroLuluEnabled) },
	{ {233, 1, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {7, 18}, (setting_offset_t)offsetof(gyroConfig_t, gyroLuluSampleCount) },
	{ {31, 249, 1, 24, 23, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 13}, (setting_offset_t)offsetof(gyroConfig_t, gyro_main_lpf_hz) },
	{ {31, 59, 37, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_GYRO_FILTER_MODE }, (setting_offset_t)offsetof(gyroConfig_t, gyroFilterMode) },
	{ {31, 76, 24, 15, 23, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {41, 44}, (setting_offset_t)offsetof(gyroConfig_t, gyroDynamicLpfMinHz) },
	{ {31, 76, 24, 12, 23, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {41, 3}, (setting_offset_t)offsetof(gyroConfig_t, gyroDynamicLpfMaxHz) },
	{ {31, 76, 24, 195, 1, 40}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {7, 5}, (setting_offset_t)offsetof(gyroConfig_t, gyroDynamicLpfCurveExpo) },
	{ {240, 1, 31, 88, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(gyroConfig_t, init_gyro_cal_enabled) },
	{ {31, 115, 67, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {9, 8}, (setting_offset_t)offsetof(gyroConfig_t, gyro_zero_cal[X]) },
	{ {31, 115, 68, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {9, 8}, (setting_offset_t)offsetof(gyroConfig_t, gyro_zero_cal[Y]) },
	{ {31, 115, 9, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {9, 8}, (setting_offset_t)offsetof(gyroConfig_t, gyro_zero_cal[Z]) },
	{ {241, 1, 134, 1, 189, 1}, VAR_FLOAT | MASTER_VALUE, .config.minmax.indexes = {0, 4}, (setting_offset_t)offsetof(gyroConfig_t, gravity_cmss_cal) },
	// PG_ACCELEROMETER_CONFIG
	{ {34, 146, 1, 23, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(accelerometerConfig_t, acc_notch_hz) },
	{ {34, 146, 1, 124, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {7, 1}, (setting_offset_t)offsetof(accelerometerConfig_t, acc_notch_cutoff) },
	{ {34, 93, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_ACC_HARDWARE }, (setting_offset_t)offsetof(accelerometerConfig_t, acc_hardware) },
	{ {34, 24, 23, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 6}, (setting_offset_t)offsetof(accelerometerConfig_t, acc_lpf_hz) },
	{ {34, 24, 26, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_FILTER_TYPE }, (setting_offset_t)offsetof(accelerometerConfig_t, acc_soft_lpf_type) },
	{ {34, 159, 1, 123, 0, 0}, VAR_FLOAT | MASTER_VALUE, .config.minmax.indexes = {36, 43}, (setting_offset_t)offsetof(accelerometerConfig_t, acc_temp_correction) },
	{ {85, 67, 0, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {9, 8}, (setting_offset_t)offsetof(accelerometerConfig_t, accZero.raw[X]) },
	{ {85, 68, 0, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {9, 8}, (setting_offset_t)offsetof(accelerometerConfig_t, accZero.raw[Y]) },
	{ {85, 9, 0, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {9, 8}, (setting_offset_t)offsetof(accelerometerConfig_t, accZero.raw[Z]) },
	{ {84, 67, 0, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {7, 34}, (setting_offset_t)offsetof(accelerometerConfig_t, accGain.raw[X]) },
	{ {84, 68, 0, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {7, 34}, (setting_offset_t)offsetof(accelerometerConfig_t, accGain.raw[Y]) },
	{ {84, 9, 0, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {7, 34}, (setting_offset_t)offsetof(accelerometerConfig_t, accGain.raw[Z]) },
	// PG_COMPASS_CONFIG
	{ {43, 32, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_ALIGNMENT }, (setting_offset_t)offsetof(compassConfig_t, mag_align) },
	{ {32, 93, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_MAG_HARDWARE }, (setting_offset_t)offsetof(compassConfig_t, mag_hardware) },
	{ {32, 201, 1, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {51, 74}, (setting_offset_t)offsetof(compassConfig_t, mag_declination) },
	{ {100, 67, 0, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {9, 8}, (setting_offset_t)offsetof(compassConfig_t, magZero.raw[X]) },
	{ {100, 68, 0, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {9, 8}, (setting_offset_t)offsetof(compassConfig_t, magZero.raw[Y]) },
	{ {100, 9, 0, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {9, 8}, (setting_offset_t)offsetof(compassConfig_t, magZero.raw[Z]) },
	{ {99, 67, 0, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {9, 8}, (setting_offset_t)offsetof(compassConfig_t, magGain[X]) },
	{ {99, 68, 0, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {9, 8}, (setting_offset_t)offsetof(compassConfig_t, magGain[Y]) },
	{ {99, 9, 0, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {9, 8}, (setting_offset_t)offsetof(compassConfig_t, magGain[Z]) },
	{ {32, 184, 1, 48, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {21, 31}, (setting_offset_t)offsetof(compassConfig_t, magCalibrationTimeLimit) },
	{ {43, 32, 14, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {17, 19}, (setting_offset_t)offsetof(compassConfig_t, rollDeciDegrees) },
	{ {43, 32, 8, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {17, 19}, (setting_offset_t)offsetof(compassConfig_t, pitchDeciDegrees) },
	{ {43, 32, 5, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {17, 19}, (setting_offset_t)offsetof(compassConfig_t, yawDeciDegrees) },
	// PG_BAROMETER_CONFIG
	{ {52, 93, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_BARO_HARDWARE }, (setting_offset_t)offsetof(barometerConfig_t, baro_hardware) },
	{ {52, 88, 160, 1, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 3}, (setting_offset_t)offsetof(barometerConfig_t, baro_calibration_tolerance) },
	{ {52, 159, 1, 123, 0, 0}, VAR_FLOAT | MASTER_VALUE, .config.minmax.indexes = {36, 43}, (setting_offset_t)offsetof(barometerConfig_t, baro_temp_correction) },
	// PG_RX_CONFIG
	{ {165, 2, 26, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_RECEIVER_TYPE }, (setting_offset_t)offsetof(rxConfig_t, receiverType) },
	{ {15, 122, 0, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {3, 4}, (setting_offset_t)offsetof(rxConfig_t, mincheck) },
	{ {12, 122, 0, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {3, 4}, (setting_offset_t)offsetof(rxConfig_t, maxcheck) },
	{ {79, 186, 2, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_RSSI_SOURCE }, (setting_offset_t)offsetof(rxConfig_t, rssi_source) },
	{ {79, 188, 1, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 60}, (setting_offset_t)offsetof(rxConfig_t, rssi_channel) },
	{ {79, 15, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(rxConfig_t, rssiMin) },
	{ {79, 12, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(rxConfig_t, rssiMax) },
	{ {176, 2, 195, 2, 242, 1}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {13, 15}, (setting_offset_t)offsetof(rxConfig_t, sbusSyncInterval) },
	{ {42, 59, 24, 23, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {18, 23}, (setting_offset_t)offsetof(rxConfig_t, rcFilterFrequency) },
	{ {42, 59, 27, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(rxConfig_t, autoSmooth) },
	{ {42, 59, 110, 217, 1, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {7, 2}, (setting_offset_t)offsetof(rxConfig_t, autoSmoothFactor) },
	{ {156, 1, 15, 164, 1, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {46, 48}, (setting_offset_t)offsetof(rxConfig_t, rx_min_usec) },
	{ {156, 1, 12, 164, 1, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {46, 48}, (setting_offset_t)offsetof(rxConfig_t, rx_max_usec) },
	{ {179, 2, 135, 1, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_TRISTATE }, (setting_offset_t)offsetof(rxConfig_t, halfDuplex) },
	// PG_MOTOR_CONFIG
	{ {15, 190, 1, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 4}, (setting_offset_t)offsetof(motorConfig_t, mincommand) },
	{ {47, 64, 4, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {11, 77}, (setting_offset_t)offsetof(motorConfig_t, motorPwmRate) },
	{ {47, 64, 151, 1, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_MOTOR_PWM_PROTOCOL }, (setting_offset_t)offsetof(motorConfig_t, motorPwmProtocol) },
	{ {47, 157, 2, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {28, 1}, (setting_offset_t)offsetof(motorConfig_t, motorPoleCount) },
	// PG_FAILSAFE_CONFIG
	{ {18, 29, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 6}, (setting_offset_t)offsetof(failsafeConfig_t, failsafe_delay) },
	{ {18, 167, 2, 29, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 6}, (setting_offset_t)offsetof(failsafeConfig_t, failsafe_recovery_delay) },
	{ {18, 147, 2, 29, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 6}, (setting_offset_t)offsetof(failsafeConfig_t, failsafe_off_delay) },
	{ {18, 33, 98, 29, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 32}, (setting_offset_t)offsetof(failsafeConfig_t, failsafe_throttle_low_delay) },
	{ {18, 149, 1, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_FAILSAFE_PROCEDURE }, (setting_offset_t)offsetof(failsafeConfig_t, failsafe_procedure) },
	{ {18, 191, 2, 65, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 13}, (setting_offset_t)offsetof(failsafeConfig_t, failsafe_stick_motion_threshold) },
	{ {18, 2, 14, 22, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {35, 47}, (setting_offset_t)offsetof(failsafeConfig_t, failsafe_fw_roll_angle) },
	{ {18, 2, 8, 22, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {35, 47}, (setting_offset_t)offsetof(failsafeConfig_t, failsafe_fw_pitch_angle) },
	{ {18, 2, 5, 4, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {53, 3}, (setting_offset_t)offsetof(failsafeConfig_t, failsafe_fw_yaw_rate) },
	{ {18, 15, 53, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 16}, (setting_offset_t)offsetof(failsafeConfig_t, failsafe_min_distance) },
	{ {18, 15, 53, 149, 1, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_FAILSAFE_PROCEDURE }, (setting_offset_t)offsetof(failsafeConfig_t, failsafe_min_distance_procedure) },
	{ {18, 102, 29, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {37, 65}, (setting_offset_t)offsetof(failsafeConfig_t, failsafe_mission_delay) },
	// PG_BOARD_ALIGNMENT
	{ {43, 87, 14, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {17, 19}, (setting_offset_t)offsetof(boardAlignment_t, rollDeciDegrees) },
	{ {43, 87, 8, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {17, 19}, (setting_offset_t)offsetof(boardAlignment_t, pitchDeciDegrees) },
	{ {43, 87, 5, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {17, 19}, (setting_offset_t)offsetof(boardAlignment_t, yawDeciDegrees) },
	// PG_BATTERY_METERS_CONFIG
	{ {70, 71, 163, 1, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_BAT_CAPACITY_UNIT }, (setting_offset_t)offsetof(batteryMetersConfig_t, capacity_unit) },
	{ {90, 101, 158, 1, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {52, 15}, (setting_offset_t)offsetof(batteryMetersConfig_t, current.scale) },
	{ {90, 101, 78, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {9, 8}, (setting_offset_t)offsetof(batteryMetersConfig_t, current.offset) },
	{ {90, 101, 26, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_CURRENT_SENSOR }, (setting_offset_t)offsetof(batteryMetersConfig_t, current.type) },
	{ {179, 1, 165, 1, 188, 2}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_BAT_VOLTAGE_SOURCE }, (setting_offset_t)offsetof(batteryMetersConfig_t, voltageSource) },
	{ {73, 148, 1, 0, 0, 0}, VAR_UINT32 | MASTER_VALUE, .config.minmax.indexes = {0, 26}, (setting_offset_t)offsetof(batteryMetersConfig_t, cruise_power) },
	{ {77, 148, 1, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 20}, (setting_offset_t)offsetof(batteryMetersConfig_t, idle_power) },
	{ {16, 210, 1, 250, 1, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(batteryMetersConfig_t, rth_energy_margin) },
	{ {38, 89, 167, 1, 0, 0}, VAR_FLOAT | MASTER_VALUE, .config.minmax.indexes = {0, 12}, (setting_offset_t)offsetof(batteryMetersConfig_t, throttle_compensation_weight) },
	// PG_BATTERY_PROFILES
	{ {70, 71, 0, 0, 0, 0}, VAR_UINT32 | BATTERY_CONFIG_VALUE, .config.minmax.indexes = {0, 26}, (setting_offset_t)offsetof(batteryProfile_t, capacity.value) },
	{ {70, 71, 213, 2, 0, 0}, VAR_UINT32 | BATTERY_CONFIG_VALUE, .config.minmax.indexes = {0, 26}, (setting_offset_t)offsetof(batteryProfile_t, capacity.warning) },
	{ {70, 71, 194, 1, 0, 0}, VAR_UINT32 | BATTERY_CONFIG_VALUE, .config.minmax.indexes = {0, 26}, (setting_offset_t)offsetof(batteryProfile_t, capacity.critical) },
	{ {56, 45, 150, 1, 0, 0}, VAR_UINT8 | BATTERY_CONFIG_VALUE, .config.minmax.indexes = {0, 57}, (setting_offset_t)offsetof(batteryProfile_t, controlProfile) },
	{ {33, 158, 1, 0, 0, 0}, VAR_FLOAT | BATTERY_CONFIG_VALUE, .config.minmax.indexes = {0, 7}, (setting_offset_t)offsetof(batteryProfile_t, motor.throttleScale) },
	{ {33, 77, 0, 0, 0, 0}, VAR_FLOAT | BATTERY_CONFIG_VALUE, .config.minmax.indexes = {0, 29}, (setting_offset_t)offsetof(batteryProfile_t, motor.throttleIdle) },
	{ {18, 33, 0, 0, 0, 0}, VAR_UINT16 | BATTERY_CONFIG_VALUE, .config.minmax.indexes = {3, 4}, (setting_offset_t)offsetof(batteryProfile_t, failsafe_throttle) },
	{ {1, 3, 237, 1, 38, 0}, VAR_UINT16 | BATTERY_CONFIG_VALUE, .config.minmax.indexes = {3, 4}, (setting_offset_t)offsetof(batteryProfile_t, nav.mc.hover_throttle) },
	{ {1, 2, 73, 38, 0, 0}, VAR_UINT16 | BATTERY_CONFIG_VALUE, .config.minmax.indexes = {3, 4}, (setting_offset_t)offsetof(batteryProfile_t, nav.fw.cruise_throttle) },
	{ {1, 2, 15, 38, 0, 0}, VAR_UINT16 | BATTERY_CONFIG_VALUE, .config.minmax.indexes = {3, 4}, (setting_offset_t)offsetof(batteryProfile_t, nav.fw.min_throttle) },
	{ {1, 2, 12, 38, 0, 0}, VAR_UINT16 | BATTERY_CONFIG_VALUE, .config.minmax.indexes = {3, 4}, (setting_offset_t)offsetof(batteryProfile_t, nav.fw.max_throttle) },
	{ {1, 2, 107, 0, 0, 0}, VAR_UINT8 | BATTERY_CONFIG_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(batteryProfile_t, nav.fw.pitch_to_throttle) },
	{ {1, 2, 11, 38, 0, 0}, VAR_UINT16 | BATTERY_CONFIG_VALUE, .config.minmax.indexes = {3, 4}, (setting_offset_t)offsetof(batteryProfile_t, nav.fw.launch_throttle) },
	{ {1, 2, 11, 77, 38, 0}, VAR_UINT16 | BATTERY_CONFIG_VALUE, .config.minmax.indexes = {3, 4}, (setting_offset_t)offsetof(batteryProfile_t, nav.fw.launch_idle_throttle) },
	// PG_MIXER_PROFILE
	{ {47, 126, 138, 1, 0, 0}, VAR_UINT8 | MIXER_CONFIG_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(mixerProfile_t, mixer_config.motorDirectionInverted) },
	{ {156, 2, 26, 0, 0, 0}, VAR_UINT8 | MIXER_CONFIG_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_PLATFORM_TYPE }, (setting_offset_t)offsetof(mixerProfile_t, mixer_config.platformType) },
	{ {234, 1, 220, 1, 0, 0}, VAR_UINT8 | MIXER_CONFIG_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(mixerProfile_t, mixer_config.hasFlaps) },
	{ {144, 1, 160, 2, 26, 0}, VAR_INT16 | MIXER_CONFIG_VALUE, .config.minmax.indexes = {37, 8}, (setting_offset_t)offsetof(mixerProfile_t, mixer_config.appliedMixerPreset) },
	{ {255, 1, 106, 98, 0, 0}, VAR_UINT8 | MIXER_CONFIG_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(mixerProfile_t, mixer_config.motorstopOnLow) },
	{ {103, 45, 150, 1, 244, 1}, VAR_UINT8 | MIXER_CONFIG_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(mixerProfile_t, mixer_config.controlProfileLinking) },
	{ {103, 174, 1, 80, 0, 0}, VAR_UINT8 | MIXER_CONFIG_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(mixerProfile_t, mixer_config.automated_switch) },
	{ {103, 80, 203, 2, 201, 2}, VAR_INT16 | MIXER_CONFIG_VALUE, .config.minmax.indexes = {0, 6}, (setting_offset_t)offsetof(mixerProfile_t, mixer_config.switchTransitionTimer) },
	{ {198, 2, 148, 2, 78, 0}, VAR_UINT8 | MIXER_CONFIG_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(mixerProfile_t, mixer_config.tailsitterOrientationOffset) },
	{ {113, 63, 104, 105, 14, 0}, VAR_INT16 | MIXER_CONFIG_VALUE, .config.minmax.indexes = {27, 14}, (setting_offset_t)offsetof(mixerProfile_t, mixer_config.transition_PID_mmix_multiplier_roll) },
	{ {113, 63, 104, 105, 8, 0}, VAR_INT16 | MIXER_CONFIG_VALUE, .config.minmax.indexes = {27, 14}, (setting_offset_t)offsetof(mixerProfile_t, mixer_config.transition_PID_mmix_multiplier_pitch) },
	{ {113, 63, 104, 105, 5, 0}, VAR_INT16 | MIXER_CONFIG_VALUE, .config.minmax.indexes = {27, 14}, (setting_offset_t)offsetof(mixerProfile_t, mixer_config.transition_PID_mmix_multiplier_yaw) },
	// PG_REVERSIBLE_MOTORS_CONFIG
	{ {69, 28, 98, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {3, 4}, (setting_offset_t)offsetof(reversibleMotorsConfig_t, deadband_low) },
	{ {69, 28, 235, 1, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {3, 4}, (setting_offset_t)offsetof(reversibleMotorsConfig_t, deadband_high) },
	{ {69, 146, 2, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {3, 4}, (setting_offset_t)offsetof(reversibleMotorsConfig_t, neutral) },
	// PG_SERVO_CONFIG
	{ {54, 151, 1, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_SERVO_PROTOCOL }, (setting_offset_t)offsetof(servoConfig_t, servo_protocol) },
	{ {54, 186, 1, 162, 2, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {3, 4}, (setting_offset_t)offsetof(servoConfig_t, servoCenterPulse) },
	{ {54, 64, 4, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {11, 64}, (setting_offset_t)offsetof(servoConfig_t, servoPwmRate) },
	{ {54, 24, 23, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {0, 44}, (setting_offset_t)offsetof(servoConfig_t, servo_lowpass_freq) },
	{ {219, 1, 199, 2, 78, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {11, 45}, (setting_offset_t)offsetof(servoConfig_t, flaperon_throw_offset) },
	{ {204, 2, 207, 2, 54, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(servoConfig_t, tri_unarmed_servo) },
	{ {54, 177, 1, 172, 2, 62}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {7, 61}, (setting_offset_t)offsetof(servoConfig_t, servo_autotrim_rotation_limit) },
	// PG_CONTROL_PROFILES
	{ {38, 252, 1, 0, 0, 0}, VAR_UINT8 | CONTROL_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(controlConfig_t, throttle.rcMid8) },
	{ {38, 40, 0, 0, 0, 0}, VAR_UINT8 | CONTROL_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(controlConfig_t, throttle.rcExpo8) },
	{ {172, 1, 158, 2, 0, 0}, VAR_UINT16 | CONTROL_VALUE, .config.minmax.indexes = {0, 6}, (setting_offset_t)offsetof(controlConfig_t, throttle.apa_pow) },
	{ {66, 4, 0, 0, 0, 0}, VAR_UINT8 | CONTROL_VALUE, .config.minmax.indexes = {0, 6}, (setting_offset_t)offsetof(controlConfig_t, throttle.dynPID) },
	{ {66, 182, 1, 0, 0, 0}, VAR_UINT16 | CONTROL_VALUE, .config.minmax.indexes = {3, 4}, (setting_offset_t)offsetof(controlConfig_t, throttle.pa_breakpoint) },
	{ {66, 8, 191, 1, 0, 0}, VAR_UINT8 | CONTROL_VALUE, .config.minmax.indexes = {0, 21}, (setting_offset_t)offsetof(controlConfig_t, throttle.tpa_pitch_compensation) },
	{ {66, 106, 5, 0, 0, 0}, VAR_UINT8 | CONTROL_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(controlConfig_t, throttle.dynPID_on_YAW) },
	{ {2, 66, 48, 193, 1, 0}, VAR_UINT16 | CONTROL_VALUE, .config.minmax.indexes = {0, 14}, (setting_offset_t)offsetof(controlConfig_t, throttle.fixedWingTauMs) },
	{ {42, 40, 0, 0, 0, 0}, VAR_UINT8 | CONTROL_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(controlConfig_t, stabilized.rcExpo8) },
	{ {42, 5, 40, 0, 0, 0}, VAR_UINT8 | CONTROL_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(controlConfig_t, stabilized.rcYawExpo8) },
	{ {14, 4, 0, 0, 0, 0}, VAR_UINT8 | CONTROL_VALUE, .config.minmax.indexes = {28, 22}, (setting_offset_t)offsetof(controlConfig_t, stabilized.rates[FD_ROLL]) },
	{ {8, 4, 0, 0, 0, 0}, VAR_UINT8 | CONTROL_VALUE, .config.minmax.indexes = {28, 22}, (setting_offset_t)offsetof(controlConfig_t, stabilized.rates[FD_PITCH]) },
	{ {5, 4, 0, 0, 0, 0}, VAR_UINT8 | CONTROL_VALUE, .config.minmax.indexes = {7, 22}, (setting_offset_t)offsetof(controlConfig_t, stabilized.rates[FD_YAW]) },
	{ {36, 42, 40, 0, 0, 0}, VAR_UINT8 | CONTROL_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(controlConfig_t, manual.rcExpo8) },
	{ {36, 42, 5, 40, 0, 0}, VAR_UINT8 | CONTROL_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(controlConfig_t, manual.rcYawExpo8) },
	{ {36, 14, 4, 0, 0, 0}, VAR_UINT8 | CONTROL_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(controlConfig_t, manual.rates[FD_ROLL]) },
	{ {36, 8, 4, 0, 0, 0}, VAR_UINT8 | CONTROL_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(controlConfig_t, manual.rates[FD_PITCH]) },
	{ {36, 5, 4, 0, 0, 0}, VAR_UINT8 | CONTROL_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(controlConfig_t, manual.rates[FD_YAW]) },
	{ {221, 1, 253, 1, 204, 1}, VAR_UINT8 | CONTROL_VALUE, .config.minmax.indexes = {0, 11}, (setting_offset_t)offsetof(controlConfig_t, misc.fpvCamAngleDegrees) },
	// PG_IMU_CONFIG
	{ {35, 74, 140, 1, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 20}, (setting_offset_t)offsetof(imuConfig_t, dcm_kp_acc) },
	{ {35, 74, 139, 1, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 20}, (setting_offset_t)offsetof(imuConfig_t, dcm_ki_acc) },
	{ {35, 74, 140, 1, 32, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 20}, (setting_offset_t)offsetof(imuConfig_t, dcm_kp_mag) },
	{ {35, 74, 139, 1, 32, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 20}, (setting_offset_t)offsetof(imuConfig_t, dcm_ki_mag) },
	{ {181, 2, 22, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 22}, (setting_offset_t)offsetof(imuConfig_t, small_angle) },
	{ {35, 34, 97, 4, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 29}, (setting_offset_t)offsetof(imuConfig_t, acc_ignore_rate) },
	{ {35, 34, 97, 180, 2, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 5}, (setting_offset_t)offsetof(imuConfig_t, acc_ignore_slope) },
	{ {35, 10, 5, 214, 2, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(imuConfig_t, gps_yaw_windcomp) },
	{ {35, 239, 1, 89, 251, 1}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_IMU_INERTIA_COMP_METHOD }, (setting_offset_t)offsetof(imuConfig_t, inertia_comp_method) },
	{ {35, 10, 5, 167, 1, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 13}, (setting_offset_t)offsetof(imuConfig_t, gps_yaw_weight) },
	// PG_ARMING_CONFIG
	{ {218, 1, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(armingConfig_t, fixed_wing_auto_arm) },
	{ {75, 171, 1, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(armingConfig_t, disarm_always) },
	{ {80, 75, 29, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 3}, (setting_offset_t)offsetof(armingConfig_t, switchDisarmDelayMs) },
	{ {159, 2, 112, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 15}, (setting_offset_t)offsetof(armingConfig_t, prearmTimeoutMs) },
	// PG_GENERAL_SETTINGS
	{ {173, 1, 203, 1, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 62}, (setting_offset_t)offsetof(generalSettings_t, appliedDefaults) },
	// PG_EZ_TUNE
	{ {30, 91, 0, 0, 0, 0}, VAR_UINT8 | EZ_TUNE_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(ezTuneSettings_t, enabled) },
	{ {30, 59, 23, 0, 0, 0}, VAR_UINT16 | EZ_TUNE_VALUE, .config.minmax.indexes = {21, 32}, (setting_offset_t)offsetof(ezTuneSettings_t, filterHz) },
	{ {30, 178, 1, 164, 2, 0}, VAR_UINT8 | EZ_TUNE_VALUE, .config.minmax.indexes = {40, 63}, (setting_offset_t)offsetof(ezTuneSettings_t, axisRatio) },
	{ {30, 155, 1, 0, 0, 0}, VAR_UINT8 | EZ_TUNE_VALUE, .config.minmax.indexes = {0, 6}, (setting_offset_t)offsetof(ezTuneSettings_t, response) },
	{ {30, 196, 1, 0, 0, 0}, VAR_UINT8 | EZ_TUNE_VALUE, .config.minmax.indexes = {0, 6}, (setting_offset_t)offsetof(ezTuneSettings_t, damping) },
	{ {30, 189, 2, 0, 0, 0}, VAR_UINT8 | EZ_TUNE_VALUE, .config.minmax.indexes = {0, 6}, (setting_offset_t)offsetof(ezTuneSettings_t, stability) },
	{ {30, 168, 1, 0, 0, 0}, VAR_UINT8 | EZ_TUNE_VALUE, .config.minmax.indexes = {0, 6}, (setting_offset_t)offsetof(ezTuneSettings_t, aggressiveness) },
	{ {30, 4, 0, 0, 0, 0}, VAR_UINT8 | EZ_TUNE_VALUE, .config.minmax.indexes = {0, 6}, (setting_offset_t)offsetof(ezTuneSettings_t, rate) },
	{ {30, 40, 0, 0, 0, 0}, VAR_UINT8 | EZ_TUNE_VALUE, .config.minmax.indexes = {0, 6}, (setting_offset_t)offsetof(ezTuneSettings_t, expo) },
	{ {30, 184, 2, 0, 0, 0}, VAR_UINT8 | EZ_TUNE_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(ezTuneSettings_t, snappiness) },
	// PG_GPS_CONFIG
	{ {10, 161, 2, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_GPS_PROVIDER }, (setting_offset_t)offsetof(gpsConfig_t, provider) },
	{ {10, 175, 2, 37, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_GPS_SBAS_MODE }, (setting_offset_t)offsetof(gpsConfig_t, sbasMode) },
	{ {10, 76, 144, 1, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_GPS_DYN_MODEL }, (setting_offset_t)offsetof(gpsConfig_t, dynModel) },
	{ {10, 27, 192, 1, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(gpsConfig_t, autoConfig) },
	{ {10, 27, 121, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(gpsConfig_t, autoBaud) },
	{ {10, 27, 121, 12, 194, 2}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_GPS_AUTO_BAUD_MAX }, (setting_offset_t)offsetof(gpsConfig_t, autoBaudMax) },
	{ {10, 82, 56, 229, 1, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(gpsConfig_t, ubloxUseGalileo) },
	{ {10, 82, 56, 180, 1, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(gpsConfig_t, ubloxUseBeidou) },
	{ {10, 82, 56, 230, 1, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(gpsConfig_t, ubloxUseGlonass) },
	{ {10, 15, 174, 2, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {10, 5}, (setting_offset_t)offsetof(gpsConfig_t, gpsMinSats) },
	{ {10, 82, 1, 23, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {10, 6}, (setting_offset_t)offsetof(gpsConfig_t, ubloxNavHz) },
	// PG_RC_CONTROLS_CONFIG
	{ {28, 0, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 59}, (setting_offset_t)offsetof(rcControlsConfig_t, deadband) },
	{ {5, 28, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(rcControlsConfig_t, yaw_deadband) },
	{ {13, 96, 28, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {12, 23}, (setting_offset_t)offsetof(rcControlsConfig_t, pos_hold_deadband) },
	{ {51, 96, 28, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {5, 23}, (setting_offset_t)offsetof(rcControlsConfig_t, alt_hold_deadband) },
	{ {69, 28, 33, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 6}, (setting_offset_t)offsetof(rcControlsConfig_t, mid_throttle_deadband) },
	{ {117, 26, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_AIRMODEHANDLINGTYPE }, (setting_offset_t)offsetof(rcControlsConfig_t, airmodeHandlingType) },
	{ {117, 33, 65, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {3, 4}, (setting_offset_t)offsetof(rcControlsConfig_t, airmodeThrottleThreshold) },
	// PG_PID_PROFILE
	{ {3, 7, 8, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_PITCH].P) },
	{ {3, 19, 8, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_PITCH].I) },
	{ {3, 17, 8, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_PITCH].D) },
	{ {3, 72, 8, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_PITCH].FF) },
	{ {3, 7, 14, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_ROLL].P) },
	{ {3, 19, 14, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_ROLL].I) },
	{ {3, 17, 14, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_ROLL].D) },
	{ {3, 72, 14, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_ROLL].FF) },
	{ {3, 7, 5, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_YAW].P) },
	{ {3, 19, 5, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_YAW].I) },
	{ {3, 17, 5, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_YAW].D) },
	{ {3, 72, 5, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_YAW].FF) },
	{ {3, 7, 41, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_LEVEL].P) },
	{ {3, 19, 41, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_LEVEL].I) },
	{ {3, 17, 41, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_LEVEL].D) },
	{ {2, 7, 8, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_PITCH].P) },
	{ {2, 19, 8, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_PITCH].I) },
	{ {2, 17, 8, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_PITCH].D) },
	{ {2, 58, 8, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_PITCH].FF) },
	{ {2, 7, 14, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_ROLL].P) },
	{ {2, 19, 14, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_ROLL].I) },
	{ {2, 17, 14, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_ROLL].D) },
	{ {2, 58, 14, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_ROLL].FF) },
	{ {2, 7, 5, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_YAW].P) },
	{ {2, 19, 5, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_YAW].I) },
	{ {2, 17, 5, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_YAW].D) },
	{ {2, 58, 5, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_YAW].FF) },
	{ {2, 7, 41, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_LEVEL].P) },
	{ {2, 19, 41, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_LEVEL].I) },
	{ {2, 17, 41, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_LEVEL].D) },
	{ {12, 22, 137, 1, 171, 2}, VAR_INT16 | PROFILE_VALUE, .config.minmax.indexes = {2, 33}, (setting_offset_t)offsetof(pidProfile_t, max_angle_inclination[FD_ROLL]) },
	{ {12, 22, 137, 1, 154, 2}, VAR_INT16 | PROFILE_VALUE, .config.minmax.indexes = {2, 33}, (setting_offset_t)offsetof(pidProfile_t, max_angle_inclination[FD_PITCH]) },
	{ {129, 1, 24, 23, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 13}, (setting_offset_t)offsetof(pidProfile_t, dterm_lpf_hz) },
	{ {129, 1, 24, 26, 0, 0}, VAR_UINT8 | PROFILE_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_FILTER_TYPE_FULL }, (setting_offset_t)offsetof(pidProfile_t, dterm_lpf_type) },
	{ {5, 24, 23, 0, 0, 0}, VAR_UINT8 | PROFILE_VALUE, .config.minmax.indexes = {0, 6}, (setting_offset_t)offsetof(pidProfile_t, yaw_lpf_hz) },
	{ {2, 168, 2, 169, 1, 0}, VAR_FLOAT | PROFILE_VALUE, .config.minmax.indexes = {32, 72}, (setting_offset_t)offsetof(pidProfile_t, fixedWingReferenceAirspeed) },
	{ {2, 114, 119, 5, 92, 0}, VAR_FLOAT | PROFILE_VALUE, .config.minmax.indexes = {0, 12}, (setting_offset_t)offsetof(pidProfile_t, fixedWingCoordinatedYawGain) },
	{ {2, 114, 119, 8, 92, 0}, VAR_FLOAT | PROFILE_VALUE, .config.minmax.indexes = {0, 12}, (setting_offset_t)offsetof(pidProfile_t, fixedWingCoordinatedPitchGain) },
	{ {228, 1, 0, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 30}, (setting_offset_t)offsetof(pidProfile_t, fixedWingYawItermBankFreeze) },
	{ {60, 215, 2, 0, 0, 0}, VAR_UINT8 | PROFILE_VALUE, .config.minmax.indexes = {0, 30}, (setting_offset_t)offsetof(pidProfile_t, itermWindupPointPercent) },
	{ {63, 60, 62, 151, 2, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 6}, (setting_offset_t)offsetof(pidProfile_t, pidItermLimitPercent) },
	{ {4, 83, 62, 14, 8, 0}, VAR_UINT32 | PROFILE_VALUE, .config.minmax.indexes = {0, 50}, (setting_offset_t)offsetof(pidProfile_t, axisAccelerationLimitRollPitch) },
	{ {4, 83, 62, 5, 0, 0}, VAR_UINT32 | PROFILE_VALUE, .config.minmax.indexes = {0, 50}, (setting_offset_t)offsetof(pidProfile_t, axisAccelerationLimitYaw) },
	{ {95, 96, 4, 62, 0, 0}, VAR_UINT8 | PROFILE_VALUE, .config.minmax.indexes = {5, 23}, (setting_offset_t)offsetof(pidProfile_t, heading_hold_rate_limit) },
	{ {1, 3, 13, 9, 7, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_POS_Z].P) },
	{ {1, 3, 50, 9, 7, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_VEL_Z].P) },
	{ {1, 3, 50, 9, 19, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_VEL_Z].I) },
	{ {1, 3, 50, 9, 17, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_VEL_Z].D) },
	{ {1, 3, 13, 21, 7, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_POS_XY].P) },
	{ {1, 3, 50, 21, 7, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_VEL_XY].P) },
	{ {1, 3, 50, 21, 19, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_VEL_XY].I) },
	{ {1, 3, 50, 21, 17, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_VEL_XY].D) },
	{ {1, 3, 50, 21, 58, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_VEL_XY].FF) },
	{ {1, 3, 95, 7, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_mc.pid[PID_HEADING].P) },
	{ {140, 2, 0, 0, 0, 0}, VAR_FLOAT | PROFILE_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(pidProfile_t, navVelXyDTermLpfHz) },
	{ {137, 2, 0, 0, 0, 0}, VAR_UINT8 | PROFILE_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(pidProfile_t, navVelXyDtermAttenuation) },
	{ {139, 2, 0, 0, 0, 0}, VAR_UINT8 | PROFILE_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(pidProfile_t, navVelXyDtermAttenuationStart) },
	{ {138, 2, 0, 0, 0, 0}, VAR_UINT8 | PROFILE_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(pidProfile_t, navVelXyDtermAttenuationEnd) },
	{ {1, 2, 13, 9, 7, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_POS_Z].P) },
	{ {1, 2, 13, 9, 19, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_POS_Z].I) },
	{ {1, 2, 13, 9, 17, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_POS_Z].D) },
	{ {1, 2, 13, 9, 58, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_POS_Z].FF) },
	{ {1, 2, 51, 45, 155, 1}, VAR_UINT8 | PROFILE_VALUE, .config.minmax.indexes = {10, 2}, (setting_offset_t)offsetof(pidProfile_t, fwAltControlResponseFactor) },
	{ {1, 2, 51, 56, 147, 1}, VAR_UINT8 | PROFILE_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(pidProfile_t, fwAltControlUsePos) },
	{ {1, 2, 13, 21, 7, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_POS_XY].P) },
	{ {1, 2, 13, 21, 19, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_POS_XY].I) },
	{ {1, 2, 13, 21, 17, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_POS_XY].D) },
	{ {1, 2, 95, 7, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_HEADING].P) },
	{ {1, 2, 13, 94, 7, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_POS_HEADING].P) },
	{ {1, 2, 13, 94, 19, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_POS_HEADING].I) },
	{ {1, 2, 13, 94, 17, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(pidProfile_t, bank_fw.pid[PID_POS_HEADING].D) },
	{ {131, 2, 0, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {2, 3}, (setting_offset_t)offsetof(pidProfile_t, navFwPosHdgPidsumLimit) },
	{ {3, 60, 153, 1, 0, 0}, VAR_UINT8 | PROFILE_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_ITERM_RELAX }, (setting_offset_t)offsetof(pidProfile_t, iterm_relax) },
	{ {3, 60, 153, 1, 124, 0}, VAR_UINT8 | PROFILE_VALUE, .config.minmax.indexes = {7, 2}, (setting_offset_t)offsetof(pidProfile_t, iterm_relax_cutoff) },
	{ {63, 26, 0, 0, 0, 0}, VAR_UINT8 | PROFILE_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_PIDTYPETABLE }, (setting_offset_t)offsetof(pidProfile_t, pidControllerType) },
	{ {3, 72, 24, 23, 0, 0}, VAR_UINT8 | PROFILE_VALUE, .config.minmax.indexes = {0, 6}, (setting_offset_t)offsetof(pidProfile_t, controlDerivativeLpfHz) },
	{ {2, 41, 8, 205, 2, 0}, VAR_FLOAT | PROFILE_VALUE, .config.minmax.indexes = {56, 5}, (setting_offset_t)offsetof(pidProfile_t, fixedWingLevelTrim) },
	{ {2, 41, 8, 92, 0, 0}, VAR_FLOAT | PROFILE_VALUE, .config.minmax.indexes = {0, 21}, (setting_offset_t)offsetof(pidProfile_t, fixedWingLevelTrimGain) },
	{ {227, 1, 0, 0, 0, 0}, VAR_UINT16 | PROFILE_VALUE, .config.minmax.indexes = {2, 3}, (setting_offset_t)offsetof(pidProfile_t, fwItermLockTimeMaxMs) },
	{ {2, 60, 245, 1, 4, 65}, VAR_UINT8 | PROFILE_VALUE, .config.minmax.indexes = {5, 2}, (setting_offset_t)offsetof(pidProfile_t, fwItermLockRateLimit) },
	{ {226, 1, 0, 0, 0, 0}, VAR_UINT8 | PROFILE_VALUE, .config.minmax.indexes = {10, 40}, (setting_offset_t)offsetof(pidProfile_t, fwItermLockEngageThreshold) },
	// PG_POSITION_ESTIMATION_CONFIG
	{ {6, 27, 32, 200, 1, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(positionEstimationConfig_t, automatic_mag_declination) },
	{ {6, 134, 1, 88, 160, 1}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(positionEstimationConfig_t, gravity_calibration_tolerance) },
	{ {6, 118, 197, 1, 166, 2}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(positionEstimationConfig_t, allow_dead_reckoning) },
	{ {6, 108, 44, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_RESET_TYPE }, (setting_offset_t)offsetof(positionEstimationConfig_t, reset_altitude_type) },
	{ {6, 108, 136, 1, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_RESET_TYPE }, (setting_offset_t)offsetof(positionEstimationConfig_t, reset_home_type) },
	{ {6, 12, 111, 44, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 3}, (setting_offset_t)offsetof(positionEstimationConfig_t, max_surface_altitude) },
	{ {6, 20, 9, 111, 7, 0}, VAR_FLOAT | MASTER_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(positionEstimationConfig_t, w_z_surface_p) },
	{ {6, 20, 9, 111, 49, 0}, VAR_FLOAT | MASTER_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(positionEstimationConfig_t, w_z_surface_v) },
	{ {6, 20, 21, 133, 1, 7}, VAR_FLOAT | MASTER_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(positionEstimationConfig_t, w_xy_flow_p) },
	{ {6, 20, 21, 133, 1, 49}, VAR_FLOAT | MASTER_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(positionEstimationConfig_t, w_xy_flow_v) },
	{ {6, 20, 9, 52, 7, 0}, VAR_FLOAT | MASTER_VALUE, .config.minmax.indexes = {0, 5}, (setting_offset_t)offsetof(positionEstimationConfig_t, w_z_baro_p) },
	{ {6, 20, 9, 52, 49, 0}, VAR_FLOAT | MASTER_VALUE, .config.minmax.indexes = {0, 5}, (setting_offset_t)offsetof(positionEstimationConfig_t, w_z_baro_v) },
	{ {6, 20, 9, 10, 7, 0}, VAR_FLOAT | MASTER_VALUE, .config.minmax.indexes = {0, 5}, (setting_offset_t)offsetof(positionEstimationConfig_t, w_z_gps_p) },
	{ {6, 20, 9, 10, 49, 0}, VAR_FLOAT | MASTER_VALUE, .config.minmax.indexes = {0, 5}, (setting_offset_t)offsetof(positionEstimationConfig_t, w_z_gps_v) },
	{ {6, 20, 21, 10, 7, 0}, VAR_FLOAT | MASTER_VALUE, .config.minmax.indexes = {0, 5}, (setting_offset_t)offsetof(positionEstimationConfig_t, w_xy_gps_p) },
	{ {6, 20, 21, 10, 49, 0}, VAR_FLOAT | MASTER_VALUE, .config.minmax.indexes = {0, 5}, (setting_offset_t)offsetof(positionEstimationConfig_t, w_xy_gps_v) },
	{ {6, 20, 9, 154, 1, 49}, VAR_FLOAT | MASTER_VALUE, .config.minmax.indexes = {0, 5}, (setting_offset_t)offsetof(positionEstimationConfig_t, w_z_res_v) },
	{ {6, 20, 21, 154, 1, 49}, VAR_FLOAT | MASTER_VALUE, .config.minmax.indexes = {0, 5}, (setting_offset_t)offsetof(positionEstimationConfig_t, w_xy_res_v) },
	{ {6, 20, 34, 181, 1, 0}, VAR_FLOAT | MASTER_VALUE, .config.minmax.indexes = {0, 7}, (setting_offset_t)offsetof(positionEstimationConfig_t, w_acc_bias) },
	{ {6, 12, 212, 1, 131, 1}, VAR_FLOAT | MASTER_VALUE, .config.minmax.indexes = {0, 49}, (setting_offset_t)offsetof(positionEstimationConfig_t, max_eph_epv) },
	{ {6, 52, 131, 1, 0, 0}, VAR_FLOAT | MASTER_VALUE, .config.minmax.indexes = {0, 49}, (setting_offset_t)offsetof(positionEstimationConfig_t, baro_epv) },
	{ {6, 202, 1, 51, 178, 2}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_DEFAULT_ALTITUDE_SOURCE }, (setting_offset_t)offsetof(positionEstimationConfig_t, default_alt_sensor) },
	// PG_NAV_CONFIG
	{ {1, 75, 106, 61, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(navConfig_t, general.flags.disarm_on_landing) },
	{ {1, 46, 125, 177, 2, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {7, 18}, (setting_offset_t)offsetof(navConfig_t, general.land_detect_sensitivity) },
	{ {1, 61, 183, 1, 205, 1}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(navConfig_t, general.flags.landing_bump_detection) },
	{ {136, 2, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 18}, (setting_offset_t)offsetof(navConfig_t, mc.inverted_crash_detection) },
	{ {1, 3, 170, 1, 33, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_NAV_MC_ALTHOLD_THROTTLE }, (setting_offset_t)offsetof(navConfig_t, mc.althold_throttle_type) },
	{ {128, 2, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_NAV_EXTRA_ARMING_SAFETY }, (setting_offset_t)offsetof(navConfig_t, general.flags.extra_arming_safety) },
	{ {1, 210, 2, 45, 37, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_NAV_USER_CONTROL_MODE }, (setting_offset_t)offsetof(navConfig_t, general.flags.user_control_mode) },
	{ {1, 147, 1, 112, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 5}, (setting_offset_t)offsetof(navConfig_t, general.pos_failure_timeout) },
	{ {145, 2, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(navConfig_t, general.waypoint_load_on_boot) },
	{ {1, 57, 152, 1, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {5, 15}, (setting_offset_t)offsetof(navConfig_t, general.waypoint_radius) },
	{ {1, 57, 211, 1, 44, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 4}, (setting_offset_t)offsetof(navConfig_t, general.waypoint_enforce_altitude) },
	{ {1, 57, 12, 173, 2, 53}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 68}, (setting_offset_t)offsetof(navConfig_t, general.waypoint_safe_distance) },
	{ {1, 57, 102, 170, 2, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_NAV_WP_MISSION_RESTART }, (setting_offset_t)offsetof(navConfig_t, general.flags.waypoint_mission_restart) },
	{ {133, 2, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 5}, (setting_offset_t)offsetof(navConfig_t, fw.wp_tracking_accuracy) },
	{ {134, 2, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {29, 24}, (setting_offset_t)offsetof(navConfig_t, fw.wp_tracking_max_angle) },
	{ {1, 2, 57, 114, 110, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_NAV_FW_WP_TURN_SMOOTHING }, (setting_offset_t)offsetof(navConfig_t, fw.wp_turn_smoothing) },
	{ {1, 27, 55, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {5, 4}, (setting_offset_t)offsetof(navConfig_t, general.auto_speed) },
	{ {1, 15, 231, 1, 55, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {58, 11}, (setting_offset_t)offsetof(navConfig_t, general.min_ground_speed) },
	{ {1, 12, 27, 55, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {5, 4}, (setting_offset_t)offsetof(navConfig_t, general.max_auto_speed) },
	{ {1, 36, 55, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {5, 4}, (setting_offset_t)offsetof(navConfig_t, general.max_manual_speed) },
	{ {1, 46, 143, 1, 166, 1}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {11, 13}, (setting_offset_t)offsetof(navConfig_t, general.land_minalt_vspd) },
	{ {1, 46, 142, 1, 166, 1}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {2, 4}, (setting_offset_t)offsetof(navConfig_t, general.land_maxalt_vspd) },
	{ {1, 46, 109, 143, 1, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {11, 3}, (setting_offset_t)offsetof(navConfig_t, general.land_slowdown_minalt) },
	{ {1, 46, 109, 142, 1, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {13, 71}, (setting_offset_t)offsetof(navConfig_t, general.land_slowdown_maxalt) },
	{ {1, 130, 1, 61, 55, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {2, 4}, (setting_offset_t)offsetof(navConfig_t, general.emerg_descent_rate) },
	{ {1, 15, 16, 53, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 14}, (setting_offset_t)offsetof(navConfig_t, general.min_rth_distance) },
	{ {1, 150, 2, 47, 192, 2}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_NAV_OVERRIDES_MOTOR_STOP }, (setting_offset_t)offsetof(navConfig_t, general.flags.nav_overrides_motor_stop) },
	{ {132, 2, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(navConfig_t, general.flags.soaring_motor_stop) },
	{ {1, 2, 185, 2, 8, 28}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 18}, (setting_offset_t)offsetof(navConfig_t, fw.soaring_pitch_deadband) },
	{ {1, 16, 39, 132, 1, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_NAV_RTH_CLIMB_FIRST }, (setting_offset_t)offsetof(navConfig_t, general.flags.rth_climb_first) },
	{ {142, 2, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_NAV_RTH_CLIMB_FIRST_STAGE_MODES }, (setting_offset_t)offsetof(navConfig_t, general.flags.rth_climb_first_stage_mode) },
	{ {141, 2, 0, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 16}, (setting_offset_t)offsetof(navConfig_t, general.rth_climb_first_stage_altitude) },
	{ {1, 16, 39, 97, 130, 1}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(navConfig_t, general.flags.rth_climb_ignore_emerg) },
	{ {1, 16, 197, 2, 132, 1}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(navConfig_t, general.flags.rth_tail_first) },
	{ {1, 16, 118, 61, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_NAV_RTH_ALLOW_LANDING }, (setting_offset_t)offsetof(navConfig_t, general.flags.rth_allow_landing) },
	{ {1, 16, 224, 1, 61, 29}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 69}, (setting_offset_t)offsetof(navConfig_t, general.rth_fs_landing_delay) },
	{ {1, 16, 51, 37, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_NAV_RTH_ALT_MODE }, (setting_offset_t)offsetof(navConfig_t, general.flags.rth_alt_control_mode) },
	{ {1, 16, 51, 45, 149, 2}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(navConfig_t, general.flags.rth_alt_control_override) },
	{ {1, 16, 116, 65, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 16}, (setting_offset_t)offsetof(navConfig_t, general.rth_abort_threshold) },
	{ {135, 2, 0, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 3}, (setting_offset_t)offsetof(navConfig_t, general.max_terrain_follow_altitude) },
	{ {1, 12, 44, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 16}, (setting_offset_t)offsetof(navConfig_t, general.max_altitude) },
	{ {1, 16, 44, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 16}, (setting_offset_t)offsetof(navConfig_t, general.rth_altitude) },
	{ {1, 16, 136, 1, 44, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 16}, (setting_offset_t)offsetof(navConfig_t, general.rth_home_altitude) },
	{ {143, 2, 0, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 15}, (setting_offset_t)offsetof(navConfig_t, general.rth_linear_descent_start_distance) },
	{ {144, 2, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(navConfig_t, general.flags.rth_use_linear_descent) },
	{ {1, 16, 161, 1, 37, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_RTH_TRACKBACK_MODE }, (setting_offset_t)offsetof(navConfig_t, general.flags.rth_trackback_mode) },
	{ {1, 16, 161, 1, 53, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {11, 4}, (setting_offset_t)offsetof(navConfig_t, general.rth_trackback_distance) },
	{ {157, 1, 12, 53, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 16}, (setting_offset_t)offsetof(navConfig_t, general.safehome_max_distance) },
	{ {157, 1, 209, 2, 37, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_SAFEHOME_USAGE_MODE }, (setting_offset_t)offsetof(navConfig_t, general.flags.safehome_usage_mode) },
	{ {1, 102, 155, 2, 108, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(navConfig_t, general.flags.mission_planner_reset) },
	{ {1, 73, 5, 4, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 31}, (setting_offset_t)offsetof(navConfig_t, general.cruise_yaw_rate) },
	{ {1, 3, 120, 22, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {18, 42}, (setting_offset_t)offsetof(navConfig_t, mc.max_bank_angle) },
	{ {1, 3, 27, 39, 4, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {5, 4}, (setting_offset_t)offsetof(navConfig_t, mc.max_auto_climb_rate) },
	{ {1, 3, 36, 39, 4, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {5, 4}, (setting_offset_t)offsetof(navConfig_t, mc.max_manual_climb_rate) },
	{ {1, 27, 75, 29, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {2, 15}, (setting_offset_t)offsetof(navConfig_t, general.auto_disarm_delay) },
	{ {1, 3, 13, 199, 1, 48}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(navConfig_t, mc.posDecelerationTime) },
	{ {1, 3, 13, 40, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(navConfig_t, mc.posResponseExpo) },
	{ {1, 3, 57, 109, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(navConfig_t, mc.slowDownForTurning) },
	{ {1, 2, 120, 22, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {10, 24}, (setting_offset_t)offsetof(navConfig_t, fw.max_bank_angle) },
	{ {1, 2, 27, 39, 4, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {5, 4}, (setting_offset_t)offsetof(navConfig_t, fw.max_auto_climb_rate) },
	{ {1, 2, 36, 39, 4, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {5, 70}, (setting_offset_t)offsetof(navConfig_t, fw.max_manual_climb_rate) },
	{ {1, 2, 39, 22, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {10, 24}, (setting_offset_t)offsetof(navConfig_t, fw.max_climb_angle) },
	{ {1, 2, 127, 22, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {10, 24}, (setting_offset_t)offsetof(navConfig_t, fw.max_dive_angle) },
	{ {1, 2, 107, 110, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 38}, (setting_offset_t)offsetof(navConfig_t, fw.pitch_to_throttle_smooth) },
	{ {2, 15, 33, 207, 1, 8}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 45}, (setting_offset_t)offsetof(navConfig_t, fw.minThrottleDownPitchAngle) },
	{ {1, 2, 107, 65, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 33}, (setting_offset_t)offsetof(navConfig_t, fw.pitch_to_throttle_thresh) },
	{ {1, 2, 141, 1, 152, 1}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 76}, (setting_offset_t)offsetof(navConfig_t, fw.loiter_radius) },
	{ {2, 141, 1, 126, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_DIRECTION }, (setting_offset_t)offsetof(navConfig_t, fw.loiter_direction) },
	{ {1, 2, 73, 55, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 20}, (setting_offset_t)offsetof(navConfig_t, fw.cruise_speed) },
	{ {1, 2, 45, 183, 2, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 38}, (setting_offset_t)offsetof(navConfig_t, fw.control_smoothness) },
	{ {1, 2, 46, 127, 22, 0}, VAR_INT8 | MASTER_VALUE, .config.minmax.indexes = {55, 21}, (setting_offset_t)offsetof(navConfig_t, fw.land_dive_angle) },
	{ {1, 2, 11, 211, 2, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {2, 15}, (setting_offset_t)offsetof(navConfig_t, fw.launch_velocity_thresh) },
	{ {1, 2, 11, 83, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {67, 75}, (setting_offset_t)offsetof(navConfig_t, fw.launch_accel_thresh) },
	{ {1, 2, 11, 12, 22, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {10, 22}, (setting_offset_t)offsetof(navConfig_t, fw.launch_max_angle) },
	{ {1, 2, 11, 125, 48, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {5, 3}, (setting_offset_t)offsetof(navConfig_t, fw.launch_time_thresh) },
	{ {1, 2, 11, 77, 47, 29}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 25}, (setting_offset_t)offsetof(navConfig_t, fw.launch_idle_motor_timer) },
	{ {130, 2, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 12}, (setting_offset_t)offsetof(navConfig_t, fw.launch_wiggle_wake_idle) },
	{ {1, 2, 11, 47, 29, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 14}, (setting_offset_t)offsetof(navConfig_t, fw.launch_motor_timer) },
	{ {1, 2, 11, 187, 2, 48}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 3}, (setting_offset_t)offsetof(navConfig_t, fw.launch_motor_spinup_time) },
	{ {1, 2, 11, 209, 1, 48}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 14}, (setting_offset_t)offsetof(navConfig_t, fw.launch_end_time) },
	{ {1, 2, 11, 15, 48, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 25}, (setting_offset_t)offsetof(navConfig_t, fw.launch_min_time) },
	{ {1, 2, 11, 112, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 25}, (setting_offset_t)offsetof(navConfig_t, fw.launch_timeout) },
	{ {1, 2, 11, 12, 44, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {0, 25}, (setting_offset_t)offsetof(navConfig_t, fw.launch_max_altitude) },
	{ {1, 2, 11, 39, 22, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {10, 42}, (setting_offset_t)offsetof(navConfig_t, fw.launch_climb_angle) },
	{ {1, 2, 11, 36, 33, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(navConfig_t, fw.launch_manual_throttle) },
	{ {1, 2, 11, 46, 116, 28}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {12, 23}, (setting_offset_t)offsetof(navConfig_t, fw.launch_land_abort_deadband) },
	{ {129, 2, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(navConfig_t, fw.allow_manual_thr_increase) },
	{ {1, 56, 2, 5, 45, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(navConfig_t, fw.useFwNavYawControl) },
	{ {1, 2, 5, 28, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 30}, (setting_offset_t)offsetof(navConfig_t, fw.yawControlDeadband) },
	// PG_TELEMETRY_CONFIG
	{ {81, 80, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(telemetryConfig_t, telemetry_switch) },
	{ {81, 138, 1, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(telemetryConfig_t, telemetry_inverted) },
	{ {222, 1, 8, 14, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(telemetryConfig_t, frsky_pitch_roll) },
	{ {223, 1, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(telemetryConfig_t, frsky_use_legacy_gps_mode_sensor_ids) },
	{ {169, 2, 185, 1, 165, 1}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(telemetryConfig_t, report_cell_voltage) },
	{ {236, 1, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 31}, (setting_offset_t)offsetof(telemetryConfig_t, hottAlarmSoundInterval) },
	{ {81, 135, 1, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(telemetryConfig_t, halfDuplex) },
	{ {182, 2, 225, 1, 163, 1}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_SMARTPORT_FUEL_UNIT }, (setting_offset_t)offsetof(telemetryConfig_t, smartportFuelUnit) },
	{ {238, 1, 81, 26, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(telemetryConfig_t, ibusTelemetryType) },
	{ {247, 1, 208, 2, 4, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_LTM_RATES }, (setting_offset_t)offsetof(telemetryConfig_t, ltmUpdateRate) },
	{ {25, 213, 1, 190, 2, 4}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(telemetryConfig_t, mavlink.extended_status_rate) },
	{ {25, 176, 1, 26, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_MAVLINK_AUTOPILOT_TYPE }, (setting_offset_t)offsetof(telemetryConfig_t, mavlink.autopilot_type) },
	{ {25, 42, 187, 1, 4, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(telemetryConfig_t, mavlink.rc_channels_rate) },
	{ {25, 13, 4, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(telemetryConfig_t, mavlink.position_rate) },
	{ {25, 214, 1, 4, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(telemetryConfig_t, mavlink.extra1_rate) },
	{ {25, 215, 1, 4, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(telemetryConfig_t, mavlink.extra2_rate) },
	{ {25, 216, 1, 4, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 1}, (setting_offset_t)offsetof(telemetryConfig_t, mavlink.extra3_rate) },
	{ {25, 212, 2, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {7, 12}, (setting_offset_t)offsetof(telemetryConfig_t, mavlink.version) },
	{ {25, 15, 206, 2, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(telemetryConfig_t, mavlink.min_txbuff) },
	{ {25, 163, 2, 26, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_MAVLINK_RADIO_TYPE }, (setting_offset_t)offsetof(telemetryConfig_t, mavlink.radio_type) },
	{ {25, 196, 2, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {7, 1}, (setting_offset_t)offsetof(telemetryConfig_t, mavlink.sysid) },
	// PG_SYSTEM_CONFIG
	{ {198, 1, 37, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_DEBUG_MODES }, (setting_offset_t)offsetof(systemConfig_t, debug_mode) },
	{ {33, 200, 2, 89, 193, 2}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {0, 2}, (setting_offset_t)offsetof(systemConfig_t, throttle_tilt_compensation_strength) },
	{ {145, 1, 0, 0, 0, 0}, VAR_STRING | MASTER_VALUE, .config.minmax.indexes = {0, 39}, (setting_offset_t)offsetof(systemConfig_t, craftName) },
	{ {152, 2, 145, 1, 0, 0}, VAR_STRING | MASTER_VALUE, .config.minmax.indexes = {0, 39}, (setting_offset_t)offsetof(systemConfig_t, pilotName) },
	// PG_MODE_ACTIVATION_OPERATOR_CONFIG
	{ {254, 1, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_AUX_OPERATOR }, (setting_offset_t)offsetof(modeActivationOperatorConfig_t, modeActivationOperator) },
	// PG_TIME_CONFIG
	{ {162, 1, 78, 0, 0, 0}, VAR_INT16 | MASTER_VALUE, .config.minmax.indexes = {54, 66}, (setting_offset_t)offsetof(timeConfig_t, tz_offset) },
	{ {162, 1, 175, 1, 208, 1}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_TZ_AUTOMATIC_DST }, (setting_offset_t)offsetof(timeConfig_t, tz_automatic_dst) },
	// PG_DISPLAY_CONFIG
	{ {206, 1, 0, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(displayConfig_t, force_sw_blink) },
	// PG_BEEPER_CONFIG
	{ {128, 1, 86, 91, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(beeperConfig_t, dshot_beeper_enabled) },
	{ {128, 1, 86, 202, 2, 0}, VAR_UINT8 | MASTER_VALUE, .config.minmax.indexes = {7, 10}, (setting_offset_t)offsetof(beeperConfig_t, dshot_beeper_tone) },
	{ {86, 64, 37, 0, 0, 0}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OFF_ON }, (setting_offset_t)offsetof(beeperConfig_t, pwmMode) },
	// PG_LEDPIN_CONFIG
	{ {243, 1, 153, 2, 64, 37}, VAR_UINT8 | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_LED_PIN_PWM_MODE }, (setting_offset_t)offsetof(ledPinConfig_t, led_pin_pwm_mode) },
};
